### ISSUE TITLE
Forum notifications

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#100]
When someone comment a post that i commented too i don't recive any notification, I'm not sure it's a bug but in the past i was receiving an alert when this event happened, or maybe i just remember wrong

**Comment by StephenPuffs** [comment]
Pretty sure it's always been that way on a post that isn't your own, so just check back manually to see.

**Comment by Bamarin** [comment]
I was right: http://imgur.com/ZoUa1fk
It should be fixed now, but maybe there are still some cases when the alert isn't sent. I'll leave another comment if it happends again
