### ISSUE TITLE
Craftable Chests

### ISSUE THREAD

**Issue by affgaming** [syl0r/Perpheads-Issues#102]
Craftable Chests when placed down can be accessed by some people who are not on your buddy list. 

For example, I had my chest downstairs, and Aaron Doman was able to access it even though he wasn't on my buddy list at all.

As far as I know, Creepis has had this same issue too.

If needed, I can get the demo.

**Comment by Creepis** [comment]
I can pretty much confirm this, people could access my craftable chest's even though they were not in my buddy list.I tried to access other people's chest's too, which didn't work for me at all.
