### ISSUE TITLE
Respawning does not happen at all

### ISSUE THREAD

**Issue by Creepis** [syl0r/Perpheads-Issues#104]
I don't really have any reproducing steps for this one but there's been an issue with respawning for some time now.Basically, when you are completly dead (black screen) you simply won't respawn anymore, at all, waiting does not obviously help and the only way to respawn is to /report the issue and let an administrator respawn you.However, this issue is quite rare and does not occur often.

**Comment by StephenPuffs** [comment]
One useful bit of information would be simply how did you die?

**Comment by Creepis** [comment]
It happened to me once when I have been shot down (don't really remember which weapon did but I guess it does not really matter by which weapon you died) as a civilian.As close as I can remember, I was shot down by an Officer with an M9 Berreta, there were no medics on duty at the time so I did not get revived and the black screen (the state when reviving is no longer possible by a medic) just stood.

Sorry for making this look like a mess but I really don't have any reproduction steps.This did happen to some other people as well and I am not just the only one who noticed this problem.

**Comment by StephenPuffs** [comment]
I've only had a reported case one time and sadly didn't really do much testing at the time, but that was all the way back on Evo City, and haven't been around when it's happened to someone now so I can't easily check as to what may cause it, but nothing should.  Love bugs like these...

**Comment by Creepis** [comment]
Got some new information by Andrew™ (thanks for telling me!):

Today, Andrew™ just had this problem.He died to the cops by an M9 Berreta while picking up a gun during the raid, while he was still equipping, he died and this bug occured where he never respawned until an administrator revived him.All the information you need really.

**Comment by StephenPuffs** [comment]
Thank you for this report it was actually very helpful.  Found out it comes down to a GMod flaw, but all is good now, will be fixed in next update.
