### ISSUE TITLE
No Custom Clothing

### ISSUE THREAD

**Issue by MartinGarekt** [syl0r/Perpheads-Issues#108]
i recently started playing Perp again. But for some reason I can't see custom clothing. I mean i got all the packs on Workshop and The Website. I type stop in console. Nothing works!
http://steamcommunity.com/sharedfiles/filedetails/?id=437243971

**Comment by Bolli123** [comment]
You're using our old content, uninstall the content you have, download the new one and install it
https://perpheads.com/link-forums/content.57/
