### ISSUE TITLE
Can't make Big Marijuana pots. 

### ISSUE THREAD

**Issue by KermitTheThug** [syl0r/Perpheads-Issues#109]
Even though I have the right skills and the correct ingredients, I cannot craft Big Marijuana pots. I would assume the same for Cocaine too.

**Comment by Bolli123** [comment]
Do you have big pots? If not craft them under 'mixed materials'

**Comment by KermitTheThug** [comment]
Oh wow. Didn't realize that was a thing. Sorry to waste your time.
