### ISSUE TITLE
Tax / city funds system is total not working 

### ISSUE THREAD

**Issue by moher4** [syl0r/Perpheads-Issues#110]
when there is a mayor city funds will drop no matter what you do even put full tax on every thing and put the job income and slots and all to the lowest possible funds only go up when there is no mayor it is bugged or broken and sometimes it happens where if you as mayor set the taxes to 0 and fuel to max and income to 20 the funds instantly become 16-20k and stay at it for 1 hour then start to go down till it hits 0

**Comment by JDaymon** [comment]
I went mayor for this and I didn't get the same affect that you explained so I guess we cannot reproduce this.

**Comment by moher4** [comment]
it dose not always happen i dont know why but i notice it happens when there is no sargents and LT
