### ISSUE TITLE
AdminTV

### ISSUE THREAD

**Issue by Creepis** [syl0r/Perpheads-Issues#113]
Not sure if this has already been reported by a staff member but here it is anyways.Play any video on the AdminTV and it will show up like this:
![2015-05-17_00006](https://cloud.githubusercontent.com/assets/10688184/7672240/2d3c6da0-fceb-11e4-950f-f4d114d92499.jpg)
Another one:
![2015-05-10_00003](https://cloud.githubusercontent.com/assets/10688184/7672242/36364e58-fceb-11e4-8c3d-d121fd120c37.jpg)

**Comment by JDaymon** [comment]
I can confirm this, had a cinema at farm
