### ISSUE TITLE
Death Model

### ISSUE THREAD

**Issue by Haydenp10** [syl0r/Perpheads-Issues#114]
Basiclly when I die this happens!
Look at the image : http://images.akamai.steamusercontent.com/ugc/715289650366670262/6FF2B2392DD8A1DB2AD0760A466D15EE97FF9AD2/

**Comment by Minilarro** [comment]
Now, I don't think what I'm saying is a bug, but whenever someone dies/gets unconscious, I see this for a split secound before the ragdoll works properly, just thought I'd ask if that's a bug or nothing to be done with?

**Comment by Bolli123** [comment]
Please provide more information, but it's probably just a missing file on your end
