### ISSUE TITLE
Delivery Guy

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#115]
There are some cases when you are working as a delivery guy where you have no longer the item that makes you able to drop the package someone ordered (key '2' of the keyboard).
One of these cases happens when you die as a delivery guy: you will respawn inside the delivery warehouse, and you still have your job, but the only items you have are keys and fists (+ physgun if you are VIP, and camera/binocular/... if you have them on you) so if you speak with the NPC, after you get an ordination, you will get the job to delivery the package to him, but you won't be able to drop it.
For now the only way to fix this is going out of service and then becoming a delivery guy again, but you will lost the ordination.
N.B. there are many other ways the package on the '2' can disappear, but i didn't find out when they happens

**Comment by Bamarin** [comment]
I'll state here another bug, which is related to delivery guy too, but i'll make another thread if it's needed.

Every day I join, the delivery warehouse is locked, i have noticed it for the last 3 days. So I guess that after the last update the delivery warehouse doors starts locked when the server restarts. This is a big problem since the delivery guy hasn't the key and so he's forced to call a mod or higher to open it

**Comment by StephenPuffs** [comment]
In response to the place being locked, it was made this way on purpose, as some people were using it to grow inside of or hide from cops with no consideration to the NPC or people that would be inside working.  So that was intentionally done, as for the delivery tool disappearing, I have fixed that for next update which should fix it in all cases (hopefully).

**Comment by Bamarin** [comment]
Ok but can you give to deliveryman the key of the delivery warehouse at least?
