### ISSUE TITLE
Ticket issue

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#116]
When an officer give you a "personal ticket" (i mean those that have a description), if you don't have  enough money on you, even if you press "I'll pay the ticket" the officer will see a pop-up saying "The suspect refused to pay the ticket"

**Comment by Bolli123** [comment]
The ticket takes from the bank, not money on hand

**Comment by syl0r** [comment]
No, he sees the message "The individual wanted to pay the ticket but couldn't afford it."
