### ISSUE TITLE
Bank robbery didn't work correctyl

### ISSUE THREAD

**Issue by FluxxLSX** [syl0r/Perpheads-Issues#119]
I tried to rob the bank, i pointed the gun at the dude behind the desk and went inside the vault...

it then pops up "You are not in the vault the robbery has been cancelled", this is complete bullshit as i spent so much money arming up for a bug to break my game :'c

Demo aka proof: http://fluxx.pw/bankrobbery.dem

it is near the end of the demo when i robbed it.

**Comment by FluxxLSX** [comment]
Tick 25500

**Comment by PHSneaky** [comment]
Guessing this has been fixed now

**Comment by jimmythehamster** [comment]
Bank robberies are still bugged, was going to open a new report but saw this one thats been open for a year.

**Comment by syl0r** [comment]
Fixed
