### ISSUE TITLE
Crafting a storage chest does not remove your wood nails from your inventory when crafted

### ISSUE THREAD

**Issue by Creepis** [syl0r/Perpheads-Issues#121]
^title, should be simple, craft a chest and notice that your 10 wood nails are still in your inventory and not used up in the process of crafting the chest.

**Comment by Minilarro** [comment]
This happens for several other mixtures aswell as I've noticed, leading to the person crafting saving an amount of materials. This does not happen on all occasions, however for me it's maybe a chance of 1 out of 15? Not completely sure as I don't keep a peeled eye on all the materials after crafting an item.

**Comment by JDaymon** [comment]
I can confirm this, although I cannot craft this myself I've seen a video of toffel trying to do so and it did not remove the nails for him.
