### ISSUE TITLE
An issue with the unstuck system

### ISSUE THREAD

**Issue by hazza56** [syl0r/Perpheads-Issues#122]
As you probably saw on my refund request, the unstuck system is a bit flawed. I got stuck inside a table and it sent me flying in the air causing me to lose an AK, here is an example:https://youtu.be/TdkZXHpqVWo

**Comment by Minilarro** [comment]
At the moment when trying to enter the back of the gmc vandura by crouch jumping in, you might get stuck in the window, or the antistuck will push you out. Not sure if this is supposed to happen, but I thought I'd adress this here instead of making a new post.
