### ISSUE TITLE
Roadcrew

### ISSUE THREAD

**Issue by Exnem** [syl0r/Perpheads-Issues#126]
Ability to drag the roadcrew vehicle via hook

Closing the roadcrew gate on a vehicle bugs it out and might blow it up

Towing a car through a fence with the roadcrew vehicle, car on one side and the rc vehicle on the other side will break the vehicle being towed when being pulled. [At least for the Mitsubishi]

**Comment by Bolli123** [comment]
Source bug, sadly can't do anything about it
