### ISSUE TITLE
Roadcrew truck can't go up hills nor bumps when towing a vehicle.

### ISSUE THREAD

**Issue by SwiperFox** [syl0r/Perpheads-Issues#13]
When the RC truck is towing a vehicle along, it's not able to make it up hills nor bumps which makes it impossible for them to do their job.

**Comment by StephenPuffs** [comment]
This may be fixed, I changed some stuff that should pertain to this, however I can not test directly so no guarantee.  For now I will leave this open until I can verify it is fixed.

**Comment by moher4** [comment]
just a tip sometimes it is hard to tow the cars uphill cuz the car you are towing has its handbrakes on
