### ISSUE TITLE
Bugged Escalade

### ISSUE THREAD

**Issue by JoshVK** [syl0r/Perpheads-Issues#132]
At certain spots, the Escalade seems to spring back, making it go backwards and thus getting you off the road most of the times, this tends to happen at this location:
(https://cloud.githubusercontent.com/assets/13069800/8386609/104e7fa4-1c52-11e5-9e51-2d3884511d2e.jpg) this is not just with me, but also with my friends, and just seems to happen with the Escalade

**Comment by samahl9709** [comment]
I have the same problem, at some locations my car gets stuck and i need to call an staff member to fix it.

**Comment by syl0r** [comment]
Not sure exactly what you mean, escalade seems fine to me. I also tested it at that location and it was just fine.
