### ISSUE TITLE
Trying to enter messenger app

### ISSUE THREAD

**Issue by BilboSwaggins12** [syl0r/Perpheads-Issues#134]
[ERROR] gamemodes/perp/gamemode/modules/smartphone/gui/screen.lua:143: attempt to index field 'Appdrawer' (a nil value)
1. unknown - gamemodes/perp/gamemode/modules/smartphone/gui/screen.lua:143

Reward me pls
STEAM_0:0:72444764

**Comment by JDaymon** [comment]
Why would you get rewarded?

**Comment by BilboSwaggins12** [comment]
Because i got u the possibility to fix things :P

**Comment by Minilarro** [comment]
Filing a bug report is not something you get rewarded for, you are simply helping out a community by making it easier for the developers to repair content and while this isn't a big thing, every report helps, and noone will recieve a reward for helping the community out as you wouldn't like people making poor reports which the devs can't use in a way to earn a reward.

**Comment by syl0r** [comment]
Could you please be more specific as to how/when this happens?

**Comment by JDaymon** [comment]
@syl0r this does not happen anymore as far as I know.
