### ISSUE TITLE
Weed plant aesthetic bug

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#136]
http://images.akamai.steamusercontent.com/ugc/442826229430830060/D0BAA96240FBF97CD61D77BC9D3240B7260C101C/

The screenshot shows a marijuana plant being dragged after some time it grown, as you can see you can drag the pot but the plant will stay at the same location

**Comment by JDaymon** [comment]
This is client sided when you have lag.

**Comment by TheMilkMann** [comment]
Try eddit your texture/model options to fix
