### ISSUE TITLE
Unlimited Police Barriers / Cones

### ISSUE THREAD

**Issue by Synatec** [syl0r/Perpheads-Issues#138]
So I was in the PD when I saw a SWAT placing down like 15 barriers. I asked him how he did that and he said "Just place your 5 barriers down, then ask for more and do the same thing over and over again". So if you place them down, and then ask for more but pick the placed barriers up again, you will have more than 5.
This does not work with bandages.
I will upload a picture tommorow, or try it yourself.

**Comment by syl0r** [comment]
fixed
