### ISSUE TITLE
Firefighter job causes you to crash, if youre inside an apartment or in PD (near doors in general)

### ISSUE THREAD

**Issue by Exnem** [syl0r/Perpheads-Issues#141]
If you ever are near doors and are using the fire hose/fire extinguisher, your game will start to bug out. Materials will start to become invisible, doors become transparent and eventualy your game will crash mid-rp

**Comment by JDaymon** [comment]
That's your computers false. Turn Smoke from fire on the F1 menu off

**Comment by Exnem** [comment]
No, i just saw another ff crash from this same problem.

**Comment by JDaymon** [comment]
It's their computers.

**Comment by syl0r** [comment]
not related to doors, probably just too many materials there
