### ISSUE TITLE
Missing Items in Storage.

### ISSUE THREAD

**Issue by MartinGarekt** [syl0r/Perpheads-Issues#142]
Well It happens rarely but it still need to be fixed. Sometimes when you open storage some items you know you had are missing. They come back later on (10 mins) or sometimes they only comeback when you rejoin. I don't know if others have this glitch or not but I would just like to show it's a bug.

**Comment by syl0r** [comment]
Don't know exactly what you mean, does it not display properly because you have too many items in your storage? Items shouldn't just disappear and no one else reported it. If you can somehow find out what exactly is causing it please report back.
