### ISSUE TITLE
Storage Chest

### ISSUE THREAD

**Issue by BelgLmfao** [syl0r/Perpheads-Issues#143]
It's not possible to place the storage chest inside of glassco/parker unless placed right next to the actual storage chest.

**Comment by Minilarro** [comment]
It doesn't have to be placeD right next to the storage chest, but within a certain range of it, this is a function to avoid users having storage chests in their vehicles and have lots of storage slots. This is a problem within most of the larger properties aswell, as you'll have to push it to your desired location.

**Comment by syl0r** [comment]
This is not a bug but intended behaviour (we might change this in the future though)
