### ISSUE TITLE
Shroom farming and Fishing

### ISSUE THREAD

**Issue by TheMilkMann** [syl0r/Perpheads-Issues#147]
Hi i play alot of RP but i think that making money the regular way like planting weed and cocain is really boring and i find it more fun to make money of fishing and making meth and shrooms. Me trying to do all of these unusual ways to make money leads me to find bugs. 

One bug being that if you buy a fishing rod for 2700 dollars you can never put it inside your inv after use, it leads you to losing it and need to pay again to get another one. And yes i have checked the storage at the subs.

Another being that you cant make money of planting shrooms. I bought 10 shrooms and i could not plant them anywhere. I tried every where, the grass place next to the pool out side the city hall dident work, in a grass plot in a suburb house dident work, in the woods at Hicktown dident work. only one place worked to plant them and that was in the water under the bridge close to Hicktown. They grew big but never re-produce.

Please fix soon :D

**Comment by Minilarro** [comment]
The fishing rod bug should be resolved now, a new release was released some days ago.

**Comment by syl0r** [comment]
Fishing rod should be fixed, shrooms work for me(there are just only few places where you can plant them)
