### ISSUE TITLE
Screwed up Glock20 viewmodel FOV

### ISSUE THREAD

**Issue by Creepis** [syl0r/Perpheads-Issues#148]
Title, all other pistols are fine, the Glock20s viewmodel FOV seems to be a bit screwed up, can't see the gun in passive stance and is almost near your face when viewing down the ironsights/having it in attack stance.
![rp_paralake_city_v20529](https://cloud.githubusercontent.com/assets/10688184/8947476/a0993c18-359b-11e5-9b0a-d4c09fc547d8.jpg)
![rp_paralake_city_v20530](https://cloud.githubusercontent.com/assets/10688184/8947477/a3332cae-359b-11e5-8f53-98aed5493db1.jpg)

**Comment by JDaymon** [comment]
The feature where you couldn't see it in passive stance was removed as far as I know, on the screenshots it looks normal to me, might be your desired_fov that is fucked

**Comment by Creepis** [comment]
Talked to Daymon about this problem, its fine for Daymon but not for me for some reason. Changing the fov_desired also does not really help.
70
![2015-07-29_00005](https://cloud.githubusercontent.com/assets/10688184/8997119/21d96d7e-371e-11e5-9d2d-c83440ffabc4.jpg)
90
![2015-07-29_00006](https://cloud.githubusercontent.com/assets/10688184/8997121/26b9dfa4-371e-11e5-98c8-ab0b7c775517.jpg)

**Comment by syl0r** [comment]
Not exactly sure what you mean, FOV seems fine to me.
Passive stance has been a bit adjusted
