### ISSUE TITLE
Seat view

### ISSUE THREAD

**Issue by Minilarro** [syl0r/Perpheads-Issues#149]
When sitting in a passenger seat of a vehicle, or a normal chair, you'll see where your face should've been. It's known to be that this new function to see your own character whilst in a seat wouldn't be fully optimized, and I hope it can be solved. 

Image: http://i.imgur.com/qiwpZf2.jpg

**Comment by Minilarro** [comment]
Once I start my vehicle's engine my arms will now go to the side - http://i.imgur.com/kxpn4f5.jpg

Sitting in a normal chair will now make it seem like you're using /actsurrender from your own perspective (best image i could get, both arms are like this) - http://i.imgur.com/opcYIZf.jpg

**Comment by syl0r** [comment]
probably not a thing anymore?
