### ISSUE TITLE
Panic Location Issue

### ISSUE THREAD

**Issue by affgaming** [syl0r/Perpheads-Issues#15]
http://puu.sh/dOIFB/6c182b853d.png - 'Unknown' just after the highway offramp after business from tunnel

**Comment by StephenPuffs** [comment]
If you happen to find another location in addition to the picture of the unknown text if you could also include a picture of the exact location as it is kinda hard to know where we have already covered.  This system needs improvements of its descriptions and overall functionality, but for now this is fixed.
