### ISSUE TITLE
Strange and Rare weapon glitch

### ISSUE THREAD

**Issue by BuzzLightBeer** [syl0r/Perpheads-Issues#153]
I simply pulled out a colt 1911 for an unpleasent suprise. The gun, dispite looking like it was already in "Attack stance" instead would not fire and and was as if in "Passive stance". I could even raise the ironsights! This annoying bug cost me my life and I would like to learn from the dev team of what this glitchy annoyance.

**Comment by JDaymon** [comment]
This is because you do something that blocks the animation

**Comment by YoloMuffin** [comment]
For me, this happens 2/5 times i want to shoot someone.
