### ISSUE TITLE
Phone: T problem

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#156]
if you are using messanger or if you are sending a 911 text the phone will close when you press "T" so basically you can't write any word containing the letter 't' unless you unbind it.

I would suggest to disable T to close (as well as Z to toggle the cursore) while texting on the phone

**Comment by Creepis** [comment]
This happens if you press the button that is bound to decline incoming phone calls (Standard is 'T'). Just change it from F1>Key Bindings to any other key that is rarely used and you won't have a problem typing with T again or any other letter.

**Comment by Bamarin** [comment]
Yeah I changed it to KP_0 but you can't remap Z and the fact it toggle the cursore off so you can't continue typing untill you press Z again is quite annoying.
I also noticed that KP_0 (as well as the other KP keys) decline calls only if NumLock is tuned on and the same is for the actions in the F1>Key Bindings, but i should probably open another issue for this

**Comment by syl0r** [comment]
It's fixed now
