### ISSUE TITLE
Speed Enforces sometimes can't use roadspikes

### ISSUE THREAD

**Issue by satoshiaaron** [syl0r/Perpheads-Issues#159]
It will sometimes say that the speed enforcer needs to pick up his roadspikes. It only happens sometimes, but it has happened more than once.

**Comment by JDaymon** [comment]
I can vouch for this, it's usually when you've already deployed them once and picked it up

**Comment by Exnem** [comment]
You have to stay crouched the entire time til it's fully deployed. Otherwise it will bug out and tell you that you haven't picked them up. I specifically tested this on the server and this is the only time it bugs out.

**Comment by syl0r** [comment]
Even when I don't crouch for the entire time of deployment/getting it back it still works for me

**Comment by chrisadamson** [comment]
Fredy, had an issue with this today. Was unable to deploy roadspikes despite never putting them down and being respawned. 

and yes i know how to place them

**Comment by Exnem** [comment]
Fredy, keep placing and picking them up multiple times. 80% of the times i want to place roadspikes they disappear. I have to stand completely still for 3 seconds before it even works properly.

I move when i place them, which may be the issue.

**Comment by lelios1** [comment]
I get this randomly. and it is very annoying. There were many times that I quickly equipped my roadspikes and tried to deploy them to stop a fleeing vehicle but it failed saying to me that I have already deployed them somewhere else even if I never used them before.

**Comment by jimmythehamster** [comment]
I'm still getting this bug regularly, I'd really like to see it fixed soon, if you can't reproduce it yourself hit me up and I'll record a video because it happens to me so often.

**Comment by JDaymon** [comment]
Works fine now
