### ISSUE TITLE
Scores Label

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#160]
http://images.akamai.steamusercontent.com/ugc/428193628104478204/19717970170D1881D09BEAE3D58FE4506E2B5171/

As you can see in the screenshot I have a problem displaying the scores label when i hold Tab, indeed I can't see how many Road Crew Workers are in service because the words are half cutted.
I use a 1366x768(native) fullscreen resolution, but that's not the problem: I already tried changing the resolution and I also tried using a 4:3 monitor. So idk if this is just a problem for me or someone else also has it, but i don't know how to fix it and I hope you can.

If you are wondering why there aren't the sergeant displayed, that's not a problem, it's just because this is an old screenshot, but I still have that problem with RC

**Comment by Minilarro** [comment]
This is a resolution problem from what I know, myself I had this problem earlier, but it fixed itself when I bought a new computer using 1920x1080.

**Comment by Bamarin** [comment]
I can't set such an high resolution on my monitors, but here's a screenshot with all the aspect ratio (4:3, 16:9, 16:10), and i have the same problem with all of them
![1](https://cloud.githubusercontent.com/assets/10375578/9491848/8656d5d2-4bf2-11e5-981e-a390f2ba351f.png)
![2](https://cloud.githubusercontent.com/assets/10375578/9491852/8c026c94-4bf2-11e5-94a5-13de3dffaa47.png)
![3](https://cloud.githubusercontent.com/assets/10375578/9491853/8d563382-4bf2-11e5-9976-8e078cd72044.png)

**Comment by Creepis** [comment]
Kind of off-topic but this is the same problem with the radio wheel. The lower the resolution, the closer the circles are and they can also cause visual clipping.

**Comment by JDaymon** [comment]
After looking this through and testing it in sandbox on my school computer it seems obvious to me that the scoreboard is built for 16:9 - 1920 x 1080 because for me this works completely fine and I can see everyone on the scoreboard, and correct me if I'm wrong but I believe that it will be better if you set the resolution to the "Native" one.

**Comment by Bamarin** [comment]
I have 2 monitors the fist one is the main display of my laptop his native resolution is a 16:9 (like yours) but 1366x768 so it doesn't fix the problem since the only working resolution to see the scoreboard properly is (as you @JDaymon and @Minilarro said) 1920:1080.
About the other monitor (which i only use when the main one stops working) it has a 4:3 resolution which is even worse.

The fix to this problem is to set the scoreboard text to a % of the fullscree/window instead of a static length. (I'm talking in HTML terms I'm ignorant in lua programming and i don't even know if such a this is possible or not)

**Comment by syl0r** [comment]
fixed
