### ISSUE TITLE
Since the introduction of Dispatch, I can't see everyone's name when they are transmitting.

### ISSUE THREAD

**Issue by satoshiaaron** [syl0r/Perpheads-Issues#161]

**Comment by satoshiaaron** [comment]
This may not be the problem, some players may be able to use alltalk meaning all players can hear it.

**Comment by JDaymon** [comment]
We noticed this once on the test server, I'm pretty Sure @syl0r or @StephenPuffs will fix this pretty quickly

**Comment by satoshiaaron** [comment]
While playing, it seems they aren't talking through radio. We can sometimes just hear other units and government employees talking across the map.

**Comment by JDaymon** [comment]
That's them holding B down while talking if anything.

**Comment by satoshiaaron** [comment]
I don't think so. Nobody tells them to stop transmitting and they wasn't about to say anything over the radio.

**Comment by satoshiaaron** [comment]
Yep, it is a glitch with dispatch. Dispatch did something to make everyone including mayor heard.

**Comment by satoshiaaron** [comment]
Still happening sometimes. Usually with specific units. I can hear them having casual conversation.

**Comment by syl0r** [comment]
Should be fixed, if not please report back
