### ISSUE TITLE
Radio Stations - Error

### ISSUE THREAD

**Issue by LEWIS088** [syl0r/Perpheads-Issues#166]
When switching to different radio stations the channel sometimes breaks and displays this message.

Error initializing music stream. BASS_ERROR_BUFLOST

**Comment by MrLewis** [comment]
I get the same thing, it isn't just you?

**Comment by syl0r** [comment]
This can happen sometimes when you can't connect to the radio channel. I made it so it retries up to 2 times if it fails.
