### ISSUE TITLE
Calculator DEL

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#167]
when using the calculator every time you press DEL you will delete the last number entered and insert a DEL character
![rp_paralake_city_v20099](https://cloud.githubusercontent.com/assets/10375578/9602958/2d1feca0-50ad-11e5-8ce2-92991fb7fa16.jpg)
![rp_paralake_city_v20101](https://cloud.githubusercontent.com/assets/10375578/9602959/2d2954ca-50ad-11e5-88de-53dc69ba7d8c.jpg)

**Comment by Minilarro** [comment]
Just delet- ..oh, right....

**Comment by syl0r** [comment]
fixed
