### ISSUE TITLE
Stuck in the SHOP menu to buy stuff

### ISSUE THREAD

**Issue by BKBBuLLeT** [syl0r/Perpheads-Issues#168]
When i try to buy something in the store i do it and then i try to exit to go on but then i am stuck in the menu and cant leave so need to loggin again (BTW in game my Name is Lars koolen or AG Reaper)

**Comment by Bamarin** [comment]
you only have to press F2

**Comment by syl0r** [comment]
It does say F2 to exit shop in every shop window. I added an indicator to storage though.
