### ISSUE TITLE
[trivial] MP5A5 or MP5A4 "this is the question"

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#17]
![2014-12-31_01-09-10](https://cloud.githubusercontent.com/assets/10375578/5599728/9d89cb54-92cc-11e4-82b7-e43be9126e77.jpg)
As you can see above to craft the MP5A4 you need MP5A5's components.
Just a bit weird, don't you think?

**Comment by StephenPuffs** [comment]
Not particularly as the only real difference between the two is the stock but I believe it stems from a misunderstanding on someone's part of which we truly have.

**Comment by StephenPuffs** [comment]
Corrected to read MP5A4 as it should be.  Although it has a nonuniform MP5A4 trigger group but we'll ignore that.
