### ISSUE TITLE
Numpad bindings

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#171]
when binding something to a numpad key in F1>Key Bindings that bind will only works when NumLock is turned on intead of working always like when you bind something trought the console (e.g. bind "KP_HOME" "say /panic")

**Comment by JDaymon** [comment]
WHAT

**Comment by syl0r** [comment]
Can't fix unfortunately, if numlock is not enabled it thinks the keys are different keys (numpad 1 becomes end key for example)
