### ISSUE TITLE
Gov Radio stays segregated and becomes useless when dispatchers leave

### ISSUE THREAD

**Issue by jimmythehamster** [syl0r/Perpheads-Issues#172]
After dispatchers separate players into different radio channels, if they leave afterwards the radios remain separate and government cannot communicate with each other anymore.

**Comment by syl0r** [comment]
This shouldn't happen (and hasn't when I was dispatcher), can anyone confirm that this happens?

**Comment by LEWIS088** [comment]
I can confirm partly that whenever a dispatcher seems to resign all of the radio stations become bugged and you can no longer talk to other government at all.
