### ISSUE TITLE
Wood working

### ISSUE THREAD

**Issue by Minilarro** [syl0r/Perpheads-Issues#175]
Yesterday (20.09.2015) I was crafting wooden furniture in order to gain wood working experience in order to level up, I crafted 2 fancy shelves, 1 polished table and 1 bedside draw, I did however not gain any experience as I checked it each time I crafted something new.

**Comment by JDaymon** [comment]
How did you find out you didn't gain any experience then?

**Comment by Minilarro** [comment]
I checked the exp bar between each time I crafted something, as I previously said.

**Comment by JDaymon** [comment]
As far as I know there is no exp bar, could you please link me a puuush of this?

**Comment by Minilarro** [comment]
I am unable at the moment, but what I'm refering to the red progress bar in F1> Skills> wood working.

**Comment by syl0r** [comment]
It should work, are you sure it didn't move at all?

**Comment by Minilarro** [comment]
Yes, I've crafted some smaller wooden fences since I posted this aswell, still nothing.

**Comment by JDaymon** [comment]
Tested this two days or so ago at it did not seem to work for me either.
