### ISSUE TITLE
Unlimited C2 when leaving SWAT

### ISSUE THREAD

**Issue by samahl9709** [syl0r/Perpheads-Issues#177]
When Mighty Mikey Dutch (Mikey Dutch) leave swat he gets unlimited amount of c2 as seen in the youtube clip. When i tried it did not work so it seems like he is the only one.

https://www.youtube.com/watch?v=V_o29WnTnek&feature=youtu.be

**Comment by Minilarro** [comment]
Already been reported.

**Comment by samahl9709** [comment]
And Fredy said it was fixed but its not

**Comment by syl0r** [comment]
It's fixed now, it just wasn't on the server yet
