### ISSUE TITLE
Vehicle repairation 

### ISSUE THREAD

**Issue by Minilarro** [syl0r/Perpheads-Issues#178]
My vehicle, the Ford GT 05, was broken when I left the server, so when I rejoined I went on my way to the car repair shop (where the price is now sneakily highened from 4 800$ to 12 000$) and after having repaired the car, the engine somehow got worse, the car itself looks nice, but the engine takes quite some time to get started (Got to press R quite alot) and this is quite frustrating. There's not any MSG for when you don't have enough money on you for the repair either, it just says it's been repaired, like if you would've had enough.

**Comment by Bolli123** [comment]
The price to repair your vehicle was increased because we felt people were being too negligent with them.

That NPC only repairs the bodywork and tires, to fully repair your engine visit the NPC by the RC impound lot
