### ISSUE TITLE
Randomly reconnecting, somewhat unknown cause

### ISSUE THREAD

**Issue by LaCreepis** [syl0r/Perpheads-Issues#179]
New account because I cannot be bothered at the moment to search for my other account's password.

Basically, this only happened to me twice (was a long time ago, before summer), not sure if other's have encountered the same problem but here it is where I actually got it recorded. Before I lost connection, I opened up the scoreboard which resulted in a small freeze and just me resulting to me droppped back onto the "loading screen", just like you would normally would when you type 'retry' into the console. Below is a video aswell as the disconnect reason I found in the logs which states that I "Disconnected by user" when I didn't do any inputs at all (apart from holding TAB to open the scoreboard).

Video is here https://youtu.be/Sbgdb8XPttA
Log saying that I disconnected is attached under here
![2015-09-29 18 31 14](https://cloud.githubusercontent.com/assets/14893257/10171265/81bc65a8-66d9-11e5-8919-5ee772c95c1c.png)

**Comment by syl0r** [comment]
Could be anything unfortunately, maybe gmod being shit as usual, maybe some owner fucking with you.
If you find any more evidence please reopen.
