### ISSUE TITLE
ATM bug

### ISSUE THREAD

**Issue by KenYamato** [syl0r/Perpheads-Issues#180]
Its not a really big bug but it can get a bit annoying. I go to withdraw or deposit money but when I click on ''Different Amount'' It says Script errors on the top left and freezes which means I need to disconnect and log again. This can cause alot of problems when I am growing drugs or in RP sitiuations which can ruin everybody elses RP. Example: Roadcrew fixes my car and asks for 500$, I go to get the money while he is waiting behind me. I forget about this bug and go onto different amounts, then it freezes (which means neither cant talk nor move and the only way to fix it is by disconnecting) this roadcrew guy will report me and I might get a ban for disconnecting especially when im totally used to using different amount.

**Comment by syl0r** [comment]
fixed
