### ISSUE TITLE
Guns as speed enforcer

### ISSUE THREAD

**Issue by Haydenp10** [syl0r/Perpheads-Issues#184]
Hello!,
So Matt Grand showed me that he could access his vehicle which he was speed  enforcer which he got a M82 out but didn't use it.

This is a bug and should be patched
Thanks,
Hayden

**Comment by syl0r** [comment]
What car did he get the m82 out? He shouldn't be able to get it from his police car.

**Comment by Haydenp10** [comment]
Ford Transit

**Comment by syl0r** [comment]
He shouldn't have a car when he's speed enforcer, when did this happen?

**Comment by LaCreepis** [comment]
Did he get it out from someone else's car?
