### ISSUE TITLE
Roadspike deployment buggy

### ISSUE THREAD

**Issue by jimmythehamster** [syl0r/Perpheads-Issues#186]
Sometimes when attempting to deploy roadspikes quickly the spikes will not deploy and any further attempts to deploy spikes will be met with a message "you have already deployed your roadspikes, go back and retrieve them" and your spikes will not deploy but there are no spikes to go retrieve either.

**Comment by syl0r** [comment]
duplicate

**Comment by lelios1** [comment]
what do you mean duplicate?

**Comment by syl0r** [comment]
there is already an issue about this
