### ISSUE TITLE
Org not creating

### ISSUE THREAD

**Issue by phshaun** [syl0r/Perpheads-Issues#19]
Made a org last night logged on then it wanted me to buy another one. Stomper told me to reconnect. Reconnected told me to buy it still stomper gave me 5k. Bought a new org then pressed f3 still wanted me to buy it. Reconnected still wanted me to buy it.

**Comment by Bamarin** [comment]
as member of his org i can say the org is still working, but he (the leader) in not in there, and since we haven't a leader we can't invite him back. The problem is: how did hi get autokicked?

**Comment by StephenPuffs** [comment]
I don't seem to have this issue.  So if someone could verify what happened to @phshaun, it would be appreciated.

@Bamarin He may have left the organization before loading it using F3, so it didn't recognize him as the leader.  I don't know for certain but it wouldn't simply drop him for no reason, I'd suggest simply remaking it so you have a leader again.

**Comment by phshaun** [comment]
That's the problem. I bought it twice and after it wanted me to talk to the clerk again. Even reconnected still wants me to buy it.

**Comment by JDaymon** [comment]
This happened to me once when i recently left an organisation. I left an org then tried creating a new one, did not work for me either so I waited till the next restart, pretty sure i reported it, not sure. hope this helped a bit
