### ISSUE TITLE
Firearms issue

### ISSUE THREAD

**Issue by Minilarro** [syl0r/Perpheads-Issues#190]
Recently several users including me have noticed there's an issue for firearms during use, when fired there seems to be a 'chance' of it not firing, which Stephen has confirmed is not supposed to be a feature and has never been in developement, meaning it cannot be a leak in the code. What basically happens is that that sometimes when attempting to shoot with a firearm, it will simply not fire, myself I've only used the AK47 recently in automatic-fire mode, and the others who have noticed it has aswell, unsure about the firing mode. It will fire eventually from what I can recall, kind of hard as I've mostly died after having this issue, but I believe when the firearm is in automatic mode, it sometimes won't fire when LMB is held down, but will however once released and pushed again, only a thought.

Although I have no real knowledge of what may cause this issue , I've got some speculations that I thought I'd add.

-Holding down the the desired button to fire (LMB) will make it not fire.
-Firing-mode.

**Comment by StephenPuffs** [comment]
If you hold E while shooting, it can stop it to shooting.

**Comment by Minilarro** [comment]
This seems to happen when I am standing still pressing no other buttons though.

**Comment by Exnem** [comment]
I can confirm, this happens.

**Comment by chrisadamson** [comment]
This has also happened to me with the Beretta M9 pistol, probably just my shite mouse though
