### ISSUE TITLE
Vehicle respawning

### ISSUE THREAD

**Issue by Minilarro** [syl0r/Perpheads-Issues#191]
So I had just gotten by GMC Vandura back from the impound lot, gotten the tires fixed aswell as the engine/etc. by a RC wrench, but when  went to CD and attempted to spawn my Ford GT 05, it said I had to get my car repaired, although it was completely fine, which I checked afterwards several times, all I got was the MSG "You must get your car fixed before you spawn another", this was also the case for when I tried to reclaim my Vandura.

**Comment by StephenPuffs** [comment]
Report back if this happens again, don't fix until we can check it out
