### ISSUE TITLE
Disappearing pumpkins

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#192]
I've been told, while i was growing some pumpkins, that while growing they can disappear. so I was suggested not to plant any pumpkin seed untill 2 or 3 days because it would have been fixed soon, but since there wasn't any report of this problem here, even if it's maybe a known issue i decided to report it myself.
I'm not sure about this bug since it didn't happened to me, but madda told me so.

**Comment by Minilarro** [comment]
This bug should be fixed as of today according to Stephen, they have earlier had a random chance of being either invisible and not grow, or to be normal, pumpkins would sometimes appear after being invisible for a prolonged amount of time aswell. And anyway, why would you not try to plant them, the seeds cost roughly 20$.

**Comment by Bamarin** [comment]
No no, I've ben told so yesterday morning, but i wasn't dure if it was fixed or not
