### ISSUE TITLE
Gun duplication

### ISSUE THREAD

**Issue by skymokid** [syl0r/Perpheads-Issues#197]
Hi, once I got a m16 from Xhantium, after i decided i wanted to go on duty as a police officer i put the m16 in my inventory. when i got out off duty i picked it up out of my storagebox again, that's when I saw that there were 2 m16's in my storage box.
now I am keeping one in my storage box and one in my trunk.

greatings, THE SPOOK (Gary Butcher)

**Comment by syl0r** [comment]
This shouldn't be possible, please try and make sure that you didn't have a second m16 in your storage box. Also try and post a reproducable scenario (or a description of exactly what you di)
