### ISSUE TITLE
Glass Co. main doors not closing.

### ISSUE THREAD

**Issue by Minilarro** [syl0r/Perpheads-Issues#20]
When you are to open the glass co. doors you have to unlock both doors with you keys, then when you open it, you'll have to unlock the doors again to close them. This happens around 75% of the time, and sometimes even if you re-unlock them you cannot close them.

**Comment by Minilarro** [comment]
Okay, thanks for the info! Go ahead and close this i guess

**Comment by JDaymon** [comment]
What I do is that I try to close it with the left one, it's the one working for me
