### ISSUE TITLE
I can not see gardening pots!

### ISSUE THREAD

**Issue by LoganFinch** [syl0r/Perpheads-Issues#200]
I can not see gardening pot, it is really annoying because I can not grow stuff in them because they are totally invisible I can still walk on top of them but I can not see the pots please can some one help I have all dlc for PERP I have all content that I need please guys!

**Comment by Minilarro** [comment]
Has this happened several times? This has happened once or twice to me, but not enough for it to be an issue.

If it does, try reinstalling the content, and download both from the workshop and the forum.

**Comment by LoganFinch** [comment]
It has beeen going on the past 20 times I have joined I will re install it thx

**Comment by LoganFinch** [comment]
It did not work :(

**Comment by StephenPuffs** [comment]
Do you have CS:S content?

**Comment by LoganFinch** [comment]
Yes I will reinstall it

**Comment by LoganFinch** [comment]
It worked thank you all so much!
