### ISSUE TITLE
perp_dropmoney

### ISSUE THREAD

**Issue by smash123** [syl0r/Perpheads-Issues#205]
When you are handcuffed, you can drop money via perp_dropmoney in console.

**Comment by LaCreepis** [comment]
I shouldn't have *leaked* the console command on how to drop money in the first place, urgh. Useful for splitting up loads a money though.

Anyways, this is possible and very minor.

**Comment by syl0r** [comment]
"leaked"

**Comment by syl0r** [comment]
fixed
