### ISSUE TITLE
Fireams while cuffed

### ISSUE THREAD

**Issue by Madda2000** [syl0r/Perpheads-Issues#206]
We found out that if you handcuff a fellow officer while he is chosing a new gun in the armory menu, the gun will go to his hands when handcuffed. His old firearm will also stay in his inventory. The old guns that stacked up can not be used. Ammo wont stock either. 

Some screenshots: SWAT holding a firearm while cuffed: http://images.akamai.steamusercontent.com/ugc/400054473529363278/213F74D8986E59FE5D0CE0C5A1CE444EF2A155F0/

Me having loads of pistols on me: http://images.akamai.steamusercontent.com/ugc/400054473529374630/2E0A0E8C91C65F405490FC99A0BA05C634D384D7/

As far as I know this is not a huge problem. You can not use the duplicated firearms and you can not use the glitch to stack up mags.

**Comment by Exnem** [comment]
Also, a side note. The firearms are fully usable when cuffed. :P

**Comment by syl0r** [comment]
fixed
