### ISSUE TITLE
Car exiting

### ISSUE THREAD

**Issue by BelgLmfao** [syl0r/Perpheads-Issues#207]
I just got my new Mercedes SLS and sometimes when I get stuck whilst exiting it, i become stuck for like 2 seconds and when it automatically unstucks me, it makes me bleed and break my legs and 'you're gonna die son' pls fix

**Comment by chrisadamson** [comment]
Known bug and common to a lot of vehicles (especially dodge charger), I believe @StephenPuffs is already aware of this?
