### ISSUE TITLE
Buying drugs from any NPC and ATM

### ISSUE THREAD

**Issue by Exnem** [syl0r/Perpheads-Issues#209]
http://puu.sh/lCL2V/768d56decf.jpg
and
http://puu.sh/lCL4I/4f12b021ad.jpg

I have recently been able to buy drug seeds from any ATM and NPC.

However, money is withdrawn but i never receive the items.

**Comment by syl0r** [comment]
Can you maybe describe what you did to get it there? Like talking to the drug dealer before hand and getting script errors?

**Comment by Exnem** [comment]
This has happened before, I haven't even spoken to the drug dealer. But after i disconnected that day, it disappeared. Never seen it ever again.

However i believe it's a bug with the drug dealer.
If i get this again i will update with some information.
