### ISSUE TITLE
Meth keeps coming back as wet in inventory

### ISSUE THREAD

**Issue by Cudder** [syl0r/Perpheads-Issues#21]
I drop meth onto my stove and leave it on for at least 15 minutes, no smoke comes and when I wait longer than 15 minutes it still comes back to me as wet

**Comment by BenStandish** [comment]
If the meth moves even slightly, such as nudges, prop collision or hit by a person, the timer resets, so make sure your meth isn't too close to each-other.

**Comment by StephenPuffs** [comment]
Meth should be fixed now, if it continues to be a problem, review what BenStandish said.  Beyond that please post this report again and give as much detail as you can about how it was cooked.
