### ISSUE TITLE
Administrator Report Menu.

### ISSUE THREAD

**Issue by LEWIS088** [syl0r/Perpheads-Issues#210]
Quite often when on the server the report menu will bug out, What happens is that when you respond to a report it does not inform you which reports have been responded too, sometimes these reports can even fully bug out informing me that "This report no longer exists" even though no one has responded to that report.

http://images.akamai.steamusercontent.com/ugc/403433347028721393/1771981E12A222701D8B0EAB0AF6C5469CCC3A74/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside|1024:768&composite-to=*,*|1024:768&background-color=black

**Comment by JDaymon** [comment]
This is because your demo has either stopped or you joined while someone closed them, it can also be thanks to EV_Menu not catching up with your client.
