### ISSUE TITLE
Cocaine bug

### ISSUE THREAD

**Issue by D3luX** [syl0r/Perpheads-Issues#211]
Well, i dont know how this happened but my cocaine turned into one "Big Cocaine Plant".. And normal cocaine you get from plant is about 1gram i think or something.. This one have a weight on 5kg..

http://images.akamai.steamusercontent.com/ugc/576822289062035093/643317E48809CE26303CF51C5928C63174C6D99F/

**Comment by Bolli123** [comment]
That is a separate item that someone gave to you or you got in a x-max present, contact an administrator to have it removed
