### ISSUE TITLE
Dispatcher Menu

### ISSUE THREAD

**Issue by chrisadamson** [syl0r/Perpheads-Issues#212]
All units must be unassigned from a call, you cannot simply unassign just the selected unit. this means at large incidents you cant break away one unit to assign to another call because it takes ten fucking years to reassign everyone

**Comment by Minilarro** [comment]
I believe you should make a suggestion to change this within the menu as it's not a bug from what I can understand, but rather something that can be improved.

**Comment by chrisadamson** [comment]
No, this is a bug :)

**Comment by syl0r** [comment]
it's not a bug
