### ISSUE TITLE
Animation Bug

### ISSUE THREAD

**Issue by YaseenF** [syl0r/Perpheads-Issues#213]
i saw lewis robertson (LEWIS 088) holding a barreta m9 while he accually dont , i told him to holster it but he said i dont have a gun , i think this bug will effect on the roleplay in this server if you didnt fix it as soon as possible ... 
http://i.imgur.com/rFWruvO.jpg?1

**Comment by Exnem** [comment]
I've also had animation bugs, items popping out of nowhere. And even a sweatervest running around with an M82 in his hands.

Also, animations like /act point for male characters don't work. It only shows someone "swimming" and pointing in a direction with an invisible weapon.

**Comment by StephenPuffs** [comment]
Pretty sure this is caused by if you download the content from the website instead of using workshop.
