### ISSUE TITLE
Binoculars

### ISSUE THREAD

**Issue by Minilarro** [syl0r/Perpheads-Issues#215]
When dropping the binoculars from your inventory, they will be dropped rather high up a bit to the right of you. Aswell as it having a texture issue while in your inventory and while using it.

In INV:
http://images.akamai.steamusercontent.com/ugc/401182814322318602/1740C5503F36FF2B0366EF1A9198F25D141432F4/

Equipped & in use:
http://images.akamai.steamusercontent.com/ugc/365154562154958636/0417EC9CE2D93BE8DE00C1F5B8EBBFD1D9D023A6/

**Comment by StephenPuffs** [comment]
It needs to be recompiled much the same as the bat.  #231 so at next content update hopefully we can have it fixed.
