### ISSUE TITLE
Roadcrew Calls

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#217]
When reciving a call at 565, on your phone will be displayed a missing texture square instead of the tipical "#565-emergency call"

**Comment by Wunderwaffle11** [comment]
This happens for me on every call

**Comment by PHSneaky** [comment]
I fixed this by using the website content,  which you shouldnt do now anymore,  think a content update is needed

**Comment by syl0r** [comment]
I don't think this is a thing anymore
