### ISSUE TITLE
Unable to access an ATM at Subs.

### ISSUE THREAD

**Issue by LEWIS088** [syl0r/Perpheads-Issues#218]
I received a report about a bug with a user unable to access the ATM machine at the subs fredy's, it seems this was a server side problem.

http://steamcommunity.com/sharedfiles/filedetails/?id=590346405

**Comment by JamesFozzie** [comment]
Can confirm I was the one who reported it. It does not have any access although the ATMs remain fine.

**Comment by JamesFozzie** [comment]
ATM is working fine now
