### ISSUE TITLE
Door texture switch

### ISSUE THREAD

**Issue by sjappy10** [syl0r/Perpheads-Issues#219]
Since Paralake V3, I've been experienceing a new bug. Normal doors, like the doors from the PD, Regals and the "Safety first" shop are randomly switching texture's. This can be solved by restarting Gmod and rejoining Perp, but it still an annoying bug. Screenshots included:

![2016-01-04_00011](https://cloud.githubusercontent.com/assets/16547800/12101683/4c1dadb8-b336-11e5-93ca-f2cb9f27fc9b.jpg)

![2016-01-04_00001](https://cloud.githubusercontent.com/assets/16547800/12101688/55e87486-b336-11e5-8441-97269b529179.jpg)

1 week ago, the Regal doors where all iron doors.

I hope this bug can be solved.
Greetings,
Sem

**Comment by LaCreepis** [comment]
Make sure that you don't have Black Mesa mounted or it's textures installed. This has happened to some people before because they had that game mounted or make sure you don't have any other games mounted except for CSS, HL2 and it's series.

**Comment by sjappy10** [comment]
Black Mesa was not mounted. Only CSS Texture's, from http://kajar9.wix.com/cscheater2#!downloads/chgd was their.

**Comment by syl0r** [comment]
Make sure you have workshop download enabled in your gmod multiplayer options.
If you do then you should try and disable all addons you have subscribed to, I think rockford is the one that actually causes these issues.
