### ISSUE TITLE
Bank Heist Crashes Server

### ISSUE THREAD

**Issue by TheVingard** [syl0r/Perpheads-Issues#220]
Recently, the server has been crashing allot, each time it crashed a bank heist was happening. Several Moderators are aware of this issue, and so sare you probably but I put it here just in-case.

**Comment by LaCreepis** [comment]
It happened Saturday and on a Sunday, I did check the console logs before the server crash and there was a bank robbery that just started before the crash. So I did come up with the conclusion that it does crash the server, at the moment we just lock the foremans office in the manager room so people can't rob the bank, and please, don't intenionally get it open by bombing the door.
