### ISSUE TITLE
DNA scan

### ISSUE THREAD

**Issue by BilboSwaggins12** [syl0r/Perpheads-Issues#222]
I was lt dna scanning gino that got run over and this error popped up

[ERROR] gamemodes/perp/gamemode/modules/jobs/medic/cl_dnasampler.lua:91: attempt to call method 'IsGovernmentOfficial' (a nil value)
  1. unknown - gamemodes/perp/gamemode/modules/jobs/medic/cl_dnasampler.lua:91

**Comment by Wunderwaffle11** [comment]
That can't be fixed, that's just the game confusing itself over whether the person is an Officer

**Comment by StephenPuffs** [comment]
Perhaps fixed, still need to improve this whole thing, but hopefully won't always give errors, remake if it does.
