### ISSUE TITLE
Gmod crashes when connecting to perp

### ISSUE THREAD

**Issue by ZzJarnozZ** [syl0r/Perpheads-Issues#224]
Hi can anyone plzz help me? I have Gmod an dplayed it 600 hours  then i upgraded my pc to windows 10 64 bit and i could still play it then i got a new grapics card a MSI GeForce GTX 750 ti but now when i try to joing perpheads it just crashes i already reinstalled it like 3 times and i got al the packs and map and when im lucky and join the server i can't see cars or people﻿

**Comment by Bolli123** [comment]
Try loading the map in sandbox before joining. 
This isn't really a server issue
