### ISSUE TITLE
ammunition

### ISSUE THREAD

**Issue by Minilarro** [syl0r/Perpheads-Issues#226]
I believe this is a bug related to the recent update regarding the shooting range and marksmanship/etc. I had taken out four pistol ammo boxes as well as four rifle ammo boxes and one buckshot box. After having used a pistol and a rifle at the shooting range, I was unable to deposit the boxes, and when I withdrew one of each kind, the other four in my inventory disappeared.

**Comment by Bolli123** [comment]
Yes

**Comment by Minilarro** [comment]
Yes.

**Comment by Bolli123** [comment]
Should just be a display error, after the box is used up it doesn't actually get removed from the inventory

**Comment by Minilarro** [comment]
It didn't go to storage though, will it possibly be there when reconnecting?
