### ISSUE TITLE
Speed limiter

### ISSUE THREAD

**Issue by lelios1** [syl0r/Perpheads-Issues#229]
When you have a speed limit set for your vehicle, you can't change the numbers from mouse wheel up and down meaning that you have to reset the speed limit which is really annoying.

**Comment by JDaymon** [comment]
I don't have this problem myself, I'm really not sure what you're on about

**Comment by lelios1** [comment]
Really? Many people including me have it...

**Comment by LEWIS088** [comment]
I also have this issue, once you set your cruise control on you cannot change the speed via using the scroll wheel.

**Comment by StephenPuffs** [comment]
Fixed for next update
