### ISSUE TITLE
Getting stuck when exiting car

### ISSUE THREAD

**Issue by ChrisAlAndrews** [syl0r/Perpheads-Issues#23]
Sometimes you get stuck in the door when exiting and it's annoying when you're urgently getting out

**Comment by Minilarro** [comment]
I believe you should add what car it is. However i believe this is only when the terrain beside the car where you exit is blocked off so a part of you gets stuck in, lets say, the pavement. Then i think it's just cause It's too close to it. Avoiding parking the car with th exit too close to something that you can spawn into should avoid this happening i believe.

**Comment by StephenPuffs** [comment]
As I have said repeatedly... People should make a list of all cars this happens with, as I have no time to test every car's exit positions.  So without stating what car at all I have no way to solve this.

**Comment by JDaymon** [comment]
The BMW M5 (I think it's the M5) got some problems when exiting the vehicle, if its on a bit of pavement it will get you stuck.

**Comment by StephenPuffs** [comment]
Although created after this one, here is the reserved issue tracker for wrong vehicle exit points. https://github.com/syl0r/Perpheads-Issues/issues/51  All the ones listed here have been corrected (pending update).
