### ISSUE TITLE
Baseball bat glitch

### ISSUE THREAD

**Issue by Wunderwaffle11** [syl0r/Perpheads-Issues#233]
This glitch is pretty simple, basically when you try to drop a baseball bat, it will appear inside you and you will be stuck for a moment, then the glitch sorts itself and the bat falls away.

Sometimes when this happens my bat pings off into oblivion, and when stuck and jumping around to get unstuck I've actually died twice from it. I did not bother making an RR considering that people would not think of it as a valid reason despite my losing an M16 and a Deagle respectively.

**Comment by StephenPuffs** [comment]
Duplicate

**Comment by Wunderwaffle11** [comment]
?
