### ISSUE TITLE
Everything, including world objects go invisible during/after medium/larger firefights

### ISSUE THREAD

**Issue by JohnDick1234** [syl0r/Perpheads-Issues#234]
Not sure if you're aware of this, you probably are but I can't find it here so I figured it's worth putting.

Essentially, during/after larger firefights everything will go invisible for the large majority of players in the area, it makes fat loads of people cry in OOC as they are just driving past, to the garage or highway and have to rejoin to fix the issue.

Also is a regular occurrence during fatty raids.

**Comment by Wunderwaffle11** [comment]
Can confirm

**Comment by syl0r** [comment]
Can anyone confirm whether or not police were involved in these gunfights?

**Comment by BenStandish** [comment]
Yes, it is something to do with police bodies stacking (Too many)

**Comment by LaCreepis** [comment]
Definetely something to do with police corpses which led me to remove some of them during firefights which helped prevent this issue as I had said in some other issue earlier.

**Comment by StephenPuffs** [comment]
Perhaps fixed after update, please remake issue report if this persists.
