### ISSUE TITLE
Keeping your car even as a gov offical

### ISSUE THREAD

**Issue by moher4** [syl0r/Perpheads-Issues#235]
this is quit old but here it is again, basically you can bug your car in a way so that it does not despawn when you go on any job what ever it is this also works the other way around where you can keep a car from a job like the RC truck or cop car or swat van works on every single one of them so its a very simple thing all you need is a friend to be RC make him hook your car in the RC truck and also put a booth on the car being hooked keep the car hooked until you get on the job then remove the hook and all and there you have it. this also works on duping cars where you can get any car yours or from a job and hook spawn a new one as the other is hooked and both will stay. this is easy to reproduce if you need my help just ask I would be happy to help :)

**Comment by StephenPuffs** [comment]
Was fixed at last patch
