### ISSUE TITLE
LUA error that times out my game.

### ISSUE THREAD

**Issue by SteyLex** [syl0r/Perpheads-Issues#239]
Most of the time when someone types something in ooc. The server can't get his steam name so his steam id I get this error

`[OOC] Console: What the f happend

[ERROR] gamemodes/perp/gamemode/modules/chatsystem/cl_chat.lua:421: attempt to call method 'SteamID' (a nil value)
  1. func - gamemodes/perp/gamemode/modules/chatsystem/cl_chat.lua:421
   2. unknown - lua/includes/extensions/net.lua:32`

When that happends its timing out my game and mostly crashing my game connection and timing me out.

Even with shootouts I die because of that.

**Comment by LaCreepis** [comment]
I only get this script error when my demo stops and automatically stards recording again or when I just have joined the server, not sure how you get this script error out of the blue, never had it appear randomly.

**Comment by syl0r** [comment]
This script error doesn't cause you to lose connection, It only occurs because you are timing out, it's the result not the cause.
