### ISSUE TITLE
Weapon fire modes not "saving"

### ISSUE THREAD

**Issue by LaCreepis** [syl0r/Perpheads-Issues#240]
This has been happening quite alot recently where the firemodes of your weapon just get switched back to semi-auto from full auto or burst fire for seemingly no reason. Or this might be happening when you get revived as a LEO with a weapon with firemodes, get out of noclip or, teleport to someone or respawn/revive yourself.

**Comment by syl0r** [comment]
It was never saved, but it'll probably saved when the new update comes out.
