### ISSUE TITLE
Interrogation room 1 chair

### ISSUE THREAD

**Issue by Minilarro** [syl0r/Perpheads-Issues#243]
One of the chairs in the interrogation room 1 of the PD has a misplaced seat.

http://images.akamai.steamusercontent.com/ugc/296483000633776263/8627B27ABF435034AF0A5F960D8F4EB639E386C6/

**Comment by LaCreepis** [comment]
gamebreaking, going to uninstall

**Comment by Minilarro** [comment]
If we all do that, they will for sure have to fix it.

**Comment by StephenPuffs** [comment]
Pls no uninstall.  Fixed for next update.
