### ISSUE TITLE
Organisation Menu

### ISSUE THREAD

**Issue by smash123** [syl0r/Perpheads-Issues#244]
Shit's broken mayne.

[ERROR] lua/vgui/dcheckbox.lua:123: attempt to perform arithmetic on local 'h' (a nil value)
  1. PerformLayout - lua/vgui/dcheckbox.lua:123
   2. unknown - gamemodes/perp/gamemode/modules/guicore/layouts/vertical_layout.lua:95

[ERROR] lua/vgui/dcheckbox.lua:123: attempt to perform arithmetic on local 'h' (a nil value)
  1. PerformLayout - lua/vgui/dcheckbox.lua:123
   2. unknown - gamemodes/perp/gamemode/modules/guicore/layouts/vertical_layout.lua:95

https://gyazo.com/53afd56055b090561449e26d393f1b23

**Comment by StephenPuffs** [comment]
Caused by broken GMod update, their reversion should take care of this issue.
