### ISSUE TITLE
Audi s5

### ISSUE THREAD

**Issue by SteyLex** [syl0r/Perpheads-Issues#245]
I have the Audi s5 now for a while and I noticed when I exit the car I am stuck to the car for like 5 seconds. Sometimes when you Carry a gun on your back your are stuck for 30-60 seconds. Its kinda annoying because in shootouts I sometimes die because I can't move.

**Comment by LaCreepis** [comment]
30-60? wtf no

Not sure what happened to the list of vehicles that need their exit position changed but while I'm here the EB110 sometimes got the same issue.

**Comment by SteyLex** [comment]
Yes I am true. Next time I am stuck like 30 seconds I send you a video.

**Comment by StephenPuffs** [comment]
I don't see how the gun would make any difference honestly, however I have adjusted their positions for tomorrow.  The thread apparently was moved to resolved, but oh well, just make individual issues as they're more likely to be seen.
