### ISSUE TITLE
Fists are unresponsive.

### ISSUE THREAD

**Issue by ThomasDeSimone** [syl0r/Perpheads-Issues#247]
Punches hardly land when you're in a fist fight.

**Comment by PHSneaky** [comment]
Havent experienced this myself yet, maybe the animation doesnt fit  the hitbox?

**Comment by ThomasDeSimone** [comment]
It's not the animation, I don't know if I'm just lagging but whenever I hit someone and the animation lands; if they are moving by an inch it doesn't hit them.

**Comment by StephenPuffs** [comment]
Not really a bug just lag, but in time we'll make a better detection as for now this will be closed.
