### ISSUE TITLE
Medic NPC is bugged (leg fixes)

### ISSUE THREAD

**Issue by BenStandish** [syl0r/Perpheads-Issues#25]
When paying the NPC medic to fix your legs, it does not work.

**Comment by StephenPuffs** [comment]
It did for me the other day, can you provide any more relevant information?

**Comment by BenStandish** [comment]
Sorry, it's just doesn't work sometimes, I've had a few people either make a /report about it or tell me it hasn't worked. The fact you can't reproduce it may be due to lag, who knows; I'll try and test it a few times.

**Comment by BenStandish** [comment]
This recently started working, I have no idea why. This was definitely a problem 3 weeks ago.
