### ISSUE TITLE
Jail bug

### ISSUE THREAD

**Issue by EmreRedbend** [syl0r/Perpheads-Issues#253]
The cops put me for 4 years in the jail . but when i was free I spawned in the womon toilet. When i report it by the mod he said you are lying because you are 1 hour in the server it inst impossible
bla bla bla. so they put me 4 years agian. but when the 4 years where over i spawn agian  in the womon toilet. I have it on a demo if you need it say it.

sorry for my bad English,
Emre ( Emre Redbend )

**Comment by syl0r** [comment]
You probably got stuck in someone else and got teleported there by the anti-stuck
