### ISSUE TITLE
Warrant problem

### ISSUE THREAD

**Issue by lelios1** [syl0r/Perpheads-Issues#255]
So I tried to rob the bank, dying shorty after just to realise that I couldn't become a LEO when I respawned. It would say to me that I am warranted and even though I was complying (take me to jail for 5 minutes) nothing happened. The NPC dialog and the text would simply disappear when I had finished talking with the NPC without going to jail. It was later confirmed that I didn't have any active warrants on me. This was fixed after me going to jail.

**Comment by jimmythehamster** [comment]
When the police computer updated the whole warrant system I don't believe bank warrants were updated. This means that when someone robs the bank they get "warranted" on the old system which stops them from becoming an LEO and alerts the police to their presence at the PD, but the warrant does not appear on the police computer. 

When warrants were updated dying does not remove them unless you die by the hand of an LEO.

**Comment by lelios1** [comment]
I died from a LEO yes. Now I am pretty confident that the issue has been fixed..

**Comment by lelios1** [comment]
Pretty sure that I figured out what is happening. When you rob the bank you get automatically warranted. This warrant though is not being shown in the police compter through F3. The warrant still blocks you from joining the police job though and will get removed when you go to jail (unsure if it gets removed when killed by a LEO)

**Comment by jimmythehamster** [comment]
Thanks Captain Obvious did you need 17 days to read my comment there -.-

**Comment by lelios1** [comment]
ayyy lmao, didnt understand it at the time you posted it.

**Comment by syl0r** [comment]
Bank robberies don't automatically warrant anymore
