### ISSUE TITLE
SWAT police computer

### ISSUE THREAD

**Issue by jimmythehamster** [syl0r/Perpheads-Issues#257]
Unsure if this was an oversight, a bug or intentional, but SWAT can't access the police computers in PD. They are just like LEO's in that they can make arrests and take people to jail, and they should be able to access the police computer to assist them in their duties.

**Comment by lelios1** [comment]
I don't see the point on SWAT being able to use the computer. They should be called in emergency situations where lives are in danger, not act like LEOs for example giving tickets and/or arresting people. What would they even do if they had access to the computer. See who got a ticket, or who got jailed? It is pointless.

**Comment by syl0r** [comment]
This should be a suggestion, not a bug.
