### ISSUE TITLE
The ORG menu breaks when you have higher resolution than 1920x1080

### ISSUE THREAD

**Issue by CLeyer** [syl0r/Perpheads-Issues#258]
This is what the org menu looks at with 2560x1440p http://images.akamai.steamusercontent.com/ugc/278472405079084898/FD2342ADAA0077D5FC892BC6047FFFFA41D5B8A2/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside|2048:1152&composite-to=*,*|2048:1152&background-color=black

http://images.akamai.steamusercontent.com/ugc/278472405079084679/A679FB33AFCB3914823D357D97C94564DF0DE2F7/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside|2048:1152&composite-to=*,*|2048:1152&background-color=black

It looks fine If I go lower than my native resolution to 1920x1080.

**Comment by JDaymon** [comment]
same, Pls fix Will install if not fixed

**Comment by syl0r** [comment]
fixed
