### ISSUE TITLE
Most YouTube videos are unable to be played

### ISSUE THREAD

**Issue by LaCreepis** [syl0r/Perpheads-Issues#259]
Most YouTube videos cannot be played in-game due to this
![ss 2016-05-05 at 09 27 49](https://cloud.githubusercontent.com/assets/14893257/15054598/8c8b13fe-1308-11e6-9b70-f833f7cc836d.png)
The video refused to play for me and another person but somehow worked for someone else. I am sure I'm not the only one with this but if I find a broken video I'll post the ID here. Most likely a problem with Awesomium if that is even relevant with YouTube videos being played in Garry's Mod.

**Comment by CLeyer** [comment]
Try this: http://cinema.pixeltailgames.com/flash.html

**Comment by LaCreepis** [comment]
@Cleyer I just realized this, the TVs might've been broken for me since I visited the Cinema server we had last weekend, I'll try that out so it is most likely just a bug on my part. Thanks!

**Comment by LaCreepis** [comment]
Yup, was just a bug on my part, I installed Adobe with the link Leyer provided, everyones TVs might be bugged because of the cinema server we visited so just a heads up. Close this please, ty.
