### ISSUE TITLE
G3/M14 mags loading wrongly with 2 full sniper boxes.

### ISSUE THREAD

**Issue by MCGSCEFFAAWHETJH55555** [syl0r/Perpheads-Issues#261]
So I managed to buy 2 full sniper boxes and went to load it inside one G3/M14 magazine. After loading, I realized it only loaded 10 rounds instead of 20 yet both boxes disappeared.

https://mega.nz/#!oY0RgbgK!wiqvydBRFiKjoCO8ZRwJ4LLSua2MiAH3xjGsqrM5j5g
Tick: 29000

**Comment by MCGSCEFFAAWHETJH55555** [comment]
It happened again today. Except I tried loading a G3/M14 magazine that already had 10 rounds with another 10 rounds, but the amount was still 10 and the amount disappeared. Are the magazines maxed out at 10 now?

**Comment by syl0r** [comment]
It does it correctly for me:
https://gyazo.com/60ed75822be1308e678cda1a94540c5f

**Comment by MCGSCEFFAAWHETJH55555** [comment]
Could you try it again with 2 sniper boxes and one empty magazine?
