### ISSUE TITLE
Forum warnings - 2.5 Rating system no longer removes actual ability for them to rate posts.

### ISSUE THREAD

**Issue by LEWIS088** [syl0r/Perpheads-Issues#262]
I've removed the other warnings from view, if you look at his warnings he's been warned twice for the rating system yet is still able to rate posts however he feels.

https://i.gyazo.com/3c6d62418bae3bd1aa6ee59bf8858b9c.png

In the past once you warned someone for this is automatically removed permissions for them to rate.

**Comment by JDaymon** [comment]
Not correct, it was always manually removed

**Comment by LEWIS088** [comment]
How come when I warned Teemo for 2.5 his permissions were instantly revoked.

**Comment by LaCreepis** [comment]
This should still work, Rogue warned someone for 2.5 recently and the one who had been issued the warning had his ratings revoked.
