### ISSUE TITLE
Trunk bug

### ISSUE THREAD

**Issue by D3luX** [syl0r/Perpheads-Issues#264]
My trunk in my Porsche Carrera GT have always been working 100% fine, but recently a bug occured.
My trunk have 3 slots, but i can only use 2. Everything i have trunked two items and trying to trunk the third, it says the trunk is full. And its kinda annoying i only have 2 slots for use when i should have 3.

![4000_screenshots_20160516002939_1](https://cloud.githubusercontent.com/assets/16181057/15277218/c93496b6-1afd-11e6-957b-1212d1ef5001.jpg)

**Comment by LaCreepis** [comment]
This could be only a client side bug, I checked inside D3luX's trunk and could easily access all 3 trunk slots while he could only use 2 as a non-existant item took up the spot for the last one.

**Comment by D3luX** [comment]
I have rejoined, closed my game etc.. But its still an issue.

**Comment by D3luX** [comment]
Also just tried to delete my game and reinstall it. Still doesnt work. RIP.

**Comment by syl0r** [comment]
Can everyone else use all slots except for you?

**Comment by D3luX** [comment]
Got others to test it for me. They also have same issue as i do. 5 other peoples, they can also only use 2. The one to the left and right. The middle is in use it says, even if its empty.

**Comment by D3luX** [comment]
Tried getting multiple people using the trunk, and they have same bug as i do.

**Comment by D3luX** [comment]
Could you please try clearing my trunk? Maybe that would fix it, as all others having same issue when using my trunk.

**Comment by syl0r** [comment]
might be fixed
