### ISSUE TITLE
Dispatcher bug

### ISSUE THREAD

**Issue by tykittyy** [syl0r/Perpheads-Issues#265]
Sometimes when you close the CCTV camera you get stuck in an invisible menu. You can see the cursor but you cant type/talk or get out your chair.

Not even respawning or tp helps, I had to relog.

And another thing, I can't talk in game or answer phone as a dispatcher.
And yest I tried to re-bind my talk key and set it to default, didnt help.

**Comment by syl0r** [comment]
Can you please be more specific as to when you get stuck in the menu? What did you do differently to when you don't get stuck?

Both phone and talking work for me, does anyone else have this issue?
