### ISSUE TITLE
Possibly game breaking bug.

### ISSUE THREAD

**Issue by Exnem** [syl0r/Perpheads-Issues#266]
A chair is all one needs, and that can really be game breaking if someone decides to abuse it.
Use it, and if you're caught by me I will slice your balls off.

https://www.youtube.com/watch?v=5ZKjdXiHc1k&feature=youtu.be

Example 2: https://www.youtube.com/watch?v=GZJvNnbMDr8&feature=youtu.be

ALT + E without anything in your hands, this leads to you sitting in the chair and picking it up at the same time.

It can be used on any two or more stories houses/apartments.

**Comment by LEWIS088** [comment]
Not really a bug from what I'm aware, this has been in for as long as I can remember.

I've never seen it abused.

**Comment by syl0r** [comment]
This has always been the case and is not worth fixing since this hasn't been an issue often.
If you find someone who is abusing it please post an action request and they will be banned.
