### ISSUE TITLE
Seargent+ shotgun bug.

### ISSUE THREAD

**Issue by EstebanWinsmore** [syl0r/Perpheads-Issues#267]
When you die with a shotgun equipped, it does not disappear from your inventory. 

Also, when you spawn a new car, your shotgun and the ammo for it should be wiped from your inventory, since the car is just going to spawn with more ammo and another shotgun. This allows you to stockpile ammo for the shotgun, giving you an unfair advantage against the criminals.

**Comment by jimmythehamster** [comment]
You're given 5 full shotgun ammo boxes. Stockpiling ammo will give you no advantage as you initially have 100 shells at your disposal and you'll never need that many.

**Comment by syl0r** [comment]
As shotguns are only an option for whitelisted officers I don't see much reason to spend time on fixing this issue since the abusability is negligible.
