### ISSUE TITLE
Chief of Police Tag

### ISSUE THREAD

**Issue by ttjr123** [syl0r/Perpheads-Issues#268]
Chief of Police tag,
replace it with my fixed version that has a transparent background: http://i.imgur.com/4gO6kEz.png
Currently looks messed up on dark themes.

**Comment by ttjr123** [comment]
By the way I am Tyla

**Comment by LaCreepis** [comment]
@ttjr123 who else would it fucking be

**Comment by syl0r** [comment]
done
