### ISSUE TITLE
stuff disapearing from storage.

### ISSUE THREAD

**Issue by moher4** [syl0r/Perpheads-Issues#27]
ok so what happens is every now and then something has to disappear from my storage i have lost things like ammo and TVs up to my g36 now i noticed that the main things at always disappear from my storage are TVs, spot lights almost all types of ammo, chairs, wooden fences and the concrete barriers and stuff that you use alot like every day or so i also noticed that stuff will disappear when you dc or my game crashes especially if i have just recently put the item in any type of storage  except the car trunk i have also noticed stuff disappearing from storage if you have recently put it in my storage and then joined a job but this happened to me once so for now this is all i know about this wired bug if i find anything more i shall post again

things that disappeared for me: wooden fences,metal detractors, spot lights, office chairs,rifle ammo, shotgun ammo, pistol ammo, TVs, g36

**Comment by Bamarin** [comment]
also wooden chairs, so i think all the chairs

**Comment by StephenPuffs** [comment]
I believe this would've happened with TVs, chairs, lamps, and spotlights.  Your G36C would not have been lost.  However as of Sunday this should be fixed.  If not please explain if you had the things out when you disconnected or if they were only in your storage.

**Comment by moher4** [comment]
things like my TV disappear after i put them in the storage and DC if i keep anything on me they dont disappear

**Comment by leffe-nl** [comment]
same happend for me 
- the first time I lost tv, wooden chairs, lamp and office chairs when I tried to get the chairs out of my storage they disappeared and after a disconnect the tv and lamp where also gone 
- second time the same items disappeared after disconnecting

**Comment by syl0r** [comment]
Fixed
