### ISSUE TITLE
Dispatcher Whitelist

### ISSUE THREAD

**Issue by PuffySandvich** [syl0r/Perpheads-Issues#273]
I got accepted for dispatcher, but i'm now able to be a senior officer INSTEAD of a dispatcher. Senior officer is great and all, but it's not what I applied for.

**Comment by lelios1** [comment]
You should probably ask Jordan, Chrissy or Chris about this. Send them a PM on the forums or make a thread here: "https://perpheads.com/forums/support.122/" and tag them.

**Comment by JDaymon** [comment]
@lelios1 no, that's not what he's supposed to do this is an issue related to the developers.

**Comment by syl0r** [comment]
Jordan or Chrissy are probably to blame for this, not a bug.
