### ISSUE TITLE
you can have 7 bobby pins on you.

### ISSUE THREAD

**Issue by silenT18** [syl0r/Perpheads-Issues#276]
when i was a cop i picked up a bobby pin after someone died and lost it and i had it in my inventory (before i was a cop i had 6 bobby pins on me).
so basicly after i resigned i had 7 bobby pins on me.
[http://steamcommunity.com/sharedfiles/filedetails/?id=700867914](url)

**Comment by LEWIS088** [comment]
Not exactly "game changing" is it.

**Comment by silenT18** [comment]
bro i found a bug im just reporting it, if fredy will want to fix or not i dont really mind.

**Comment by silenT18** [comment]
and tbh it is game changing because i gave example of 7 but you can have more then 7 it depens on how many bobby pins you get while being cop+having 6 bobby pins on you before getting the job,
and if 6 bobby pins breaks to you and you have that 1 it can be a game changing.

**Comment by Exnem** [comment]
You can have as many bobby pins as you want if you decide to keep stacking them.

**Comment by silenT18** [comment]
Nope, you can have maximum 12, if you gonna have on you 6 while civilian and then sign to the police and get 6 more, you gonna have 12 max, but then you can sign up to the police again and make 6 more so it will be 18.........

**Comment by Exnem** [comment]
That's what i just said, you can keep stacking them by resigning and re-applying. That way you can carry up to 100 if you really want to.
