### ISSUE TITLE
Bobby pin cuffing

### ISSUE THREAD

**Issue by jimmythehamster** [syl0r/Perpheads-Issues#278]
If you cuff someone who is mid-bobby pin, they will get stuck in the bobby pin "freeze" where they can't move, look around or do anything. Cops can't drag them, nobody can do anything to get them out of it. The only solution I've found is to be knocked unconscious and then be revived which fixes it.

**Comment by silenT18** [comment]
well its rarely happen when you cuff someone when he's mid bobby pin
you can just wait and then cuff them both.

**Comment by jimmythehamster** [comment]
It's still a bug.

**Comment by silenT18** [comment]
i dont think there is a fix for that, seems alot of work for something that rarely happens.

**Comment by lelios1** [comment]
I am pretty sure that it corrects itself if you uncuff him.

**Comment by jimmythehamster** [comment]
Doesn't.

**Comment by StephenPuffs** [comment]
Should be fixed for Thursday.
