### ISSUE TITLE
Glitching invisible inside cars.

### ISSUE THREAD

**Issue by JefferCake** [syl0r/Perpheads-Issues#279]
While a car is moving fast enough for the tumble animation to happen. If you spam E you can get back inside the car and you become invisible. 

Could be a huge issue for when getting away from police, you could technically get a car which looks completely empty full of invisible people.

**Comment by LaCreepis** [comment]
I tested this out myself and only works when somebody is currently driving the car, you need to be a passenger for this to work

Video
https://youtu.be/afMQkHMla-M

**Comment by StephenPuffs** [comment]
Done
