### ISSUE TITLE
Minor V3 map issue

### ISSUE THREAD

**Issue by Minilarro** [syl0r/Perpheads-Issues#281]
Found a hovering tree in the forest next to the highway. Location shown below
http://images.akamai.steamusercontent.com/ugc/270595996994134290/0141E57190050E5538DC14CCD35BA9C717CAB485/
http://images.akamai.steamusercontent.com/ugc/270595996994141421/88CB752ACEA0CBD72D99C8ABDC3BBCC471A8522A/

**Comment by syl0r** [comment]
Won't fix, not worth recompiling the entire map.
