### ISSUE TITLE
Shotgun Ammo for cpl+ 

### ISSUE THREAD

**Issue by lelios1** [syl0r/Perpheads-Issues#282]
If you have buckshot ammo on you and go rearm at the PD armory then you are going to receive 5 buckshot boxes with 6 bullets in each one (no matter how much ammo you had before).

**Comment by jimmythehamster** [comment]
I think it's when you respawn you lose most of your ammo and are left with only 6 shells per box.

**Comment by lelios1** [comment]
Not when you respawn, it is when you go to the armory.

**Comment by jimmythehamster** [comment]
I mean it only happens when you visit the armory after respawning.

**Comment by StephenPuffs** [comment]
The boxes are basically the same as magazines in the case for shotguns (and M24), so they should be the same capacity as the gun itself can hold.  This being the case, the ammo in the boxes given in the trunk will now reflect this.
