### ISSUE TITLE
Vehicle Trunk bug

### ISSUE THREAD

**Issue by Esquisita** [syl0r/Perpheads-Issues#286]
Happend when i was trying to store 20 metal pieces into trunk of my vehicle (Honda Civic 6th Gen, 1997 Type-R) and lost it.

**Comment by chrisadamson** [comment]
More information may be needed.

What were you trying to do at the time? Where were you? What time was this? Were the items put back into your storage?

**Comment by Esquisita** [comment]
That happened yesterday (05.07.2016) about 15:40 GMT +1 time. I was buying materials and ran out of inventory space so went to my car that was parked in city garage and tried to store it in trunk. Since that i didnt see my lost materials anymore.

**Comment by Esquisita** [comment]
Also car trunk was empty when i started storing stuff.
Car has one performance upgrade and changed color.

**Comment by syl0r** [comment]
fixed
