### ISSUE TITLE
Map turning invisible seemingly randomly when accessing the storage chest

### ISSUE THREAD

**Issue by LaCreepis** [syl0r/Perpheads-Issues#287]
I am reporting this for somebody else, apparently how this happened is just by accessing the storage chest and the map would turn invisible seemingly out of random (Just like the same problem we had back then at long shootouts, entities and players/cars would go invisible). Script error is here, possibly useful.

CBaseEntityList::AddNonNetworkableEntity: no free slots!

[ERROR] gamemodes/perp/gamemode/modules/guicore/cl_gui.lua:21: Tried to use a NULL entity!
  1. SetNoDraw - [C]:-1
   2. drawModelTexture - gamemodes/perp/gamemode/modules/guicore/cl_gui.lua:21
    3. v - gamemodes/perp/gamemode/modules/inventorygui/inventorywheel/inventorywheel.lua:388
     4. unknown - lua/includes/modules/hook.lua:84

Edit: This also just happened to me. I asked Xq, gave him my current playtime on the server (3 hours, 34 minutes) and said that he would've "feared that this might happen", not sure if that helps with anything.

**Comment by syl0r** [comment]
potentially fixed
