### ISSUE TITLE
Police rank symbols randomly flickering

### ISSUE THREAD

**Issue by ttjr123** [syl0r/Perpheads-Issues#288]
The epaulettes and chevrons on police models are sometimes seen to disappear until you move your camera where they will re-appear. First noticed this on a Sergeant and tested it on myself by going third person in car to find mine were disappearing/re-appearing too.

**Comment by chrisadamson** [comment]
Known bug, issue with system used. XQ and Fredy are aware.

**Comment by StephenPuffs** [comment]
Fixed
