### ISSUE TITLE
Limousine spawn

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#29]
The only spawn point working for the Limo is the last slot of the parking lot near the regals.
So when there's a car there this is what happends
![rp_paralake_city_v20061](https://cloud.githubusercontent.com/assets/10375578/5794182/43d619b6-9f63-11e4-8dc8-411a709a5c36.jpg)

**Comment by StephenPuffs** [comment]
Actually there should be two spots, odd this would happen regardless.  I will create more spots that it could spawn along there.  Hopefully shouldn't happen again.
