### ISSUE TITLE
[Forgotten] Police Broadcasts

### ISSUE THREAD

**Issue by chrisadamson** [syl0r/Perpheads-Issues#296]
Freddo, we discussed this the other day along with the other stuff for the police computer and agreed that the F3 computer would be the best place for this. 

For **Corporal plus** 

Discussion Post: https://perpheads.com/threads/police-broadcast.16350/

Main Idea: A broadcast for police/emergency services only 

Full description of the idea: Whitelisted officers can do /plpd or something wich is similar to the /broadcast feature the mayor already has today

Why should it be added?: To help the PLPD with crowd control when there is a shootout or a traffic stop/accident. It also prevents cars flying into a disabled car or police on the road. I'm aware an officer can ask the mayor or make an advert but they need to pay 200. I know 200 isn't that much but money is money right?

**Comment by syl0r** [comment]
not forgotten, wasn't gonna be part of the update.
