### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by D3luX** [syl0r/Perpheads-Issues#298]
Suddently my storage items is getting invisible and then my inventory, and then everything else gets invisble.

## **Images:**
[Image 1 - Invisible Inventory](http://images.akamai.steamusercontent.com/ugc/442859490860159601/58952642071CF5B02F2B5D421D40F1F2453B7671/)
[Image 2 - Invisible storage](http://images.akamai.steamusercontent.com/ugc/442859490860159816/6A751E5DDBFF55B248712A6B03B376A20BFE2FD7/)
[Image 3 - Console](http://images.akamai.steamusercontent.com/ugc/442859490860159990/772BCCA28B09677E0E667291DD8AE1014C52D6F6/)

# **## Here is console errors, some of them.**
CBaseEntityList::AddNonNetworkableEntity: no free slots!

[ERROR] gamemodes/perp/gamemode/modules/guicore/cl_gui.lua:12: Tried to use a NULL entity!
  1. SetSkin - [C]:-1
   2. drawModelTexture - gamemodes/perp/gamemode/modules/guicore/cl_gui.lua:12
    3. drawCircles - gamemodes/perp/gamemode/modules/inventorygui/inventorywheel/inventorywheel.lua:107
     4. v - gamemodes/perp/gamemode/modules/inventorygui/inventorywheel/inventorywheel.lua:424
      5. unknown - lua/includes/modules/hook.lua:84

VehicleType:prop_vehicle_jeep:
CBaseEntityList::AddNonNetworkableEntity: no free slots!

[ERROR] gamemodes/perp/gamemode/modules/weaponsystem/sh_attachments.lua:189: Tried to use a NULL entity!
  1. SetParent - [C]:-1
   2. AddWeaponAttachment - gamemodes/perp/gamemode/modules/weaponsystem/sh_attachments.lua:189
    3. CheckAttachments - gamemodes/perp/gamemode/modules/weaponsystem/sh_attachments.lua:225
     4. unknown - gamemodes/perp/entities/entities/prop_back_gun/cl_init.lua:58

**Comment by syl0r** [comment]
most likely fixed
