### ISSUE TITLE
Facials are always changing

### ISSUE THREAD

**Issue by BenStandish** [syl0r/Perpheads-Issues#30]
Upon reconnecting,  your facial will be the same character model, but it may change it's characteristics. For example, a bold guy will reconnect to have a black fuzz, an Asian can reconnect and have a different moustache, and mine seems to go from grey hair, to ginger, I also seem to change beards.

**Comment by Creepis** [comment]
The male_04 model (this fella http://i.imgur.com/bgCCqgb.jpg) also seems to be changing hair and beard.This has been annoying for a while now and the problem exist since the release of v2.

It makes myself also look pretty disgusting with that blonde hair and beard.

**Comment by syl0r** [comment]
Not a bug
