### ISSUE TITLE
Secret Service; Silenced Beretta 

### ISSUE THREAD

**Issue by Murtsley** [syl0r/Perpheads-Issues#304]
Secret Service agents are unable to retrieve a silenced Beretta despite the option being there. The Mac-10 and M1911s still work as intended but the Beretta doesn't work at the armoury:

Press E on armourer > Options of firearms appears > Click Beretta > Acts as if it has been spawned (In terms of dialog) but doesn't spawn.

**Comment by StephenPuffs** [comment]
Probably to do with the fact that suppressed M9 no longer exists as an item alone.

**Comment by StephenPuffs** [comment]
Fixed.
