### ISSUE TITLE
Beretta M9

### ISSUE THREAD

**Issue by Minilarro** [syl0r/Perpheads-Issues#305]
After having taken a beretta M9 from storage, regardless of attachements, it will not work properly. An animation always plays, as if you fire the last bullet, then it repeats itself. It's not usable whatsoever.

**Comment by StephenPuffs** [comment]
Do you have the latest content?  There was a change in content between 5th of July and 6th of July regarding this pistol.

**Comment by StephenPuffs** [comment]
Anyone with this issue needs to be sure they have the latest content.  Resolved.
