### ISSUE TITLE
Storage bug

### ISSUE THREAD

**Issue by D3luX** [syl0r/Perpheads-Issues#307]
After some time and have used storage a couple of times storage start to fuck up. I made en erlier about the little same. And im not the only one having it

Image - http://images.akamai.steamusercontent.com/ugc/451866700980077464/E50D7B9CDE843F981034E8D92116FBC52CCE38B0/

Console LUA Error
[ERROR] gamemodes/perp/gamemode/modules/guicore/cl_gui.lua:21: Tried to use a NULL entity!
  1. SetNoDraw - [C]:-1
   2. drawModelTexture - gamemodes/perp/gamemode/modules/guicore/cl_gui.lua:21
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/storage/storage.lua:428
[ERROR] gamemodes/perp/gamemode/modules/weaponsystem/sh_attachments.lua:189: Tried to use a NULL entity!
  1. SetParent - [C]:-1
   2. AddWeaponAttachment - gamemodes/perp/gamemode/modules/weaponsystem/sh_attachments.lua:189
    3. CheckAttachments - gamemodes/perp/gamemode/modules/weaponsystem/sh_attachments.lua:225
     4. unknown - gamemodes/perp/entities/weapons/perpheads_gun_base/cl_init.lua:113

CBaseEntityList::AddNonNetworkableEntity: no free slots!

[ERROR] gamemodes/perp/gamemode/modules/weaponsystem/sh_attachments.lua:189: Tried to use a NULL entity!
  1. SetParent - [C]:-1
   2. AddWeaponAttachment - gamemodes/perp/gamemode/modules/weaponsystem/sh_attachments.lua:189
    3. CheckAttachments - gamemodes/perp/gamemode/modules/weaponsystem/sh_attachments.lua:225
     4. unknown - gamemodes/perp/entities/weapons/perpheads_gun_base/cl_init.lua:113

[ERROR] gamemodes/perp/gamemode/modules/guicore/cl_gui.lua:21: Tried to use a NULL entity!
  1. SetNoDraw - [C]:-1
   2. drawModelTexture - gamemodes/perp/gamemode/modules/guicore/cl_gui.lua:21
    3. v - gamemodes/perp/gamemode/modules/inventorygui/inventorywheel/inventorywheel.lua:388
     4. unknown - lua/includes/modules/hook.lua:84

**Comment by D3luX** [comment]
[ERROR] gamemodes/perp/gamemode/modules/weaponsystem/sh_attachments.lua:189: Tried to use a NULL entity!
  1. SetParent - [C]:-1
   2. AddWeaponAttachment - gamemodes/perp/gamemode/modules/weaponsystem/sh_attachments.lua:189
    3. CheckAttachments - gamemodes/perp/gamemode/modules/weaponsystem/sh_attachments.lua:225
     4. DrawModel - gamemodes/perp/gamemode/modules/itemsystem/itembases/base_weapon.lua:289
      5. drawModelTexture - gamemodes/perp/gamemode/modules/guicore/cl_gui.lua:31
       6. drawCircles - gamemodes/perp/gamemode/modules/inventorygui/inventorywheel/inventorywheel.lua:107
        7. v - gamemodes/perp/gamemode/modules/inventorygui/inventorywheel/inventorywheel.lua:424
         8. unknown - lua/includes/modules/hook.lua:84

**Comment by D3luX** [comment]
[ERROR] gamemodes/perp/entities/effects/shell_eject/init.lua:107: attempt to index field 'Entity' (a nil value)
  1. unknown - gamemodes/perp/entities/effects/shell_eject/init.lua:107

**Comment by syl0r** [comment]
probably fixed

**Comment by D3luX** [comment]
Still not fixed
http://images.akamai.steamusercontent.com/ugc/437238244788323498/DB5CC44D9E2C758C50C032D1B87F8FBE7BCB9C9E/
