### ISSUE TITLE
Weird invisible entities at gas stations.

### ISSUE THREAD

**Issue by jimmythehamster** [syl0r/Perpheads-Issues#309]
There's some weird invisible props or something that are underneath gas stations around the map that cause you to get stuck on them while trying to walk over them.

**Comment by LaCreepis** [comment]
This happens very often now, this would happen rarely near the begining of V2 but is an often occuring problem now a days.

**Comment by BenStandish** [comment]
I'm fairly certain these entities are the bodies of the gas pump 'NPC's' that get smacked about and rag-doll; I could be wrong though.

**Comment by StephenPuffs** [comment]
It's no doubt the physics object of either the ATM or the gas pumps.  If you could possibly give some insight as to when you notice these appearing as in time, or after some event nearby they appear it would be helpful.
