### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Haydenp10** [syl0r/Perpheads-Issues#313]
For a lot of people, their games have been crashing recently and maybe there is a fix that could be done?

**Comment by D3luX** [comment]
Same as this? https://github.com/syl0r/Perpheads-Issues/issues/307

**Comment by StephenPuffs** [comment]
This is hardly a bug report, instead it's just stating something that happens.  A bug report needs to include what caused it or potentially caused it, or an identifiable problem.  We know it crashes but we don't know why in some cases either.  GMod is GMod.  That said we will work on some things that may help.
