### ISSUE TITLE
Script errors causing entities to become invisible, as well as your inventory.

### ISSUE THREAD

**Issue by BenStandish** [syl0r/Perpheads-Issues#314]
Here's a copy of my console after getting them, nothing specific on my end caused them. 

CBaseEntityList::AddNonNetworkableEntity: no free slots!

[ERROR] gamemodes/perp/gamemode/modules/weaponsystem/sh_attachments.lua:189: Tried to use a NULL entity!
  1. SetParent - [C]:-1
   2. AddWeaponAttachment - gamemodes/perp/gamemode/modules/weaponsystem/sh_attachments.lua:189
    3. CheckAttachments - gamemodes/perp/gamemode/modules/weaponsystem/sh_attachments.lua:225
     4. DrawModel - gamemodes/perp/gamemode/modules/itemsystem/itembases/base_weapon.lua:289
      5. drawModelTexture - gamemodes/perp/gamemode/modules/guicore/cl_gui.lua:31
       6. unknown - gamemodes/perp/gamemode/modules/inventorygui/storage/storage.lua:428

**Comment by StephenPuffs** [comment]
If it isn't obvious this is repeating text, so you only need to copy it once then say it repeats, however I believe I know the problem, just don't know a solution as to it yet.

**Comment by BenStandish** [comment]
I literally just quick copied my console; I wouldn't bother to check it when I know little of LUA.
