### ISSUE TITLE
CMDL Cache out of memory

### ISSUE THREAD

**Issue by jimmythehamster** [syl0r/Perpheads-Issues#316]
Happens randomly. Many others including myself have reported getting this bug. For me it just happens after playing for a while, so maybe a memory leak?

**Comment by jimmythehamster** [comment]
Started after the update.

**Comment by StephenPuffs** [comment]
How many add-ons do you have installed and how sizable are they?  Also try disabling them, restarting GMod, then see if you continue to get this error.

**Comment by jimmythehamster** [comment]
Only tdm cars and the ph map+map content.

**Comment by syl0r** [comment]
This might be fixed.
