### ISSUE TITLE
Minor sniper scopes issue

### ISSUE THREAD

**Issue by LaCreepis** [syl0r/Perpheads-Issues#317]
Really just a minor issue for scopes, when you have your weapon in passive stance and have one of the sniper scopes (Schmidt&Bender or other long range options) you can hold right click and the scope will actually render in passive stance as it would normally do when you view down the ironsights in attack stance.
![ss 2016-07-09 at 11 15 29](https://cloud.githubusercontent.com/assets/14893257/16707192/7e037eb6-45c6-11e6-9885-e88f378fbaef.png)

**Comment by StephenPuffs** [comment]
Fixed
