### ISSUE TITLE
SS unable to retrieve the Suppressed Beretta M9 from the armory

### ISSUE THREAD

**Issue by LaCreepis** [syl0r/Perpheads-Issues#319]
Should be self explanatory, SS cannot receive the Suppressed Beretta M9 option from the armory anymore, pressing it gives you nothing. Also, the Mac-11 comes without at stock, might want to fix that since it's pretty bad without one.

**Comment by StephenPuffs** [comment]
Duplicate https://github.com/syl0r/Perpheads-Issues/issues/304
