### ISSUE TITLE
Notepad bug on the Phone

### ISSUE THREAD

**Issue by RogueCarTyres** [syl0r/Perpheads-Issues#321]
if I try to save notes on the phone, it doesn't save directly onto there. I think it still saves the .txt file though

**Comment by StephenPuffs** [comment]
What do you mean it doesn't save directly onto there?

**Comment by RogueCarTyres** [comment]
So if i write a note on there, and click 'save', when i back out the note I made doesn't appear.

**Comment by LaCreepis** [comment]
I don't know what the usual save direcoty for notepad .txt files were again but mine were deleted after the update, you also can't save any new one's, they're just non-existant.

**Comment by syl0r** [comment]
fixed
