### ISSUE TITLE
Tooter Error

### ISSUE THREAD

**Issue by ttjr123** [syl0r/Perpheads-Issues#325]
1) My avatar appears as a firefighter when it's a police officer.
2) Script Error below:

http://puu.sh/q09XU/4ff3d71e37.png

**Comment by jimmythehamster** [comment]
Better remove tooter

**Comment by PHSneaky** [comment]
I have the same issue,  but have not tried retaking a picture yet. I did not however get a script error.

**Comment by StephenPuffs** [comment]
Yea, that's probably true since we changed police. Will let Fredy know since I let him manage it.

**Comment by syl0r** [comment]
fixed (at least the avatar thing)
