### ISSUE TITLE
Weapons not showing on back when taking out pistols.

### ISSUE THREAD

**Issue by Synatec** [syl0r/Perpheads-Issues#326]
I've noticed that if you have a weapon that shows on your back but then take out a pistol it will dissapear from your back and no one will  be able to see it. It has caused my death in multiple police situations already.

So when you holster your pistol after getting a big weapon you will not be able to see it.

EDIT:
This also occurs if you step into a vechicle.

**Comment by syl0r** [comment]
fixed (hopefully)
