### ISSUE TITLE
Test Drive Bug

### ISSUE THREAD

**Issue by AlliatTrapani** [syl0r/Perpheads-Issues#328]
When I try to make a test drive at the car dealer. I can select the cars but when I press on the car that I want to test nothing happens. When I restart gmod I still have the same problem. I also tried it with otther cars but that does not work either. I hope some of you guys knows how to fix it.

**Comment by Nutzu3650XL** [comment]
I am also experiencing this issue. I am currently downloading and setting up a fresh installation of gmod with only the PH addons and CSS textures, will see if it still persists

**Comment by LaCreepis** [comment]
Also experienced this and asked Fredy if he disabled test driving which he didn't do, I just waited some time in the server and I could test drive, not sure why I couldn't when I joined the server freshly.

**Comment by Nutzu3650XL** [comment]
Have done a fresh reinstall of GMOD with only perpheads content and CSS textures. It is the same for me. I still cannot test drive a car. Please adress this issue

**Comment by StephenPuffs** [comment]
Fixed
