### ISSUE TITLE
Drunk/Revival shader effects bugging out when using ironsights

### ISSUE THREAD

**Issue by LaCreepis** [syl0r/Perpheads-Issues#329]
I believe that these are shader effects but anyways, after being revived or being drunk and having a blurry screen and you view down your ironsights of your weapon the screen will just be frozen and viewing down the ironsights in drunk condition will slowly give you these solid colors
![4000_screenshots_20160713115608_1](https://cloud.githubusercontent.com/assets/14893257/16896874/e7f75a38-4ba0-11e6-8e33-270d98f9a8a0.jpg)
This is solid art.

**Comment by StephenPuffs** [comment]
I saw this in testing, but quite frankly, I don't know what would possibly cause it, as we don't apply any special screen effects when sighted.  #blamegarry

**Comment by syl0r** [comment]
Not worth fixing since art shouldn't be destroyed

**Comment by LaCreepis** [comment]
thanks fredy
