### ISSUE TITLE
Car bomb glitch

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#33]
I have been told by PewPewYahh (STEAM_0:0:33643092) his friend and him were SS and when they entered the limo (which had a car bomb installed on) the limo blew up and they both died, but his friend's body went under ground so medic was unable to revive him.

this cold be a rare case and hard to reproduce

**Comment by BenStandish** [comment]
I think it's just Gmod physics, can't really fix this.

**Comment by syl0r** [comment]
As Standish said
