### ISSUE TITLE
External storage bug

### ISSUE THREAD

**Issue by Atomicwizard** [syl0r/Perpheads-Issues#330]
So basically i was in my apartment with a couple friends and one of them need something so i placed down my external storage chest and then i stuck the weed in there and tried to place the seeds in with it and it wouldn't let me stick the seeds even though there was enough room. I then made a report to ask a staff if it was a known bug and imperial said just to make a bug report also when he responded he got my friend to try store two things in there and it wouldn't work for him.

**Comment by syl0r** [comment]
fixed
