### ISSUE TITLE
A couple of UI bugs

### ISSUE THREAD

**Issue by magemagicc** [syl0r/Perpheads-Issues#331]
Mostly UI based bugs at the moment that I am witnessing, using the F3 Computer for police doesn't load pictures of people anymore its just a blank grey square as simple as it sounds really, you see the name of the person but no picture, no script errors occur. Aswell as that the F3 (computer menu - not organisation menu) and F4 menu have a purple-black boarder around it so I assume there should be something there but the textures for it are missing yet again no script errors occur. http://puu.sh/q50Ga/5ad579c8c5.png

There's also a current bug while using any type of shop which causes a lot of script errors, mostly very similar errors so I'll only paste some of them. Also not sure if the shop UI looks correct? It looks quite funky atm http://puu.sh/q50KK/aa1a5ab19e.jpg
` 1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_store.lua:34

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_inv.lua:66

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_desc.lua:24

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_store.lua:34

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_inv.lua:66

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_desc.lua:24

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_store.lua:34

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_inv.lua:66

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_desc.lua:24

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_store.lua:34

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_inv.lua:66

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_desc.lua:24

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_store.lua:34

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_inv.lua:66

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_desc.lua:24

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_store.lua:34

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_inv.lua:66

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_desc.lua:24

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_store.lua:34

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_inv.lua:66

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_desc.lua:24

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_store.lua:34

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_inv.lua:66

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_desc.lua:24

[ERROR] lua/derma/derma_gwen.lua:32: attempt to perform arithmetic on local 'w' (a boolean value)
  1. Inactive - lua/derma/derma_gwen.lua:32
   2. PaintFrame - gamemodes/perp/gamemode/modules/guicore/cl_skin.lua:1548
    3. unknown - gamemodes/perp/gamemode/modules/inventorygui/shops/shop_store.lua:34

`

**Comment by syl0r** [comment]
possibly fixed
