### ISSUE TITLE
Commenting and rating in private threads shows up in Recent Activity (not sure who can see it)

### ISSUE THREAD

**Issue by Krzeszny** [syl0r/Perpheads-Issues#333]
I'm not sure whether it only shows up for people who are allowed to see it, or (most likely) for everyone.

I haven't checked if posting shows up as well.

Even if _not_ everyone can see it, it shouldn't show up at all, as it causes confusion.

**Comment by syl0r** [comment]
Only people who can view the thread can see it in the feed.
Of course it should show up in the feed.
