### ISSUE TITLE
Bug with the M9 barretta cant aim down sight

### ISSUE THREAD

**Issue by NeluDaHunter** [syl0r/Perpheads-Issues#334]
this is what happens when i aim down sights http://images.akamai.steamusercontent.com/ugc/272849658864448707/4B01866188C43E83611D2409B8DAE17F3EA30CB4/

Its basically unplayable to play cop :"(

**Comment by jimmythehamster** [comment]
That's the old model. Delete the perpheads folder from the addons folder and restart tha game, upon rejoining it might fix itself.

**Comment by StephenPuffs** [comment]
Get the latest content.
