### ISSUE TITLE
Shotguns.

### ISSUE THREAD

**Issue by lelios1** [syl0r/Perpheads-Issues#335]
The sawed off shotgun and the short remi although they are available as an option at the shooting range, they do not function. If you press them, you are going to be tped to the shooting range normally and have your stuff removed but you wont be able to equip the 2 shotguns even though they appear in your Q inventory. (lost 4k because of them :-1: )

**Comment by LaCreepis** [comment]
Lost $2,000, fucking shooting range scammed me.

Not sure when the Remington 870 Short or the Sawn Off will be available for crafting in the mixtures tab tbh, it's been some time.

**Comment by Exnem** [comment]
I had lost $2,000. at the shooting range too, I went to test the Glock 18, where as it would give me Glock 20 mags instead of the correct ones, I even filled the magazines before checking because obviously you'd trust the range actually gave you the correct items.

**Comment by StephenPuffs** [comment]
There's a reason these haven't fully implemented yet.  So removed from the list for now.  Will refund lelios1 4k, Creepis 2k, and Exnem 2k.  Thank you for the reports.
