### ISSUE TITLE
SG550 no longer an option for S.W.A.T in the armory

### ISSUE THREAD

**Issue by LaCreepis** [syl0r/Perpheads-Issues#337]
^title, you can no longer get the SG550 for S.W.A.T in the armory, not sure why this would be removed as the SG550 was always the go to weapon for me in terms of reliability and damage. This weapon might've been removed when SWAT was also able to get the HK USP40 from the armory but that is also currently bugged as mentioned here https://github.com/syl0r/Perpheads-Issues/issues/336

**Comment by StephenPuffs** [comment]
Done on purpose because of how SWAT never gave their demands for weaponry so I removed it. Use the M16A4 instead, practically the same.

**Comment by LaCreepis** [comment]
FUCK SAKE
