### ISSUE TITLE
Grenades are terribad/doesn't always kill anyone within range.

### ISSUE THREAD

**Issue by LaCreepis** [syl0r/Perpheads-Issues#339]
I noticed this happening way too often, the current frag grenades (Not the unimplemented one's e.g Mk2, M69 and M213 (IIRC?)) really just don't have the blast radius to kill or even damage someone. I was standing next to a nade, maybe 4 or 6 meters away and didn't do any kind of damage to me (I was an officer at the time, I believe it may just be a bug with armor and it could kill civilians) and is just really useless as of right now. More testing needs to be done though in different locations, I only noticed this in the Regal staircase and in the suburbs house 1 front door.

**Comment by LaCreepis** [comment]
This should probably be a good example https://youtu.be/Z2AR7QFOlMk?t=5m37s

**Comment by StephenPuffs** [comment]
Blame internal functions for this, I will be trying something to see if I can fix this partially when I get around to adding the Mk 2.  In your example the grande is probably outside the door and blocked by the door frame.
