### ISSUE TITLE
speed limiter not working.

### ISSUE THREAD

**Issue by moher4** [syl0r/Perpheads-Issues#34]
the speed limiter dose not work for all the police cars expt the LT car for my rang rover, the charger the old one, hummer and transit i dont know about other cars but it dose not work for me even if i get in anyone's car so i dont know if it is me or the thing it self being bugged also it somehow worked 3 or 4 times on my range rover before but wont do it again.

**Comment by Bamarin** [comment]
asaik it never worked from the time it got updated from cruise mode

**Comment by syl0r** [comment]
Fixed
