### ISSUE TITLE
Organisation Storage Bugged?

### ISSUE THREAD

**Issue by LeBlicky** [syl0r/Perpheads-Issues#341]
When anything is put into org storage it can't be taken out again atleast with me that is. My M14 was put into org storage when I tried to get it out I would click, it would make the sound and nothing would happen. You can't take anything out of org storage.

**Comment by LaCreepis** [comment]
Tried it out today and could take out a cup of joe just fine. Your M14 also seems to be gone now from the org storage.

**Comment by Minilarro** [comment]
having checked the logs from around the time you posted this bug report, the last time you interacted with a M14 via storage/trunk was the 23rd of July, when you retrieved it from your Raptor. Are you positive that you put it into org storage?

http://i.imgur.com/wM9RA11.png
