### ISSUE TITLE
Distorted Cars

### ISSUE THREAD

**Issue by EmilGrouleff** [syl0r/Perpheads-Issues#343]
Almost all of the cars look like this,but some of them don't, i have downloaded all of the addons, and i don't know what to do.

![4000_screenshots_20160728155024_1](https://cloud.githubusercontent.com/assets/19330161/17215915/e18f008c-54de-11e6-861d-28b44dc0f290.jpg)
![4000_screenshots_20160728154534_1](https://cloud.githubusercontent.com/assets/19330161/17215920/e3f3f0da-54de-11e6-8d64-ba13957c27aa.jpg)

(IGN) Emil Jul

**Comment by KodiZX** [comment]
It's because your video settings are too low, change models to high.

**Comment by EmilGrouleff** [comment]
Thank you very much
