### ISSUE TITLE
Quite an important firefighter bug

### ISSUE THREAD

**Issue by magemagicc** [syl0r/Perpheads-Issues#344]
Currently if you have a fire extinguisher equipped prior to becoming a firefighter, you don't receive the 'unlimited ammo' fire extinguisher. Here's a very easy way to re-produce the bug.

Have a fire extinguisher equipped before enlisting for the job. Then once you become a firefighter, it will remain equipped on you, and this means you won't receive the special one you get with the job. If you now unequip it you no longer have a fire extinguisher at all, and you are only able to use the one in your inventory that you had originally (if you re-equip it), meaning you have to use your own fire extinguisher and in most cases even though its not the money that's a problem, it's the pure fact that it will run out if you are trying to put out a fire at the top of city hall since the hose range isn't far enough for that. Yes you can fix this by re-enlisting for the job, but if you make it all the way to CH only to realise what just happened, you get really annoyed.

**Comment by syl0r** [comment]
It would take way too much effort to fix this, just don't bring your own fire extinguisher.
