### ISSUE TITLE
GMC Vandura bodykit & trims

### ISSUE THREAD

**Issue by Minilarro** [syl0r/Perpheads-Issues#345]
I noticed that the front of the Vandura has changed, but along with it, you are no longer capable of seeing any difference between the Free Candy bodykit, which removes the spoiler, and the default car. In addition, any trims are not visible.

http://images.akamai.steamusercontent.com/ugc/272850516045643469/A4BD95BC60BCB5761A04708AE6AB86A6B75F9164/

**Comment by LaCreepis** [comment]
Wait, there is a free candy bodykit? fucking g, instant buy

**Comment by MatStarS** [comment]
In addition to this: Some cars I've experienced with have had the same problem but it seems like they come back after time or at a certain time?

**Comment by Minilarro** [comment]
This issue has been resolved for me by removing TDM files from my local files that were leftover after unsubscribing to them from the workshop.
