### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by PH4KixHesus** [syl0r/Perpheads-Issues#346]
like when i press f1 i crash and also i crash randomly like if i go cop and just drive around my screen goes black and my gmod is not running anymore.i really need help and if i dont get help im gonna be able to play perp

**Comment by MatStarS** [comment]
The crashes are already a know problem, the random blackscreens are probably your PC 'dying' or something

**Comment by ShrikeTheGod** [comment]
The black screen might be due to Drivers Crashing, look up your graphics card drivers and download the newest ones!

**Comment by StephenPuffs** [comment]
Sounds like you're having more issues than simply related to the server.  We are already looking into fixes for the F1 menu being the cause of a crash.
