### ISSUE TITLE
Cooking flashes

### ISSUE THREAD

**Issue by MatStarS** [syl0r/Perpheads-Issues#347]
You aren't able to cook flashes anymore. When you throw it after holding it for about 4-5 seconds (Should create an instant pop flash) it automatically resets. Not quite sure if this was intentionally made like this but yeah.

**Comment by StephenPuffs** [comment]
After you pull the pin and hold it with LMB, you need to press RMB while still holding LMB to release the lever in order for it to start "cooking".  Release LMB to throw.
