### ISSUE TITLE
Police Computer Properties Bug

### ISSUE THREAD

**Issue by jimmythehamster** [syl0r/Perpheads-Issues#348]
There are a few properties that  don't show up on the property search in te police computer including the farm, hicktown 3 and 4 and wood cabin 3.

Also properties haven't been showing up on people's Police Computer database entries, there's been two occassions today when I've searched someone up who I know has a property and it doesn't show on their profile. The properties were farm and glassco if it helps.

**Comment by lelios1** [comment]
Add church as well, it doesn't show up either.

**Comment by JDaymon** [comment]
Shouldn't be an issue anymore, I've seen them atleast.
