### ISSUE TITLE
Job salaries

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#35]
as Mayor if you set the job salaries of SS to the max (210$/min) on their console it says thay are getting payed (360$/min) and i think this is not the only job which is bugged.
Also you can set the Medics salary only between 0 and 1 but they will still get a normal paycheck

**Comment by JDaymon** [comment]
Isn't this for VIP?

**Comment by Bamarin** [comment]
ah lol never thought about that... it could be. But still remain the problem with the medics

**Comment by StephenPuffs** [comment]
I will have to verify this, because as stated it may simply be a VIP thing.

**Comment by StephenPuffs** [comment]
Well I don't believe this happens anymore if it ever did so I will close this now.
