### ISSUE TITLE
Turning yourself in functions 50/50

### ISSUE THREAD

**Issue by PHSneaky** [syl0r/Perpheads-Issues#350]
Today, sombody turned themselfs in at the desk sargeant, and the lovely person dispatched this to all officers. A few hours later, sombody else turned themselfs in, still getting the message at the desk sargeant, however nothing happends. I don't know why, but i guess it's due people getting warranted by the mayor(which allows it)? People who are wanted by police computer don't seem to be alerted in /gov chat.

I robbed the bank not a long while ago, but later turned myself in. The desk sgt confirmed i turned myself in, but no officer came and i had to call 911. Officers claimed they saw nothing dispatched in /gov

**Comment by JDaymon** [comment]
Tried this with two people, haven't had any issues whatsoever
