### ISSUE TITLE
Selling Vehicles

### ISSUE THREAD

**Issue by BlackdownPH** [syl0r/Perpheads-Issues#352]
After selling a vehicle at the car dealership, when going to claim a vehicle, edit a vehicle, or sell another vehicle, the previously sold vehicle still appears as if it is in your list. You cannot interact with it, nor spawn it, however it still appears after it has been sold. I am unsure if it remains after rejoining the server.

**Comment by Drafaxo** [comment]
I can vouch for this, as it happened after I sold my Nissan 370z yesterday.

**Comment by StephenPuffs** [comment]
Fixed long time ago
