### ISSUE TITLE
Vehicle colour

### ISSUE THREAD

**Issue by Krazy1029** [syl0r/Perpheads-Issues#354]
I color my vehicle white at the car dealer but it appears as silver
http://images.akamai.steamusercontent.com/ugc/1621679306993328900/AFF0E57D5C114DEC86A902EAA9A976596ED02F90/

**Comment by LaCreepis** [comment]
Take off the smooth metallic.

**Comment by Krazy1029** [comment]
I've tried that.

**Comment by Krazy1029** [comment]
-FIXED
For some reason when I rejoined the server the next morning it's turned white.
