### ISSUE TITLE
People can unfreeze themselves with act's

### ISSUE THREAD

**Issue by LaCreepis** [syl0r/Perpheads-Issues#355]
If a player has been frozen by the godstick and he does an act via the console ('act dance' was used to test this) he will be unfrozen as soon as the act ends.

**Comment by PHSneaky** [comment]
Thanks for the info xd

**Comment by lelios1** [comment]
Acts can also make you stop when you are being dragged while cuffed.

**Comment by StephenPuffs** [comment]
Fixed
