### ISSUE TITLE
Police computer ERROR model for a certain female model

### ISSUE THREAD

**Issue by LaCreepis** [syl0r/Perpheads-Issues#356]
This female model in particular is showing up as an ERROR on the police computer
![ss 2016-08-12 at 12 51 02](https://cloud.githubusercontent.com/assets/14893257/17607605/11c60054-6027-11e6-92ba-5e8bea972522.png)
![ss 2016-08-12 at 12 51 30](https://cloud.githubusercontent.com/assets/14893257/17607607/1363d1c0-6027-11e6-81bc-60012f17cac8.png)
![ss 2016-08-12 at 12 52 02](https://cloud.githubusercontent.com/assets/14893257/17607647/594449c2-6027-11e6-8d3f-817a870ad6af.png)

**Comment by Bertie362** [comment]
Racism at its finest

**Comment by GrandTheftShitstorm** [comment]
Subscribe to [this](http://steamcommunity.com/sharedfiles/filedetails/?id=158185405) and you should be fine.

**Comment by LaCreepis** [comment]
Already am subscribed to it, this ERROR model doesn't just show up to me, DannyD is also getting this along with some other people.

**Comment by syl0r** [comment]
Is this still a thing?

**Comment by JDaymon** [comment]
I've spoken to some users, not a thing anymore apparently.
