### ISSUE TITLE
Traffic lights not working for me 

### ISSUE THREAD

**Issue by KINGSCOTTISH** [syl0r/Perpheads-Issues#358]
Well i have been with the community for a while now and just since i came back into Perpheads and the traffic lights do not show , there is no colour in them . 

Anyone please help, i have been told off many times now but i cant see them

**Comment by PHSneaky** [comment]
Not a bug since it's only you, id say make a thread in support on the forums.

**Comment by GrandTheftShitstorm** [comment]
I highly recommend you subscribe to [this](http://steamcommunity.com/sharedfiles/filedetails/?id=158185405) and get CS:S textures.

**Comment by KINGSCOTTISH** [comment]
I am not sure why but when I went back onto Perpheads it started to work again so yeah...
