### ISSUE TITLE
New drugs image

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#36]
When put into the storage all the drugs (weed, marijuana seeds, coca and coca seeds) look like the same, as the old ones.
http://cloud-4.steamusercontent.com/ugc/536259730581682470/766BD4F75BB6255BB342C46D57B1FD23FE573FE5/

**Comment by StephenPuffs** [comment]
Ah alright, will address for quick update in upcoming days.

**Comment by StephenPuffs** [comment]
Fixed, will be on for update on Wednesday.
