### ISSUE TITLE
"Core dark - blue" is broken for me

### ISSUE THREAD

**Issue by JarredInator** [syl0r/Perpheads-Issues#360]
https://i.gyazo.com/343bf57ec1171539037abed1c5b8c227.png
https://i.gyazo.com/e5511d7f2ca75b03400bf22c18f9ee5c.png

No one else seems to be having this problem.

**Comment by LaCreepis** [comment]
This happened to me once on my phone when the page didn't load correctly for me/slow internet. Refreshing it usually fixes it but since that wasn't your case, see if some disabling Chrome addons like AdBlocker/uBlock Origin help.
