### ISSUE TITLE
Car color not changing. (Walker)

### ISSUE THREAD

**Issue by SynatecIV** [syl0r/Perpheads-Issues#362]
The car dealer menu changed the colour I selected to something completely different. See video for more information.

https://www.youtube.com/watch?v=5El_lbOZlaU

Apologies for the horrible aspect ratio and no sound. Shadowplay royally fucked up. That along with the incorrect spelling of completely.

Made for Walker.

**Comment by JDaymon** [comment]
As far as I can remember this has to do with gmod_mcore so if you turn it off it should have the correct colour, I haven't had any issues with this at all myself.
