### ISSUE TITLE
Mass Crashing

### ISSUE THREAD

**Issue by Haydenp10** [syl0r/Perpheads-Issues#364]
As of the update today, a lot of crashing has been taking place and I have no idea what is causing it. Just now, probably about 30 people timed out from the server. Maybe in the server files there is a file to say what's causing the crashes but I have no clue. Just made this so you were aware of the issue.

**Comment by MangoJuicePerp** [comment]
I have the same issue. I have the multicore setting turned off and still I keep crashing. I don't know what's causing the problem as I have never had it before the update.

**Comment by ToXIcGaming** [comment]
Yes, I also have the same issue, The server was working fine earlier today.

**Comment by syl0r** [comment]
fixed
