### ISSUE TITLE
Lockpicking a car

### ISSUE THREAD

**Issue by chrisalex600** [syl0r/Perpheads-Issues#367]
If you lockpick a car, but leave it, you won't be able to get back in.

**Comment by magemagicc** [comment]
This is avoidable by making the car mode public and leaving the engine on before leaving the car. By turning off the engine or forgetting to make it public while the engine is on and leaving the car you basically guarantee no way into the car again unless you lock pick it again.

**Comment by PHSneaky** [comment]
thats actually pretty useful @magemagicc never knew that

**Comment by JDaymon** [comment]
This is if you turn the engine off, or leave without making the car public as the doors are still technically locked.
