### ISSUE TITLE
SS unable to select new guns from the PD Armory

### ISSUE THREAD

**Issue by Allabin** [syl0r/Perpheads-Issues#37]
Just found this today after the Sergeant update, the current two SS Agents were unable to select any other gun other than the already equiped Colt M1911.
Officers, SWAT, LT & Sgt have had no problem switching weapons as far as I know.

**Comment by JDaymon** [comment]
Never happened to me, and as far as I know I was SS yesterday.

**Comment by Allabin** [comment]
Hmm okay, I will be SS today and see if it works for me.

**Comment by StephenPuffs** [comment]
Fixed, simple mistake (will be corrected for Wednesday)

**Comment by Allabin** [comment]
Thank you Stephen!
