### ISSUE TITLE
Skin bug for female model

### ISSUE THREAD

**Issue by TheFrozenMonkeyKing** [syl0r/Perpheads-Issues#372]
One of the white female player models (not sure of the name) does not have the option to switch to blond hair, and the skin has been reset to the default one.

**Comment by LaCreepis** [comment]
what a shame

**Comment by Bertie362** [comment]
savage

**Comment by Ysauzi** [comment]
Not only the female one its also about 4 men ones that are only default. Chinese , black , old and white are default. I just want my moustache!

**Comment by syl0r** [comment]
fixed
