### ISSUE TITLE
can spawn two SWAT vans / Cannot spawn a limo

### ISSUE THREAD

**Issue by PHSneaky** [syl0r/Perpheads-Issues#375]
Me and a few others are unable to spawn any police car, we all have vip. I tried several times  but to no succces, some can spawn one however, i saw one lieutenant with a car and one who couldn't spawn one. My rank is cpl if that could be related

**Comment by LaCreepis** [comment]
Same problem with the SS, they cannot spawn the Limo in even though the Mayor funded one.

**Comment by PHSneaky** [comment]
Other SWAT members can spawn another van even tough already one is owned.

**Comment by LaCreepis** [comment]
oh fuck

**Comment by PHSneaky** [comment]
Appears to be fixed ayy

**Comment by PHSneaky** [comment]
While police cars do work, you're sometimes able to have two SWAT vans and you're still unable to spawn a limosine.

**Comment by jimmythehamster** [comment]
Can get two traffic officer cars too.

**Comment by LaCreepis** [comment]
Limousine has been fixed and is spawnable again.
