### ISSUE TITLE
Old trunk bug still there

### ISSUE THREAD

**Issue by D3luX** [syl0r/Perpheads-Issues#379]
Old Post - https://github.com/syl0r/Perpheads-Issues/issues/307

Im still having the issue with something invisible is in my trunk.

[http://images.akamai.steamusercontent.com/ugc/437238244788323498/DB5CC44D9E2C758C50C032D1B87F8FBE7BCB9C9E/](http://images.akamai.steamusercontent.com/ugc/437238244788323498/DB5CC44D9E2C758C50C032D1B87F8FBE7BCB9C9E/)

**Comment by syl0r** [comment]
it might just be that your car is still affected from when the bug was a thing

**Comment by KDG-Dom** [comment]
my transit has the same issue, nothing that the mods/admins suggest is working

**Comment by syl0r** [comment]
give me your steamids and I will fix it for you

**Comment by D3luX** [comment]
STEAM_0:1:25015916

**Comment by syl0r** [comment]
fixed it for you
