### ISSUE TITLE
Crashing when pressing f1.

### ISSUE THREAD

**Issue by itzsonzy** [syl0r/Perpheads-Issues#382]
Whenever i press f1 at all, i instantly drop to 0 frames before blackscreening and then my game closes fully. It used to happen every now and then, but now its become constant with me crashing almost every time i press f1.

Would be nice to get some help, thanks.

**Comment by itzsonzy** [comment]
has now evolved into this, can no longer log into the sever at all.
https://i.gyazo.com/ebf0e34b0c4507484896c6dca03068ed.png

**Comment by LaCreepis** [comment]
Try starting Garry's Mod in DirectX 9 by writing "-dxlevel 90" in the launch options of your Garry's Mod (without the "")

**Comment by itzsonzy** [comment]
already done this, worked for like 1 minuite then crashed, then went straight back to what you see on the screenshot.

**Comment by itzsonzy** [comment]
By the way, it works fine when i use that command apart from awful fps, but it isn't really playable because my monitor is 1920x1080 and it changes it down to like a quarter of my screen.

**Comment by syl0r** [comment]
How much ram do you have?

**Comment by itzsonzy** [comment]
8gb 2133hz or something along those lines. I know its 8gb but not 100% about the hz.

**Comment by syl0r** [comment]
Well, in that case I recommend making a forum thread asking for help. It doesn't seem like this is really related to the code of the gamemode but just an issue with gmod in general.
