### ISSUE TITLE
When warrant is removed from police computer, cannot become an officer.

### ISSUE THREAD

**Issue by PHSneaky** [syl0r/Perpheads-Issues#384]
I've seen various people who were warranted and have either died or had their warrants removed, being unable to become a police officer. The "dispatch" NPC claims he's still wanted and radio's this in. This has been fixed by putting the player in jail, however obviously very annoying.

**Comment by JDaymon** [comment]
I had a warrant and I didn't have any issues with this, got any ideas if this issue still exists @PHSneaky

**Comment by PHSneaky** [comment]
I'm not 100% sure, i haven't been very active the past couple of days but i have not seen it happen alot after i made this.

**Comment by JDaymon** [comment]
I'll close this then considering it's not an issue anymore what I can see

Thanks for reporting it though.
