### ISSUE TITLE
Skin-Changer NPC not working

### ISSUE THREAD

**Issue by JoeyLopezLopezFamily** [syl0r/Perpheads-Issues#385]
When you go to the Skin-changing NPC in Jennifers, it doesn't let you change to certain skins. You can go through all the default skins that appear- You can switch from an old man to a skinhead, black person, etc. But with some of them you don't get to choose the variations of skins. You can't select the old man model and make him bearded anymore, for example. Look through the skin changer, it's broken.

**Comment by LaCreepis** [comment]
Same issue as https://github.com/syl0r/Perpheads-Issues/issues/372
