### ISSUE TITLE
Eating fish looks weird

### ISSUE THREAD

**Issue by LaCreepis** [syl0r/Perpheads-Issues#387]
As of the Halloween update you can now see the food that people eat. Fish hasn't really been adjusted and shows up at your feet when you eat it but I really don't know how you could eat a whole fish in 3 seconds so it would be rather weird to properly set up an animation for this but oh well
![ss 2016-10-30 at 12 37 05](https://cloud.githubusercontent.com/assets/14893257/19836339/a4822e72-9e9d-11e6-821f-8660033cd303.png)

**Comment by StephenPuffs** [comment]
This should be fixed.  If you still have issues, please ensure you have the latest content.
