### ISSUE TITLE
Ford GT 05 exit position minor bug

### ISSUE THREAD

**Issue by Creepis** [syl0r/Perpheads-Issues#39]
Decided to make a whole new issue post out of this, as it would get more attention than simply commenting on an existing issue post.You simply get suck for 2 seconds or so when exiting the Ford GT 05 on even terrain, you get unstuck faster sometimes when you park and exit on uneven terrain.Really minor thing, but it can really screw you over sometimes when you have to make a quick escape.I will probably update this with more cars when I can find the exact same problem.

**Comment by StephenPuffs** [comment]
Thank you for this report, far as I know, there is no topic that has all the different vehicles in which this happens.  However if more people report such problems, the faster they'll be solved.  As for this one, it should be done and will be included tomorrow.
