### ISSUE TITLE
Crouching with a rifle in passive stance

### ISSUE THREAD

**Issue by LaCreepis** [syl0r/Perpheads-Issues#391]
Crouching with a rifle in passive stance  causes you to use an animation where your hitbox is shifted downwards but your model looks like it's standing up. Can lead to abuse in some ways and also makes it look weird in a specific spot if you'd ever hide. Going into attack stance while crouching fixes this issue. Kind of reminds me of a Quantum Crouch in TF 2 https://www.youtube.com/watch?v=Jf-MxemmQpY (This is an Engine problem, not sure if this would be replicable in Garry's Mod)
Here you can see Bollas standing on my head while I am crouched
![ss 2016-11-03 at 10 58 56](https://cloud.githubusercontent.com/assets/14893257/19986994/27829ae0-a219-11e6-817c-7aa913abb729.png)
And here is the specific spot I meant
![ss 2016-11-03 at 10 54 32](https://cloud.githubusercontent.com/assets/14893257/19986956/059070d8-a219-11e6-9f93-4a66fb3f6b43.png)
![ss 2016-11-03 at 10 57 11](https://cloud.githubusercontent.com/assets/14893257/19986958/069a2c58-a219-11e6-8ee4-df2da951e944.png)

**Comment by syl0r** [comment]
fixed
