### ISSUE TITLE
Ferrari Enzo trunk bug?

### ISSUE THREAD

**Issue by JarredInator** [syl0r/Perpheads-Issues#392]
So yeah I can't fit in any type of gun in my Enzo's trunk. It says max weight 7 yet guns with a 3 kg weight can't fit in. I can however fit small weight objects like bandages in every slot.

Idk man Creepis told me to put it here.

STEAM_0:1:42883693

**Comment by JDaymon** [comment]
Could you upload evidence of this? I haven't had any issues with my Enzo
