### ISSUE TITLE
Random vehicle script error

### ISSUE THREAD

**Issue by magemagicc** [syl0r/Perpheads-Issues#396]
Random occurrence, I get it at least once or twice a day but don't know what causes it because it probably happens across the map somewhere.

Image: https://puu.sh/sjpqm/ed4be62aaa.png
The actual script error

```
[ERROR] gamemodes/perp/gamemode/modules/materials/sh_vehicles.lua:4: bad argument #1 to 'pairs' (table expected, got no value)
 1. pairs - [C]:-1
  2. GetInteriorMaterial - gamemodes/perp/gamemode/modules/materials/sh_vehicles.lua:4
   3. UpdateMaterial - gamemodes/perp/gamemode/modules/materials/cl_vehicles.lua:53
    4. UpdateVehicleMaterial - gamemodes/perp/gamemode/modules/materials/cl_vehicles.lua:100
	 5. unknown - gamemodes/perp/gamemode/modules/materials/cl_vehicles.lua:122
Timer Failed! [Simple](@gamemodes/perp/gamemode/modules/materials/cl_vehicles.lua (line121)]	 
```

**Comment by LaCreepis** [comment]
Might be an error for a specific car, which one do you usually drive? I remember receiving this script error before.

**Comment by PHSneaky** [comment]
UpdateMaterial - gamemodes/perp/gamemode/modules/materials/cl_heciles.lua:53
Spelling error?

**Comment by magemagicc** [comment]
Audi S5, however it happened even when not using my car and just walking around. 

Oh and thanks sneaky :P fixed.

**Comment by syl0r** [comment]
fixed
