### ISSUE TITLE
Spawn game freeze and/or lag

### ISSUE THREAD

**Issue by BrewsterTKoopa** [syl0r/Perpheads-Issues#399]
I've been coming to perpheads RP for over a year now,i love this server and thats coming from a guy who solely uses single player 90%(not counting P2P btw) and i got this weird glitch,upon spawning in the server

-i cannot move from my position at all but i can rotate and attempting to move won't do anything(not controls based).
-game freezes for a whole minute like downloading a addon in the server then it unfreezes for about 2-4 seconds.
-i only get it when more then 30 or 40 people join in,a number of fewer players made me allowed to play it up until i started to lag AF.
I didn't have this issue before and i don't know when it started so i'm stumped,anyone got any ideas?

**Comment by LaCreepis** [comment]
Remove your demos, the demo folder can be found within your Garry's Mod installation directory.

If you're loading in make sure that you do not move, at all. Don't do any commands or do not even look around. This is how it was back in the day when everyone was loading in and it took around a minute or so to complete when you could finally move.

**Comment by BrewsterTKoopa** [comment]
tried them all,still nothing it still lags even also after getting rid of a ton of my addons. it

**Comment by syl0r** [comment]
This isn't really a bug, you should ask for support on the forums.
