### ISSUE TITLE
Died instantly while getting out of the car.

### ISSUE THREAD

**Issue by Ignas237** [syl0r/Perpheads-Issues#400]
I was driving my lambo gallardo and I wrecked it at like 20mph. The paint was wrecked and stuff and it automatically turned on blinkers. Usually when this happens you most of the time die. But I didn't. I survived and tried to start the engine. After 5 minutes of trying to start the engine I failed. Then I stepped out of the car and instantly died. Noone ran me over, noone was behind me either.

**Comment by syl0r** [comment]
This might just be a source physics glitch.
