### ISSUE TITLE
Some Items are stuck in my storage, Maybe a bug. Please help me get them out

### ISSUE THREAD

**Issue by DrewLumsden** [syl0r/Perpheads-Issues#402]
Ive been trying for hours to get certain items out of my storage but they wont budge, it could be a bug. if u need a screenshot just ask and I can supply 
 Thanks

**Comment by JDaymon** [comment]
Could you supply a screenshot with these items?

**Comment by DrewLumsden** [comment]
Its ok it was a bug, the items have gone when I reconnected, sorry for the inconvence
