### ISSUE TITLE
Able to drive vehicle while having a ticket.

### ISSUE THREAD

**Issue by LEWIS088** [syl0r/Perpheads-Issues#405]
I'm able to still drive my vehicle when I have a traffic ticket, This was caused by leaving the engine on.

**Comment by lelios1** [comment]
Having a ticket basically doesn't allow you to press R on the vehicle, wether that is to start or close the engine.

**Comment by syl0r** [comment]
That's always been the case. This might get changed if tickets get reworked at some point in the future.
