### ISSUE TITLE
Using trunk while cuffed.

### ISSUE THREAD

**Issue by Envionic** [syl0r/Perpheads-Issues#408]
The thing is, is that this has been going on for half a year now, whenever you are cuffed and you've got a gun on you that'll probably be confiscated you can store your gun in your trunk without the cops knowing while you are cuffed.

Told this to Daymon one time while being arrested by him, and i myself never used this '' bug ''.

**Comment by syl0r** [comment]
I can't transfer items while being handcuffed. I can look into the trunk.
