### ISSUE TITLE
Swat has no access to the Police computer  

### ISSUE THREAD

**Issue by Tim-Meijer** [syl0r/Perpheads-Issues#410]
When I'm swat i do not have the access to check the police computer.

**Comment by JDaymon** [comment]
I believe this is intentional as SWAT at the moment isn't a unit that should have access to it

**Comment by Exnem** [comment]
I belive they should have access to the PC due to arrests and being able to be up-to-date with warrants. At the time I as a SWAT member have no clue who is warranted or what they look like.

**Comment by syl0r** [comment]
fixed
