### ISSUE TITLE
Crafting level not going up.

### ISSUE THREAD

**Issue by MatthewSchmonithan** [syl0r/Perpheads-Issues#412]
Hello. I my name is Kodak Black / IGN: Matthew Schmonithan, I have spent over 50,000 dollars crafting over  25 molotovs, 50 STIM Packs, and 20 metal detectors for what? My crafting level didn't even go up one bit. I am NOT trying to boost my firearms. I AM trying to boost the crafting level itself. It just isn't going up. I can provide proof (demos) if necessary. I probably wont check this page often. So if someone comes up with an answer/explanation can you message me or leave a post on my wall at this link please?

https://perpheads.com/members/kodak-black.6077/

**Comment by magemagicc** [comment]
I'm unable to check currently, however if the item you are crafting does not need any crafting level to craft it, then you will not receive any XP from the item towards your crafting level.

Doesn't need the skill = won't give you XP to the skill not needed

**Comment by MatthewSchmonithan** [comment]
Yes I realised that. Thank you, but all the things I crafted required 3-4 crafting level.

**Comment by syl0r** [comment]
This shouldn't be a problem, it should always give you experience for crafting no matter what you are crafting.
