### ISSUE TITLE
Porsche Cayenne 2012 Bug & SG-550 Bug

### ISSUE THREAD

**Issue by Cudder** [syl0r/Perpheads-Issues#413]
For the SG-550 it comes built with a stock when you make it without requiring the components... As for the Porsche Cayenne 2012, I'm finding at high speeds the car's tires go under the map and then I skid uncontrollably and after that I get stuck, having to wait for it to reset.

Screenshot of the porsche bug: http://steamcommunity.com/sharedfiles/filedetails/?id=837710486

**Comment by syl0r** [comment]
Unfortunately that's just source engine being source
