### ISSUE TITLE
Firearms level decreased

### ISSUE THREAD

**Issue by arron10** [syl0r/Perpheads-Issues#418]
It seems my firearm level decreased from 95 to 94 after logging back in, Mr. Nice also had this issue but he dropped from 47 to 45.

Any idea on how / why this happend?

**Comment by arron10** [comment]
Also reconnected / rebooted my game a couple of times, this also did not help.

**Comment by arron10** [comment]
Another person that has the same issue http://prntscr.com/dyhb6u
And I know he was level 5 firearms yesterday since I helped him craft his first walter ppk

**Comment by orzel1244** [comment]
I had the problem too, from 35 firearms to 34, I have proof I had 35, because I crafted remington, and today I wasn't able to do it :/
