### ISSUE TITLE
TeamSpeak 3 (can't force move/subscribe to channels/edit channel max users)

### ISSUE THREAD

**Issue by ttjr123** [syl0r/Perpheads-Issues#419]
hello as you can see I can not edit the maximum users http://i.imgur.com/Du1KpyX.png and prior to this I could force move people in overriding the max limit.

furthermore I can no longer subscribe to my own channel, academy staff office, lobby or the "top secret bunker" personal channel due to no permissions.

my channel is stuck at 2 users max

the house of lords would really appreciate your help

**Comment by LaCreepis** [comment]
don't help his sweaty channel
