### ISSUE TITLE
Chairs don't despawn when the owner of them leaves the server

### ISSUE THREAD

**Issue by LaCreepis** [syl0r/Perpheads-Issues#421]
Title should be self explanatory, place down chair, leave, chairs won't go into storage after 5 minutes and just stay there.
![ss 2017-01-26 at 04 23 35](https://cloud.githubusercontent.com/assets/14893257/22336877/f49629e6-e3e3-11e6-9a0a-8e713b342cfe.jpg)

**Comment by syl0r** [comment]
fixed
