### ISSUE TITLE
Walther PPK

### ISSUE THREAD

**Issue by Exnem** [syl0r/Perpheads-Issues#423]
The walther ppk does not instantly kill on headshot as far as i can tell.

**Comment by LaCreepis** [comment]
Not a bug, the Walther PPK does minimal damage as it's bullets have only a small amount of gunpowder so it's travelling with a less of a force and impact but is the quitest gun in comparison to everything else. Words of XQ, also in terms of a balancing standpoint it is the cheapest gun to craft and would be quite powerful if it could kill instantly on headshots.
