### ISSUE TITLE
mrlewis broke perms

### ISSUE THREAD

**Issue by ttjr123** [syl0r/Perpheads-Issues#424]
anyone who is channel admin cannot subscribe to channels they are channel admin of

I cannot see the following:
- chief of department office
- academy staff office and sub-channels
- top secret bunker not allowed
- tylas house of lords
- police lounge 1

http://i.imgur.com/zzbA5Y5.png
http://i.imgur.com/j0UnlK0.png

**Comment by syl0r** [comment]
I hope this is fixed, if not shout at lewis
