### ISSUE TITLE
Minor issue with cup of joe image

### ISSUE THREAD

**Issue by magemagicc** [syl0r/Perpheads-Issues#426]
Simple as it sounds, not sure if it's accidental or just a bug but anyway the cup of joe icon in the inventory is too big causing the upper half of the image to not be displayed. Nothing major but just slightly annoying and would be nice if it would get fixed :D

http://i.imgur.com/lrM6tdU.png
and the icon when it's hovered over (center image) http://i.imgur.com/ASBt2bH.png

**Comment by LaCreepis** [comment]
literally unplayable

**Comment by syl0r** [comment]
fixed
