### ISSUE TITLE
Passive stance + Crouching bug

### ISSUE THREAD

**Issue by magemagicc** [syl0r/Perpheads-Issues#428]
Theres a really annoying bug that when you have an assault rifle in passive stance and you are crouching, your player model is actually still standing up so you are unable to hide with the gun in passive stance. This can at certain times be very significant. I guess it can still be in some ways fixed if you just have your gun in attack stance, but regardless it is quite an important glitch.

Easily reproducible, just get an assault rifle and place it in passive stance, crouch and anyone else will still see you standing up and is able to shoot you. 

Example: https://puu.sh/ubvTW/6ee0c4cb14.mp4

**Comment by LaCreepis** [comment]
https://github.com/syl0r/Perpheads-Issues/issues/391
