### ISSUE TITLE
New fire extinguisher

### ISSUE THREAD

**Issue by magemagicc** [syl0r/Perpheads-Issues#429]
Currently the new fire extinguisher goes below 0 and hits the minuses if you continue to use it, not sure if it still allows you to extinguish fires because it stops spraying so someone else may have to test that.

Simply reproduced on the live server: Get a fire extinguisher -> Use it up until it gets to 0 -> Use it again and you start going into the minuses.

Image: https://puu.sh/udck0/fc1996c8a4.png

Might not be significant at all idk.

**Comment by LaCreepis** [comment]
I have a "infinite" fire extinguisher from ages ago that does the same. Fumes don't come out but it still damages people and extinguishes fires, I screwed around with it for so long that it has almost reached the -10,000 units mark. Yes, it's abusable.

**Comment by syl0r** [comment]
fixed
