### ISSUE TITLE
Mercedez-Benz E63 exit position minor bug

### ISSUE THREAD

**Issue by Creepis** [syl0r/Perpheads-Issues#43]
Same as with my last issue post, on even terrain you seem to get stuck for several seconds when exiting.The same problem should occur on all the passenger seats.Have not tested this on uneven terrain yet.

Note:I will test out more car exit positions (might aswell call them 'locations'), as for now, this is all the ones that I have found with the problem, and I have noticed this problem with the car only by today now.Next issue post should be a small list of cars that have this issue, just to avoid spam.

**Comment by StephenPuffs** [comment]
Thanks for putting together a list if you do.  I know some cars are off, and other times it seems to only occasionally happen which is why I can't be bothered trying out hundreds of car seats to find out each one.

Anyhow, the E63 is now fixed, will apply the update in a few days probably.

**Comment by StephenPuffs** [comment]
Thanks for putting together a list if you do.  I know some cars are off, and other times it seems to only occasionally happen which is why I can't be bothered trying out hundreds of car seats to find out each one.

Anyhow, the E63 is now fixed, will apply the update in a few days probably.
