### ISSUE TITLE
SLS AMG issues

### ISSUE THREAD

**Issue by LaCreepis** [syl0r/Perpheads-Issues#435]
The SLS AMG has 2 issues
1: Smoke only comes out from 1 exhaust
![ss 2017-03-13 at 11 18 40](https://cloud.githubusercontent.com/assets/14893257/23877634/87373168-0843-11e7-8a0f-41ed61eb3d91.jpg)
2: The interior has been see trough since the Halloween update. This is definitely fixable.
![20170313231433_1](https://cloud.githubusercontent.com/assets/14893257/23877655/a018b4f4-0843-11e7-9de3-eaa2f083ee6b.jpg)

**Comment by LaCreepis** [comment]
oh for fuck sake

but pls

fix my beautiful car

**Comment by Bolli123** [comment]
Exhaust fixed, materials are being worked on
