### ISSUE TITLE
Had this error when accessing the bank npcs

### ISSUE THREAD

**Issue by TheDeadBanana** [syl0r/Perpheads-Issues#438]
[ERROR] gamemodes/perp/gamemode/modules/properties/npc_realtor.lua:19: Tried to use a NULL entity!
  1. GetClass - [C]:-1
   2. OnTalk - gamemodes/perp/gamemode/modules/properties/npc_realtor.lua:19
    3. func - gamemodes/perp/gamemode/modules/npcs/sh_npcs.lua:174
     4. unknown - lua/includes/extensions/net.lua:32

**Comment by syl0r** [comment]
That was probably just a one time thing without any bad consequences and can be ignored.
