### ISSUE TITLE
Parker Tunnel

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#44]
there's a part of the road in the Parker Tunnel where you can't walk in, but you still can drive trought with a car. The problem exist when you exit the car and you are in that part of the road: you are stuck next to your car and you can't move, and enter your car neighter.
If you are going to ask "and why should someone exit the car there? that would be breaking 3.21" well imagine if you are a roadcrew and you need to tow a car wich crashed there

**Comment by Creepis** [comment]
Basically, there is a huge (atleast that is what I presume) playerclip brush that prevents people from walking into a certain area, so this isn't really a bug, more like a feature from XQuality, put to prevent people from bugging out of the map? who knows, I myself cannot come up with an idea, why you would put a playerclip into the Parker Tunnel as some accidents can happen and you just get literally cockblocked, preventing you from accessing your vehicle.

**Comment by StephenPuffs** [comment]
As Creepis said, this was a mistake by Xquality which we noted several times before release, but then he never went back and fixed it so we're stuck with it until he gets off his butt and does V3.  Sorry to say but this is unfixable by code only a new version of the map could do it.
