### ISSUE TITLE
Bug about reviving bodies.

### ISSUE THREAD

**Issue by MCGSCEFFAAWHETJH55555** [syl0r/Perpheads-Issues#442]
I tried reviving some dead bodies, which were presumably finished off because the defib said it was too late to revive them. When I tried to dump the bodies in the ambulance, the remover stated that they were still alive and it wasn't too late. The warnings kept popping up whenever I did either of those things until the bodies disappeared.

**Comment by magemagicc** [comment]
#436 dupe

**Comment by syl0r** [comment]
fixed
