### ISSUE TITLE
Getting stuck in the RTU Porsche

### ISSUE THREAD

**Issue by Janice-PH** [syl0r/Perpheads-Issues#448]
There are times where you try to get out of the car and you get stuck on it so you can't move or do anything. This is really annoying if you need to chase a suspect on foot or just need to get out quickly

**Comment by ttjr123** [comment]
+support this is really winding me up

ive found that if you park at a 45 degree angle in relation to the map then youll get stuck, but if you park at 0, 90, 180 or 270 degrees you will be fine

**Comment by Janice-PH** [comment]
That is pretty useful if you have time for it but  when you are trying to get out the car quickly you won't always have time. So Hopefully this will be fixed
