### ISSUE TITLE
LT can view the number of sergeants on scoreboard, but not number of LTs, police, etc.

### ISSUE THREAD

**Issue by VPixels** [syl0r/Perpheads-Issues#45]
Not sure if intentional or not.

**Comment by StephenPuffs** [comment]
Well it was semi-intentional, I forgot they were unable to see other emergency services when adding sergeant.  I will ask around to see whether they should be added or sergeant removed from lieutenant's view.

**Comment by StephenPuffs** [comment]
Changed so that lieutenant can see all job numbers except for the number of secret service.  Mayor is still able to see all jobs.  Wait for release.
