### ISSUE TITLE
SWAT get armour on revive by medic

### ISSUE THREAD

**Issue by Xquality** [syl0r/Perpheads-Issues#453]
SWAT get magical armour on revive by medic. Gives them an advantage. Maybe add armour replenish to the SWAT truck trunk? Idea.

**Comment by slayerduck** [comment]
Why though? If a medic revived the scene should be secure and the SWAT can get a new set of armor at PD. If the SWAT is revived in the middle of a gunfight the medic is breaking 3.4

**Comment by Xquality** [comment]
The medic is not breaking 3.4 if he's in a secure location and the swat officer was dragged to him. And yes, the swat should get a new armour from the PD, not on revive; it's a bug.

**Comment by syl0r** [comment]
fixed
