### ISSUE TITLE
Unconscious state needs improving

### ISSUE THREAD

**Issue by Xquality** [syl0r/Perpheads-Issues#455]
Grenade: Anyone within 2-3 meters should get a black screen immediately upon impact from the grenade (no way to revive).
Guns: Right now, your unconscious state has a timer varying on the type of caliber you were shot with and which body part. Being shot in the head/body should be much more punishing than it currently is. A cop who get riddled with bullets shouldn't be alive much longer than 30 seconds (giving the medics almost no time to combat revive, which is good).

**Comment by syl0r** [comment]
not a bug
