### ISSUE TITLE
Body's dissapearing right after respawn

### ISSUE THREAD

**Issue by slayerduck** [syl0r/Perpheads-Issues#456]
Right now body's are still disappearing right after then 5 min mark when a person respawned. This has been going on for a month or so. You said in game this is after 15 min or when a person dies again but this is not the case.

**Comment by Xquality** [comment]
They actually despawn after 15 minutes. If the same person dies again, his old body is removed and a new one placed.

**Comment by slayerduck** [comment]
It should be, but its not. Body's disappear at exactly 5 min. I can reproduce it anytime.

**Comment by Xquality** [comment]
This is though, I tested it on James, and he stayed alive for the entire time after making his body. It stayed for 15 minutes and then disappeared. Stop writing bullshit you don't know shit about, thank you.

**Comment by slayerduck** [comment]
Its not, no need to be all angry about it. Here is footage i got from just now. Exactly 5 min: https://youtu.be/eeMTApP3Z_k

**Comment by jimmythehamster** [comment]
This is definitely still happening. It's gamebreaking for medics and cops.

**Comment by syl0r** [comment]
pretty sure it's fixed
