### ISSUE TITLE
Weapon Components do not show up in police searches.

### ISSUE THREAD

**Issue by jimmythehamster** [syl0r/Perpheads-Issues#458]
Because you do not need to use a stove to put a weapon together from it's components, you can carry all the components needed to craft a gun + mags and ammo. Then allow yourself to be searched by police who will see that you are clear of weapons and release you. You can then craft the firearm and gat the cop who is under the impression you are unarmed. It's rather abusey.

**Comment by syl0r** [comment]
This is not really a bug but will definitely be addressed in some time
