### ISSUE TITLE
City funds bugged?

### ISSUE THREAD

**Issue by maxh13** [syl0r/Perpheads-Issues#46]
Basically last 2 days it has been impossible to be a good mayor you just have to put insane taxes to prevent the cityfunds from going down. Here it says im supposed to make 700 dollars but im still losing money very quickly 
http://steamcommunity.com/sharedfiles/filedetails/?id=383348297

edit : after i ran out all the sudden i had 69k city funds

**Comment by StephenPuffs** [comment]
Nowhere does it say you would make $700, yes your projected income is higher than your projected expenses, but they are simply that projections.  Chances are there were more people in jobs than you set the city to have, causing your expenses to be higher than you thought.  In which case you should've had a discussion about it with that person or let the lieutenant know that some people need to be relieved from their position as the city couldn't afford it.  I don't know what you had the government pay at, but I would guess fairly high as well.  High pay is good for employed people, however it will drain your city funds fast if you don't balance it by other means.

Essentially, as mayor you need to look at the whole picture of what is costing the city a lot of money and how you can best go about solving it.  I don't see where the "insane taxes" part comes in, yes some people may consider them high, but that's when you have a citywide meeting and explain to them the current status and you're doing everything you can.

**Comment by maxh13** [comment]
Okay so there were no jobs that had more people in them nor were there a lot more police cars etc.
The city just kept losing money with these taxes and payment ( usually when I'm mayor I set it up like this only with a bit lower taxes and that works 9/10 if not I raise the taxes ) 8 cops - 2medics -1FF and in this case even all pay on just 100 dollars even with this I ran our of city funds in no time. However after I ran out ( the first time I got the city does not have enough fund to pay you I got almost $70000 city funds out of nowhere.

**Comment by StephenPuffs** [comment]
Someone buying a car no doubt for your sudden increase of city funds all at once.  But my guess is several of those cops were actually premium members, who would have a paycheck of $175 instead so they require a fair amount of income to sustain.

**Comment by StephenPuffs** [comment]
From what budgets I've seen on the live server, city funds don't seem too impossible to come by.  So I am closing this.
