### ISSUE TITLE
M82 can't be sold with Cash Register

### ISSUE THREAD

**Issue by crimsonnugget** [syl0r/Perpheads-Issues#460]
You can drop an M82 next to a cash register and the label window will still pop up, but it won't be for sale. It doesn't show anything, not the title, not the price.

Can be picked up with E as if it were not for sale.

**Comment by Atomicwizard** [comment]
It's just flashlights and spotlights they hide the title the weapon can not be picked up by other players without paying.

**Comment by crimsonnugget** [comment]
Then that should be fixed, right now I'm trying to sell m82s and I have to turn off everybody's spotlights so I don't lose customers.
