### ISSUE TITLE
Death himself doesn't collect

### ISSUE THREAD

**Issue by Xquality** [syl0r/Perpheads-Issues#463]
I've seen this multiple times. People fall out of a moving vehicle, get shot, or whatever happens... They end up having 0 HP yet still walking. In some extreme circumstances their screen is completely black and they can still walk around and talk. https://puu.sh/vhiQX/85bbd0d884.jpg

Edit: One punch seemed to knock the person out.

**Comment by slayerduck** [comment]
I can confirm, this happened to me once during a frontal collision with another car. We were both going at 60mph so it should have been a 120mph collision when combined. I got a gray screen saying i was unconscious. A medic heal fixed it, this event is extremely rare though and only happened once to me.

**Comment by HenkSpenk19** [comment]
Oh i have seen this bug now; will add: 

https://steamuserimages-a.akamaihd.net/ugc/82596991692798418/4700719F2BFDE2C74C9F44CB08E605A3046471ED/

**Comment by syl0r** [comment]
fixed
