### ISSUE TITLE
Benelli reloading bug, aswell as not taking any buckshot ammo when reloading

### ISSUE THREAD

**Issue by Creepis** [syl0r/Perpheads-Issues#47]
This problem should exist since the release of V2 or since the shotgun nerf.Anyways, the Benelli sometimes does not want to reload up to 8 shells.It stays sometimes stuck at 7 and you have to switch from Benelli to Keys/Fists and then back to the Benelli for it to work.And another thing I have noticed is, if you reload the Benelli like from 4 shells to 8 shells, it does not drain any Buckshot 00 ammo, this does not happen very often, but can lead to abuse.After reloading, the Benelli also seems to behave weirdly, sometimes you cannot shoot after reloading or view down your ironsights, a quick weapon switch from Benelli to Keys/Fists and then back to Benelli fixes this.

**Comment by BenStandish** [comment]
I've had this as well, especially with the unable to shoot or aim problem, the gun seems buggy.

**Comment by StephenPuffs** [comment]
This has nothing to do with the "shotgun fix" that fix was only related to the type of bullet it shot in actuality.  However it has been noted for quite some time that it has flaws, and I'm not surprised that it does.  All guns that load directly from the box have problems, and shotguns are especially bad.  So can try to fix it, but when I looked last time I couldn't find an easy reason for it.  Will continue to look though, thanks for the report anyhow.

**Comment by JDaymon** [comment]
Does this happen now? Never happens to me

**Comment by Minilarro** [comment]
This seems to happen with the remington aswell, as someone else adressed this in OOC after a raid, having spent to buckshots reloading.
