### ISSUE TITLE
Not cuffed animation while sitting in a car in first person.

### ISSUE THREAD

**Issue by HenkSpenk19** [syl0r/Perpheads-Issues#470]
When you go third person in a police car while sitting in the back cuffed you can see yourself cuffed (You can see your hand on your back), BUT if you go first person you can see your hands laying on your knees and not in cuffs.

Image's will be provided later

**Comment by syl0r** [comment]
That's unfortunately not easy to fix at all, and as it's not a priority at all won't be fixed
