### ISSUE TITLE
Transgender aliens

### ISSUE THREAD

**Issue by Xquality** [syl0r/Perpheads-Issues#472]
https://puu.sh/vsB8F/d569d57e77.png It appears that when you have a sex change, your skin and clothing doesn't switch to the correct gender, giving you a look which is best explained as 100% nightmare fuel.

**Comment by SteyLex** [comment]
HHAAHHAHAH

**Comment by LaCreepis** [comment]
@syl0r 's fetish everyone

**Comment by syl0r** [comment]
fixed :(
