### ISSUE TITLE
another totally gamebreaking issue

### ISSUE THREAD

**Issue by LaCreepis** [syl0r/Perpheads-Issues#473]
![ss 2017-04-23 at 05 37 04](https://cloud.githubusercontent.com/assets/14893257/25314858/c5bdb9b6-284b-11e7-8891-4d9f2a0a9c4e.jpg)
No lockpick will get past*

Please fix

**Comment by Exnem** [comment]
special needs, if this is the case i have a whole load of item descriptions that could be fixed

**Comment by LaCreepis** [comment]
pls do

**Comment by Weazelyes** [comment]
Its true

**Comment by syl0r** [comment]
fixed
