### ISSUE TITLE
phone messages are deleted when disconnect

### ISSUE THREAD

**Issue by speeeedy** [syl0r/Perpheads-Issues#474]
every time I disconnect from the server all messages on the phone are deleted

**Comment by LaCreepis** [comment]
Phone messages are stored client side I believe (just like your notes on the Notepad app). I reinstalled my Garry's Mod and they dissapeared as expected but I'm not sure what the cause for you would be. Check your HDD for any errors with Windows.

**Comment by syl0r** [comment]
This only happens if you delete something in your garry's mod folder every time.
