### ISSUE TITLE
Storage container only takes 50 

### ISSUE THREAD

**Issue by Weazelyes** [syl0r/Perpheads-Issues#475]
The current storage container we have on PerpHeads takes a total of 90kg. But is that really so?
I got a picture here and it only goes to 50 you can see the bar is fully red i got a picture here of some food in a chest that goes to 50 instead of 90     https://gyazo.com/796767aeeb6049d3f39e7cdd99e0370f

**Comment by Weazelyes** [comment]
I think this is very easy to fix so.

**Comment by syl0r** [comment]
Fixed
