### ISSUE TITLE
Porsche Wheels go inside ground 

### ISSUE THREAD

**Issue by Sdac2** [syl0r/Perpheads-Issues#478]
Sometimes in the forest the wheels of the Porsche Cayenne go inside the ground and cause the car to crash. it also happens over speedbumps

https://www.youtube.com/watch?v=rEl4wfGuybE
https://www.youtube.com/watch?v=EyOVcnSGA3Q
https://www.youtube.com/watch?v=H45LQ_M5fWI
https://www.youtube.com/watch?v=TGC6trAT3MQ
https://www.youtube.com/watch?v=-825OfmjxeI

**Comment by syl0r** [comment]
Is it the Cayenne S or Turbo 2012?

**Comment by Sdac2** [comment]
Cayenne Turbo 2012
