### ISSUE TITLE
Clipping issue under the Forest Highway

### ISSUE THREAD

**Issue by SgtJames** [syl0r/Perpheads-Issues#480]
As of right now you are able to **drive** a vehicle into [this](https://puu.sh/vHDBE/fd9fad97b6.jpg) area, however if you get out you end up being teleported onto the highway (Had a report about it, resulting in the players getting arrested). 

I've tried walking into that area but there is an invisible wall...

**Comment by syl0r** [comment]
can't really fix this, since this is a map issue

**Comment by jimmythehamster** [comment]
XQ fixed it in the next update
