### ISSUE TITLE
Nissan Silvia fuel glitch/bug

### ISSUE THREAD

**Issue by magemagicc** [syl0r/Perpheads-Issues#481]
![xd](https://puu.sh/vKOAH/14d0a63e88.png)

As you can probably see from the picture, I was able to drive my car despite the fuel being empty and the engine being turned off.

Some information to help:

When I claimed my car and got inside I expected the fuel to be empty and the car not to turn off because it was basically on the "E". 

The car still however turned on and the car hud lit up, and then the moment I accelerated, it turned the car hud lights off, yet I was still able to drive the car.

I stopped accelerating completely and waited a bit, however the car was still fully functioning, and no extra fuel was being drained (it was empty but I thought it might go negative)

Trying to press R to turn it back on again shows "This vehicle doesn't have any fuel" message, so the vehicle is obviously registered as having no actual fuel.

After driving to scrapyard to just take the photo, I refueled the car and it worked as normal.

I guess it's not _that_ serious, but somebody could abuse this and have unlimited fuel, depends if it still works after you get out the vehicle, which I am unsure of as I didn't test it at the time.

Car is double upgraded if that helps in any way.

**Comment by LaCreepis** [comment]
This sometimes happens if you're in a car and receive a ticket and somehow manage to  start the engine. The hud will also be black and I believe even consume no fuel like your case here. You sure you didn't have any tickets beforehand?

**Comment by magemagicc** [comment]
No ticket was present at the time.
