### ISSUE TITLE
Lag spikes bug.

### ISSUE THREAD

**Issue by MotiBachar** [syl0r/Perpheads-Issues#485]
Me and some other player on the community recieve lag spike every couple seconds for some reason. 
It gets really annoying and it makes hard to enjoy the role play and the game itself.
Please fix that as soon as possible

**Comment by LaCreepis** [comment]
I think I only noticed this happening on the live server. It was fine on academy with around 20 people but don't count on it. I have these spikes myself and they get worse if you go into a wall while you're in noclip.

**Comment by jimmythehamster** [comment]
I get them too, happened after the update. It sucks.

**Comment by Tim-Meijer** [comment]
Same for me

**Comment by LaCreepis** [comment]
fixed
