### ISSUE TITLE
Ford raptor

### ISSUE THREAD

**Issue by Exnem** [syl0r/Perpheads-Issues#486]
Flipping the ford raptor upside down and having the flatbed hit the ground after the roof hits, will cause it to merge with the ground and cause severe physics problems.

I found this out in single player as I obviously don't own a ford raptor.
I'm pretty sure this is a model issue however I'm just stating this here in case you are able to prevent this from happening, in the event it should happen.
http://puu.sh/w2j2c/dd36659e36.jpg

Ignoring the prop used as a "wall" to keep the vehicle in place while I took the picture, this happens even without doing so.

**Comment by HenkSpenk19** [comment]
I'm pretty sure its almost impossible to flip a vehicle in perpHeads

**Comment by syl0r** [comment]
Since the ford raptor is only being given to moderators anyways, I doubt it's gonna be a problem
