### ISSUE TITLE
Chevrolet Spark Hydraulics and Automatic drive

### ISSUE THREAD

**Issue by Synatec** [syl0r/Perpheads-Issues#487]
The Chevrolet Spark had hydraulics when jumping on it and when you are standing still on it, it will drive backwards as seen in this gif.
https://puu.sh/w3EL9/a249eb6ddd.gif

**Comment by LaCreepis** [comment]
sell the car to fix this issue

**Comment by Synatec** [comment]
Found another issue with the Spark

It can drive in the pond at city hall, amazing.
I wouldn't even mind if you don't fix this this is fucking hilarious

**Comment by Exnem** [comment]
That last one is fantastically not a bug, infact the water doesn't reach the engine block so I'm pretty sure it shouldn't drown.
