### ISSUE TITLE
can drop weapon while in cuffs

### ISSUE THREAD

**Issue by ShadowTyler** [syl0r/Perpheads-Issues#488]
Hello i just found this bug and if u was in cuffs and you have weapon on you and you don't want it got confiscated you can just go to any place no one can see the gun and type ./act surrender and the gun will fell down and you can now drop your gun while in cuffs

**Comment by Synatec** [comment]
lmao this actually works, @syl0r where is the major tag!!!1!!11!

**Comment by syl0r** [comment]
fixed
