### ISSUE TITLE
Boats at docks invisible?

### ISSUE THREAD

**Issue by Atomicwizard** [syl0r/Perpheads-Issues#491]
So after the server problem on the 03/06/2017, I rejoined and noticed some of the boats were gone, 2 of them. The next day I came on and went back and tried jumping on them and noticed they were still there as a physical prop just invisible. also when you stand on them to makes your screen shake up and down.
as  you can see in this photo, https://i.gyazo.com/9e47efda6db3533047c151a021cc33f0.png Gary is floating in the air.

**Comment by LaCreepis** [comment]
One of the boats is spawned in by the map, the rest are by code I believe. Not sure why they'd turn invisible after the sever crash and still persist.
