### ISSUE TITLE
Forum warnings

### ISSUE THREAD

**Issue by Exnem** [syl0r/Perpheads-Issues#496]
http://puu.sh/wdarc/d5d7bb0f74.png
Forum warnings don't display content for profile comments or comments in general, neither does it bring out what message you were warned for in general.

**Comment by Minilarro** [comment]
Doubt this is a bug. That is the standard forum warning template, made when a staff member issues a warning directly to your profile and not through a comment/reply. Sure that's not what happened? Otherwise the content of a reply should be added to the conversation.

**Comment by PHSneaky** [comment]
not a bug. Its when a staff member doesn't directly warn your post/thread but trough profile.
xenforo has default templates for that as you've probably noticed.
https://puu.sh/wdpbX/8246da9969.png
