### ISSUE TITLE
Car bombs

### ISSUE THREAD

**Issue by magemagicc** [syl0r/Perpheads-Issues#497]
Car bombs to not destroy cars now, only kill the people inside (from what I exprienced today). Some poor fella car bombed me in revenge fair and square and my car was not wrecked, it was in perfect condition. Car was a Tesla

**Comment by LaCreepis** [comment]
Check TinySlayer's post in Adrish's thread in the Staff Discussion section for more info on this.

**Comment by syl0r** [comment]
This is intended since otherwise car bombs would almost always fall under excessive negativity
