### ISSUE TITLE
Remington 870

### ISSUE THREAD

**Issue by Exnem** [syl0r/Perpheads-Issues#502]
For this bug to work, you must have shot once, and only once.

Aim down sights and keep holding right click
Hold R as well as right click and your shotgun reloads the single shell 90% faster.
It only works for the one missing shell, nothing more.

**Comment by syl0r** [comment]
This is only a slight visual glitch. It lets you shoot exactly as fast as when you do not hold down right click. In fact you can start ironsighting as soon as the shell is in the gun, even without holding down right click the entire time.
