### ISSUE TITLE
Doors

### ISSUE THREAD

**Issue by magemagicc** [syl0r/Perpheads-Issues#506]
Some doors on the map have small gaps that you can see through. There may be more but I only found some at the big subs houses and bazaar 
![Bazaar](https://puu.sh/wsXhm/28cad7fc65.png)
![Subs](https://puu.sh/wsXbS/c2a558bcb2.png)
![Subs](https://puu.sh/wsXc5/b3579ed480.png)
![Subs](https://puu.sh/wsXcs/36baca08a2.png)

**Comment by magemagicc** [comment]
another one 
![Regals balcony](https://puu.sh/wsXPM/b92f5c8dfa.png)

**Comment by LaCreepis** [comment]
I'm sure the actual frame of the door is a model to save brush faces with the current map limits. I don't know the process of putting actual models into the map but I'm sure it's a tedious or time consuming process and not worth fixing something small like this.
