### ISSUE TITLE
i am missing the GLASS CO / PARKER RAID WINNER TROPHY

### ISSUE THREAD

**Issue by ttjr123** [syl0r/Perpheads-Issues#507]
@MrLewis AND @Bolli123  can VERIFY this bug in which they cant give me this trophy

i will happily take elite member if this cant be fixed, sorry i am not able to provide much detail as to why this bug exists because i am not an admin and i cant see the admin panel pmsl

**Comment by coderiekelt** [comment]
This is clearly a case of PEBCAK. Nobody ever wins a Glasss Co / Parker Raid.
