### ISSUE TITLE
Stuck Inside Vehicles list.

### ISSUE THREAD

**Issue by JDaymon** [syl0r/Perpheads-Issues#51]
So yesterday I bought a Mini Cooper 1965, the exit position can sometimes get you stuck
Same goes with the Volvo 242 Turbo. 

Note; Keep this open and I will add more vehicles ASAP

Hello, before you add any vehicle's to this list there is a format I've created
>Vehicle:
>How do you get stuck?

**Comment by StephenPuffs** [comment]
These two are done, but I will leave this issue open for others (or yourself) to add to.

**Comment by JDaymon** [comment]
UPDATE: Range Rover 2012
Dodge Challanger 2012
RoadCrew Vehicle

**Comment by Millheimer** [comment]
Bugatti veyron SS. Usually when i get out of my car i get stuck for like 10 seconds. It need to be fixed because its pretty annoying when you are in a car chase and tries to run away when you get out of the car you instantly get stuck and because of that you get caught by the police.

**Comment by gottlieb94** [comment]
Mazda rx8 Usually when i get out of my car i get stuck for like 10 seconds.
Also when you are 4 players in the car and you all leave at the same time, you get stuck 2 persons on each side of the car

**Comment by JDaymon** [comment]
Beetle

**Comment by JDaymon** [comment]
Shelby GT500 got some small issues

**Comment by StephenPuffs** [comment]
All vehicles mentioned up to this point are changed (pending update)  if they continue to have issues, please either list again or message me on forums.  New cars must be listed here.

**Comment by Minilarro** [comment]
GMC Vandura gets stuck at pavements & some terrain at the left side of church. However I've felt a change lately so in case you fixed the exit position there's still just a few issues for it.

**Comment by JDaymon** [comment]
I got some problems with the BMW M5, got stuck several times last night on pavements.

**Comment by Janssoni** [comment]
The BMW 507 has another problems including with the exiting i sent you a PM about. It feels like you would be driving only with the rims even when tires arent popped. The speed slowers a lot when you go through a bump and if you are on the side of the bump the handling goes wierd. Also when i today went up the suburb ramp to highway, and let it fall down and tried to go back up it didnt go up at all. The car tires were half in the ground, even if they weren't popped.

**Comment by JDaymon** [comment]
@Janssoni that is a problem with the vehicle and not it's exit position, you can read more about this thread here; https://perpheads.com/threads/updating-vehicles.4119/

**Comment by JDaymon** [comment]
Vehicle: Dodge Charger 2012
How do you get stuck? You still get stuck at the PD.

**Comment by TEOTKU** [comment]
Toyota Supra 9 times out of 10. And maybe 7 times out of 10 when parked half on half off a pavement.

**Comment by Creepis** [comment]
Mercedes-Benz SL65 AMG, you get stuck very often and sometimes on ledges when exiting.
Ford Mustang GT, same problem as the SL65.

**Comment by MadlynBeasly** [comment]
No idea If you're still working on this, Nissan 370z

**Comment by JDaymon** [comment]
Ford Transit, BMW m5 (LT's vehicle i dunno what model it is)

**Comment by Minilarro** [comment]
Vehicle: Ford GT 05
How do you get stuck? 
Pretty much anywhere that the ground is not compeltely flat, mostly on any ledge, any ground that is not flat at all, happens quite alot in the woods.

**Comment by Creepis** [comment]
Bugatti 16.4 (Maybe the same problem with the SS) you almost get stuck every time you exit the vehicle, test it on uneven and a bit of uneven terrain.

**Comment by JDaymon** [comment]
Dodge Charger (Old one) I usually get stuck when I'm responding to emergencies as a police officer, also the BMW m5 (LT) you get stuck when you go on to a ledge. Already reported but why not bump this
