### ISSUE TITLE
V4 INVISIBLE HICKTOWN

### ISSUE THREAD

**Issue by Adikid** [syl0r/Perpheads-Issues#516]
One of the hicktowns is missing (the broken one) however the storage chest is still visible, for now I have just remover tooled it. Yet when it restarts it will still be there

https://puu.sh/wG1Vz/7f08e57eed.png

**Comment by Adikid** [comment]
You can also still buy it from the bank, and I'm assuming you can still search for it in the police database

**Comment by StephenPuffs** [comment]
Xquality made no mention that he removed this.  Fixed.
