### ISSUE TITLE
Viewing clothes

### ISSUE THREAD

**Issue by youseffa** [syl0r/Perpheads-Issues#517]
[ERROR] gamemodes/perp/entities/entities/ent_viewmodel_attachment/shared.lua:69: attempt to call method 'ViewModelChanged' (a nil value)
  1. v - gamemodes/perp/entities/entities/ent_viewmodel_attachment/shared.lua:69
   2. unknown - lua/includes/modules/hook.lua:84

**Comment by StephenPuffs** [comment]
At least won't give an error, can't guarantee the view will work every time.
