### ISSUE TITLE
Food bug

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#52]
![rp_paralake_city_v20063](https://cloud.githubusercontent.com/assets/10375578/6009030/62d1d08e-ab26-11e4-8a6a-0cd68280d48a.jpg)
ordering food by the delivery man you can hold a big amount af food passing the limit of 20

**Comment by StephenPuffs** [comment]
Already known, and considered to be bug abusing so I wouldn't recommend you get caught with more than the limit on you.  Probably will be addressing this with a future addition, as for now, may simply remove food from appearing in delivery.

**Comment by StephenPuffs** [comment]
Delivery no longer can send food, updated for 04.02.2015
