### ISSUE TITLE
Traffic light buttons floating away and then back again

### ISSUE THREAD

**Issue by Minilarro** [syl0r/Perpheads-Issues#521]
http://i.imgur.com/GzS5lhL.jpg
http://i.imgur.com/FwEVqsi.jpg

The buttons to activate the traffic lights closest to puffer market float slowly away for a while once activated, and then back again. Bit of an issue as the button closest to the business shops float into the highway meaning cars will crash into it on its way over and its way back to the box.

Only occurs when buttons are activated from what I have seen. Not sure if the button closest to puffer being activated triggers this, as I don't want to risk more people crashing.

**Comment by Exnem** [comment]
This is me crashing into the button responding to a call
https://puu.sh/wNloD/4d6f331c02.jpg
Fix this aids

**Comment by syl0r** [comment]
fixed by removing the button...
