### ISSUE TITLE
Chairs

### ISSUE THREAD

**Issue by ChrisAlAndrews** [syl0r/Perpheads-Issues#522]
Ingame report.

ALT+E on a chair, sits you down but as it picks up the chair your clothes remain and you just become a head. Seems to fix its self after a short while?

![b6ezneq](https://user-images.githubusercontent.com/6288439/28113451-76cbd440-66f4-11e7-8605-4cf4e6d603ae.png)
![jalfw0j](https://user-images.githubusercontent.com/6288439/28113452-7803bca6-66f4-11e7-9bcf-a5da24c4217b.png)

**Comment by PHSneaky** [comment]
believe this is always fixed when you do an animation, such as eating or drinking.

**Comment by syl0r** [comment]
fixed
