### ISSUE TITLE
Mayor can't demote people via mayoral menu.

### ISSUE THREAD

**Issue by AyJay0** [syl0r/Perpheads-Issues#526]
[ERROR] gamemodes/perp/gamemode/modules/guicore/menus/mayor_tab.lua:134: attempt to index field 'AdditionalComments_W' (a nil value)
  1. DoClick - gamemodes/perp/gamemode/modules/guicore/menus/mayor_tab.lua:134
   2. unknown - lua/vgui/dlabel.lua:232

**Comment by syl0r** [comment]
fixed
