### ISSUE TITLE
Infinite fuel

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#53]
this is a known problem on the server and i had it aroung the last of December and then no more so i thought it had been fixed, but some days ago it happened again.
Sometimes, i don't know how, the display of fuel just stay and doen't move. It happend with all kind of cars: from privates to governaments

**Comment by StephenPuffs** [comment]
Yes it has been addressed already; unfortunately I made the change in the wrong area so having to wait til some more things get done before i can successfully patch it.
