### ISSUE TITLE
I have VIP but can't buy VIP clothes

### ISSUE THREAD

**Issue by JBirksy** [syl0r/Perpheads-Issues#534]
So I thought suits were disabled now but my mates told me they aren't so I took a screen shot of me having VIP and me not being able to buy the long sleeve clothes thing.

http://steamcommunity.com/sharedfiles/filedetails/?id=1098065976
http://steamcommunity.com/sharedfiles/filedetails/?id=1098065890

**Comment by syl0r** [comment]
You can't have a watch and something with sleeves.
Remove the watch and it will work.
