### ISSUE TITLE
Office windows only wallbangable from outside (Caliber or map related issue)

### ISSUE THREAD

**Issue by LaCreepis** [syl0r/Perpheads-Issues#535]
https://www.youtube.com/watch?v=1bp-LuRjQXg
Footage was from academy server, AK47 cannot shoot out the windows which clearly should be able to but others outside the office can shoot inside. Either it's a caliber issue or map issue.

"Why is that gun not going trough the glass" sorry for bad London

**Comment by syl0r** [comment]
It's all angles. If you shoot at the right angle you can shoot through the window, at a bad angle you can't.
