### ISSUE TITLE
Skills have been reset

### ISSUE THREAD

**Issue by virtualbanana** [syl0r/Perpheads-Issues#537]
When I joined the server at 4 am today I noticed that when driving I received lvl 2 from driving and was like wtf im not lvl 2 driving skill. When I looked at the skills I saw all my skills had been reset to lvl 1. Me thinking it was a glitch I went to sleep and after waking up and connecting the skills were still lvl 1 and the driving lvl 2. Can someone somehow restore my skills. Ingame name: Joe Guerrero and forum name: Huijaaja42.

**Comment by syl0r** [comment]
fixed
If you want your skills back message me on the forums
