### ISSUE TITLE
Can't enter the taxi

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#54]
So i was a  taxi driver and i after i had taken some passengers to the requested location someone other wanted to enter the taxi he paid 200$, i got them, but i couldn't enter, so i called a moderator and mannerwaffel came and succesfully entered, but the man sill couldn't enter... after some times we tried again and the bug was solved (this happened with more then 1 player) very weird :\

**Comment by StephenPuffs** [comment]
I saw this happen to one guy, Rutger and myself tried to help him, when we tried to use the taxi it worked fine for both of us, so I figured it was simply him doing something wrong.  Will look into it.

**Comment by Bamarin** [comment]
I thought the same at first, because it was only him and another one, while everyone else still could enter. But then after some time the man having the problem tried again and he succesfully enter. He told me he did nothing different so i think he knew how to do it

**Comment by StephenPuffs** [comment]
Strange... I don't see any reason that this would effect people for different reasons.  So hopefully someone figures out how to reproduce.  Will keep looking though.

**Comment by ieatyou** [comment]
@JDaymon I found out after. I really hope it gonna be a fix soon. i like the taxi job. :+1:

**Comment by StephenPuffs** [comment]
Ok hopefully it is fixed.  Although I'm unsure of why it would sometimes work and not others.  After next update if this continues please recreate this bug report.  (There are still other taxi improvements I wish to do at some point so important to get this sorted out at least).
