### ISSUE TITLE
3x headshots to the head to kill a TFU.

### ISSUE THREAD

**Issue by LeBlicky** [syl0r/Perpheads-Issues#544]
After doing some testing, it takes 3 shots with a rifle to kill a fully armoured TFU. If this could be fixed to one that would be great.

http://gph.is/2w9Rczw

Cheers,
Blicky

**Comment by Daigestive** [comment]
Obviously its due to them still being fully armoured and only player models changed so far.

**Comment by StephenPuffs** [comment]
This was changed in the latest update.
