### ISSUE TITLE
Regals staircase burn your fucking eyes

### ISSUE THREAD

**Issue by LaCreepis** [syl0r/Perpheads-Issues#545]
![20170804222450_1](https://user-images.githubusercontent.com/14893257/29334625-52863db2-8208-11e7-9a70-1eb81b833d04.jpg)
I'm sure it's map related anyways (lights on every corner of the staircase wtf xq) but if it's possible to change the brightness of specific light entities via code then it would be good to fix this. This is during day time and clear weather, don't remember exactly anymore.

**Comment by StephenPuffs** [comment]
This is an issue with the lighting of the map itself.  Some lighting has decent fall off settings which allows day/night cycle to work alright with it, other ones like this do not.  Unfortunately there is very little that can effectively be done in post with how the Source engine handles lighting.
