### ISSUE TITLE
Cars

### ISSUE THREAD

**Issue by Ferasalzarah** [syl0r/Perpheads-Issues#546]
When someone leaves his car sometime he/she gets stuck on the car while there is a shoot out then gets shot instantly plz fix it ASAP this is stuped

**Comment by LaCreepis** [comment]
https://www.youtube.com/watch?v=glgmv8L8Md0
Was stuck for a good 10 seconds, had to help myself out however the other guy didn't have much tools to help himself out. Depends where you get out aswell, make sure your car completly stops before exiting to avoid this issue

**Comment by syl0r** [comment]
fixd
