### ISSUE TITLE
Phone getting stuck in specific apps (Emergency+Call app)

### ISSUE THREAD

**Issue by Creepis** [syl0r/Perpheads-Issues#55]
First of all, thank you to JDaymon for finding how to reproduce this bug.Since he told me that he wanted to report this bug here (or to a server Dev. directly via Steam) and did not do it as far as I know, I decided to do report this problem on my own.

The issue or just what this bug is doing to our phone:
Some people have reported the issue of their phone being stuck in a their emergency app or in the call app.Dropping, pressing the back button or buying a new phone obviously does not fixes this problem, only a reconnect can fix this.

Now on how to reproduce this:
Simply, User1 calls User 2 (in this example User1 was me, Creepis and User 2 was JDaymon), User2 accepts the phone call and hangs up.User 1 should NOT get up his phone or go back to the home screen after calling.User2 now should call User1, User1 accepts and hangs up.User1 can now no longer exit back to the home screen and is stuck in the phone app.I believe the same problem seems to be with the emergency app, after submitting an emergency report and someone calls you afterwards without pulling out your phone or going back to the home screen of the phone, it gets stuck in the emergency app screen and you cannot go back to the home screen.Correct me if I am wrong, but I do believe the problem with the screen getting stuck in the Emergency app should be fixed as written in this other issue post https://github.com/syl0r/Perpheads-Issues/issues/3

**Comment by StephenPuffs** [comment]
Is this still happening? We attempted a patch on it the other day that should function without problem.

**Comment by Creepis** [comment]
It is fixed, my bad.
