### ISSUE TITLE
Head/brake and indicator lights issue

### ISSUE THREAD

**Issue by LaCreepis** [syl0r/Perpheads-Issues#550]
The head/brake lights and indicators no longer show up on your car when you press F (MOUSE1/MOUSE2) in your car after the update we had today. Others will be able to see them just fine but you don't see your own.

EDIT: So far only Sdac seemed to have the same issue as me but only with my car. Not sure what could be the cause for this or if it's just specific cars like my Shelby 1000 that have this issue.
![20170823154702_1](https://user-images.githubusercontent.com/14893257/29619223-d60629c8-881a-11e7-878b-0df2c1e03f77.jpg)
![20170823154703_1](https://user-images.githubusercontent.com/14893257/29619250-ebce286e-881a-11e7-9cbe-3c393d0188f1.jpg)

OOT: I'm bad at titles.

**Comment by Exnem** [comment]
This appears to be fixed.
