### ISSUE TITLE
Tooter

### ISSUE THREAD

**Issue by Exnem** [syl0r/Perpheads-Issues#565]
Display name change creates script errors.

[ERROR] gamemodes/perp/gamemode/modules/tooter/smartphone/settings.lua:36: Calling net.Start with unpooled message name! [http://goo.gl/qcx0y]
  1. Start - [C]:-1
   2. Callback - gamemodes/perp/gamemode/modules/tooter/smartphone/settings.lua:36
    3. DoClick - gamemodes/perp/gamemode/modules/tooter/smartphone/settings.lua:211
     4. unknown - gamemodes/perp/gamemode/modules/tooter/smartphone/tooterbutton.lua:27

**Comment by syl0r** [comment]
fixed
