### ISSUE TITLE
Guns don't have an extra bullet when loaded with a fresh mag

### ISSUE THREAD

**Issue by LaCreepis** [syl0r/Perpheads-Issues#566]
This issue has been there for ages but not sure why this hasn't been adressed yet but it's triggering the fuck out of me xd
![](https://puu.sh/xqxNb/73b35fb1e1.png)
If the gun (In this case the P226) is at 0 bullets, the gun should only have 13 bullets as described when reloaded with a magazine as it had no bullet already loaded into the gun from a previous magazine or if all the bullets had been fired from a previous magazine.
If the gun gets reloaded with a bullet already loaded in the chamber then it would effectively be 13+1 as described by the description, 13 bullets in the magazine and 1 already loaded in the gun/chamber.
If this is hard to implement/fix then don't bother doing this, I'm just throwing this out so it may get fixed. 
If you clear the gun/disarm it (In this case 13+1) by taking out the magazine in the Q menu then the extra bullet should just be discarded as you can see from the animation which is already implemented (Neat). 
![](https://puu.sh/xqyiH/7e5484a835.gif)
This should not be the case if you take the mag out of the gun that you just loaded with a bullet, take out the mag again you lose 1 bullet for your magazine. This would trigger the fuck out of people that use snipers as sniper ammo can be expensive. You do discard the bullet during the animation but it should go back into the magazine just for convenience.
I'm bad at explaining this but I hope you can understand my Kanacken words @syl0r 
And yes, this would benefit some weapons such as snipers. An extra bullet from an M82 or AS50 would make a difference.

Literally game breaking, please fix and I will re-install.

**Comment by StephenPuffs** [comment]
This has never been a feature and likely will not be for some time still.  Also, saying something is game breaking when it is not is a fast way to have an issue ignored/discarded.
