### ISSUE TITLE
Chairs.

### ISSUE THREAD

**Issue by JDaymon** [syl0r/Perpheads-Issues#57]
If you leave while having a chair put down as a prop it will dissapears from your character.

**Comment by Bamarin** [comment]
It didn't happened to me, but i may didn't undertand: you are saying that if you place a chair as a prop (left click) and then disconnect you will lose it? if so, it doesn't happends to me.

P.S. I would state another bug related to chairs instead. The third person view doen't fully work: i placed one inside suburbs6 and when i sat on it, it looked like i was under the house

**Comment by JDaymon** [comment]
Hm, I guess it happens sometimes then.

**Comment by StephenPuffs** [comment]
@JDaymon More information is required.
@Bamarin To be honest 3rd person in chairs should be removed.

**Comment by StephenPuffs** [comment]
@JDaymon More information is required.
@Bamarin To be honest 3rd person in chairs should be removed.

**Comment by StephenPuffs** [comment]
@JDaymon More information is required.
@Bamarin To be honest 3rd person in chairs should be removed.

**Comment by JDaymon** [comment]
@StephenPuffs I'm sorry, I forgot to put when it disappears. 

> John Daymon puts a chair down.
> John Daymon does not pick the chair up while in-game
> John Daymon disconnects with the prop still out
> John Daymon's chair is gone.

**Comment by Bamarin** [comment]
@StephenPuffs oh well fine then, also, you told me to write down a list about the benches wjere you get stuck when you stand up; should i make it here?

**Comment by StephenPuffs** [comment]
@Bamarin Might as well I suppose, I already know the benches outside of Fredy's on Sunset Blvd.  So you don't need to mention adding those.

**Comment by Bamarin** [comment]
i found the one next the hungurians restaurant(idk if i wrote it correctly) in the park over the stairs
also it would be nice to be able to sit on your own sofas and harmchairs

**Comment by StephenPuffs** [comment]
Not sure if I know where you mean @Bamarin everywhere around there has a seat already.  As for the others please review my post in this thread https://perpheads.com/threads/resting-to-regain-stamina.5519/

**Comment by SwiperFox** [comment]
I think Daymon is talking about the prop restore feature, when you disconnect with props down, they go back to storage, however chairs do not seem to do so.

**Comment by JDaymon** [comment]
@SwiperFox Thanks for clearing it out, this is basically what I meant.

**Comment by StephenPuffs** [comment]
Will look into this, although more of a @syl0r (Fredy) problem.

**Comment by Minilarro** [comment]
The office chair at the City hall Library makes you stuck in the desk infront of it upon exit.

(I saw that Bamarin was making a list and though I'd add this)

**Comment by StephenPuffs** [comment]
@Minilarro This chair is now fixed for next update, thanks for reporting it.
