### ISSUE TITLE
Bazaar Clip

### ISSUE THREAD

**Issue by JaniceMcG** [syl0r/Perpheads-Issues#570]
Players can use the bed to clip onto a bit in bazaar so they are practically floating

http://steamcommunity.com/sharedfiles/filedetails/?id=1127983808

**Comment by LaCreepis** [comment]
Where exactly do they place the beds?

**Comment by JaniceMcG** [comment]
I have seen it be done by the bollards but as far as I am aware it can be done anywhere in the center of bazaar

**Comment by LaCreepis** [comment]
Not possible to fix in the first place but it's against the rules obviously as you're abusing a bug and placing props in the public.

**Comment by StephenPuffs** [comment]
Not a game bug, just report if witnessed.  This is not allowed by in-game rules.
