### ISSUE TITLE
Mayor entry doesn't reset

### ISSUE THREAD

**Issue by smudgerPH** [syl0r/Perpheads-Issues#572]
When you run for mayor and you lose, you are still counted as running for mayor on the NPC menu meaning you can only be SS or retract your mayor bid. When you should also be able to change your name or create an org.

**Comment by smudgerPH** [comment]
You also cant retract a mayor bid while there is a mayor

**Comment by PHSneaky** [comment]
You're unable to retract when the mayor has been selected, meaning you have to go rejoin the server to be able to do a job
