### ISSUE TITLE
You cant hear radios when  operating an ATM

### ISSUE THREAD

**Issue by Mendoxd** [syl0r/Perpheads-Issues#573]
Not the biggest issue arround, and there aint much to it really... other than whats stated in the tittle.

**Comment by Exnem** [comment]
This happens because your view is placed somewhere else on the map, removing all sound surrounding you, and only using the sound in the scripted view. AFAIK

**Comment by LaCreepis** [comment]
Radios should work the same ways as phones though if I'm not mistaken. I was using the ATM while in the TeamSpeak app and could still hear everyone.

**Comment by StephenPuffs** [comment]
Issue already stated by @Exnem so no point in trying to get around this as the time spent in an ATM is generally < 30 seconds.
