### ISSUE TITLE
Mercedes 300 SEL bug

### ISSUE THREAD

**Issue by Weazeliscool** [syl0r/Perpheads-Issues#582]
![](https://i.gyazo.com/5ab945dd11971b81a4e5f226b7be8869.png)

Only 4/8 headlights work!!!!!!!!!!

This is very big scam plz fix.

----

I'd love it if you can fix the headlights for this car, i paid 750k for it and i'd love to see it actually work. <3

**Comment by StephenPuffs** [comment]
Impractical as those are part of a bodygroup which could mean any number of changes for any given car.  Additionally this is not a bug or issue.
