### ISSUE TITLE
Crafting doesn't require you to click all required materials

### ISSUE THREAD

**Issue by Drafaxo** [syl0r/Perpheads-Issues#583]
https://www.youtube.com/watch?v=vXXnZ5yQZRA

When crafting sniper ammo, I noticed it didn't require me to click all the necessary materials. Only 5/6 gunpowder, 4/5 brass bulk, one of the refined metal wasn't used, and neither was the bullet casing. Not sure if this happens with other items

I attempted crafting sniper ammo again after I rejoined the server, and while it randomized the sequence, it still didn't make me click all necessary materials.

NOTE: It still uses all the materials, just doesn't make you click them when crafting.

**Comment by LaCreepis** [comment]
Already a reported issue https://github.com/syl0r/Perpheads-Issues/issues/579

**Comment by StephenPuffs** [comment]
Things like this
