### ISSUE TITLE
PM invite

### ISSUE THREAD

**Issue by Tim-Meijer** [syl0r/Perpheads-Issues#586]
The PM invite button on the forms when you have already created your PM is not working.

**Comment by LaCreepis** [comment]
If you're the PM creator or if you're staff you can put a /invite after the URL to invite more forum users to your conversation

**Comment by PHSneaky** [comment]
which button exactly? https://i.imgur.com/ldBJakk.png this works fine for me.

**Comment by JDaymon** [comment]
This is going to be closed as it isn't a  bug
