### ISSUE TITLE
Flashbangs and grenades are bugged.

### ISSUE THREAD

**Issue by BenStandish** [syl0r/Perpheads-Issues#60]
When I realised this, I thought it was just you guys adding a timer to the flashbang, but when I cooked a grenade for four ticks yesterday, after throwing it, it took 5 seconds after throwing it to explode, same with flashbangs, they have a delay.

**Comment by StephenPuffs** [comment]
I have severely reduced the time it takes for flashbangs for the next update while I work on changing frags to use a better cooking system that should result in less lag potential and better grenade realism.
