### ISSUE TITLE
Taxi Job

### ISSUE THREAD

**Issue by ieatyou** [syl0r/Perpheads-Issues#61]
After some time (0-1) jobs, the next passenger is not able to enter the car. 

We tryed like 7 times, also with a other player.
Tryed to respawn the taxi.

The problems was there also last time i played the job, but think it was noting, but now i thing its a bug

**Comment by JDaymon** [comment]
This has already been reported:https://github.com/syl0r/Perpheads-Issues/issues/54

**Comment by StephenPuffs** [comment]
Check the issue list before posting.
