### ISSUE TITLE
Jail cells

### ISSUE THREAD

**Issue by AVAST4894** [syl0r/Perpheads-Issues#62]
Well, basically i was breaking Bilbo and Ian out of jail i pointed my pistol at the person down at jail cells. Anyways.. What happened was that the only thing that opened was the main jail door and not the other ones... I tried several Times by gunpointing again and trying to lockpick. Nothing worked.... Please fix this..

**Comment by JDaymon** [comment]
As far as I know you're supposed to speak to the NPC ( i never break people out)

**Comment by AVAST4894** [comment]
I did and IT only opened the main cell door
