### ISSUE TITLE
Jeep Wrangler popped tires

### ISSUE THREAD

**Issue by Drafaxo** [syl0r/Perpheads-Issues#63]
I am not entirely sure if this has been fixed yet, as I've already sold my Jeep a long time ago.

Anyway, the Jeep Wrangler, when the tires are popped, very easily tips over. Do basically any turn at 30 MPH or above, and it tips.

I have a video making fun of the whole thing, though also shows it: https://www.youtube.com/watch?v=fFLMtgHQtvc

**Comment by JDaymon** [comment]
We have a thread on the forums for vehicles https://perpheads.com/threads/updating-vehicles.4119/

**Comment by StephenPuffs** [comment]
As noted, there is a thread on the forums for things like this, and it shows I have not done this one yet, but sounds higher priority than some others.  Will do soon.
