### ISSUE TITLE
Problem to get into a car after take anything from the ground

### ISSUE THREAD

**Issue by Faker1** [syl0r/Perpheads-Issues#64]
Hello Support team, 

my problem is, that i cant go into a car after taken things from the ground. After reconnect, i can go into the car :D do you have any Ideas what i can do?

ty for helping

**Comment by JDaymon** [comment]
I had this problem 1 week ago, all I did was using ALT+E. Probably going to help you! If not just hit me up! 
-Daymon

**Comment by StephenPuffs** [comment]
I don't understand what either of you mean, taking an item should have no effect on your ability to enter a vehicle.  Be sure you have keys/unarmed when trying to enter, not fists.
