### ISSUE TITLE
GMC vendura bug

### ISSUE THREAD

**Issue by AVAST4894** [syl0r/Perpheads-Issues#65]
When wheels are bråken and you drive GMC its actually easier to handle and IT drives faster then IT does when its fixed.

**Comment by JDaymon** [comment]
This is not true at all. The vehicle is slow and quite hard to drive. I've driven the GMC before christmas and now: no bugs

**Comment by StephenPuffs** [comment]
Reported as solved, and considering I remember doing this vehicle I don't view it as a problem.
