### ISSUE TITLE
Gun Clip Bug

### ISSUE THREAD

**Issue by Cudder** [syl0r/Perpheads-Issues#66]
There's an issue in game where if you have multiple clips and you cycle through them pressing "r", it shows that your gun will have 0 bullets in it and then when you left click it will fire off rounds from a full clip. Very aggrovating issue because sometimes that will happen to me in a raid or defending my house, and other times I will be trying to raid someone and it says I have 7 rounds, but I really have 0 rounds and the 7 rounds are in my spare clip(s) saying that there are 0 rounds in them.. Please fix this asap I'm sure I am not the only one affected by it

**Comment by JDaymon** [comment]
This happens to me sometimes but only when I do not let it finish the animation.
