### ISSUE TITLE
Bobby Pin Bug

### ISSUE THREAD

**Issue by Cudder** [syl0r/Perpheads-Issues#67]
Adding on, another issue the server has is a bobby pin bug.. You will have say x amount of bobbies, and then when you equip one sometimes the number will decrease by one, other times the number won't decrease at all. It's not as major as the gun clip bug but if you could patch this little issue that would be nice

**Comment by StephenPuffs** [comment]
I don't ever have anything like this.  No matter how many times I unequip and reequip one it always shows how many I have properly.
