### ISSUE TITLE
First Paint Job

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#68]
Basically after buying a new car you can't paint it: it should be free, but it says you can't afford it.
As it is now the only way to fix this bug is rejoining the server

**Comment by StephenPuffs** [comment]
It's a known bug, I'll look into correcting it for next weekend.

**Comment by StephenPuffs** [comment]
Should now be fixed (pending update).  I am tempted to change a lot of cars default colors as a lot of them are terrible, but I will make a poll when I actually feel like doing that.
