### ISSUE TITLE
Metal detectors don't always work.

### ISSUE THREAD

**Issue by BenStandish** [syl0r/Perpheads-Issues#69]
Title.

**Comment by StephenPuffs** [comment]
More explanation is needed here... They don't work when?  Every time I've been near one with a weapon it works fine.

**Comment by BenStandish** [comment]
Well, I've been through a few metal detectors recently and they simply do not go off (I have a weapon obviously) and a few other people will say how it isn't working ATM, it may be due to server lag I have no clue.

**Comment by Creepis** [comment]
It's happening when the metal detectors have been placed down for quite some time, server lag could be the issue.

**Comment by JDaymon** [comment]
@Creepis I've had the same problem however when I just put it down so I guess there's other ways to reproduce it

**Comment by StephenPuffs** [comment]
I really don't know, nothing should stop it from functioning at any point.  I can see maybe how server lag has some impact on its performance, but it still should function properly at any given time.

**Comment by StephenPuffs** [comment]
Well I have now seen this happen while on the live server, and after sitting under it, eventually it does trigger, but slow to say the least.  However I can only imagine this is from server lag.  I maybe could get around this, but I don't know how buggy it may be either.  Worth a try I guess.

**Comment by StephenPuffs** [comment]
Well I have now seen this happen while on the live server, and after sitting under it, eventually it does trigger, but slow to say the least.  However I can only imagine this is from server lag.  I maybe could get around this, but I don't know how buggy it may be either.  Worth a try I guess.

**Comment by HyDroKiller** [comment]
Something i found was if the metal detector is on the floor it doesn't work. You have to put the metal detector slightly off the floor for it to work.

**Comment by StephenPuffs** [comment]
This was updated in last update, so should always work now.
