### ISSUE TITLE
Can only see default player Sweater

### ISSUE THREAD

**Issue by satoshiaaron** [syl0r/Perpheads-Issues#70]
For some reason I can only see the default clothes on players. I thing this is more of a personal issue but it is still something that could be effecting more than one person.

**Comment by StephenPuffs** [comment]
Provide a screenshot of what you mean, I don't know if I understand what it is you're seeing.

**Comment by syl0r** [comment]
This probably means that your content contains older versions of our model, so reinstall the game or just empty your addons folder.
