### ISSUE TITLE
Monorail MINOR BUG.

### ISSUE THREAD

**Issue by AVAST4894** [syl0r/Perpheads-Issues#71]
The monorail almost kills people when you dont enter it. Video : https://www.youtube.com/watch?v=JjP5erSr3Ks&feature=youtu.be

**Comment by StephenPuffs** [comment]
There's nothing that can be done about this as 1) It is a map issue which would require Xquality to work on it which he's been hesitant to do anything more with it and 2) Even if he did functrains always turn to face the direction they travel, so when the train is set to go the other direction it has to automatically turn 180 degrees which unfortunately has the possibility to clip with a player knocking them around.
