### ISSUE TITLE
Phone not closing when dropped.

### ISSUE THREAD

**Issue by chrisadamson** [syl0r/Perpheads-Issues#74]
When a phone call is active and a user drops their phone, the phone call continues. I think the "active" animation also disappears but I can't remember off the top of my head. The reason that this is an issue is the fact that one could mug someone who is on the phone, forcing them to drop it however they could continue to ask for help. I found this when I was mugged by that lovely man Andii Millheimer

**Comment by StephenPuffs** [comment]
Known, and plan to correct soon.  I believe presently you are able to do the same thing if you have your flashlight on then drop your flashlight, it will remain on.  This will be addressed at the same time.

**Comment by StephenPuffs** [comment]
Fixed for next update.  Thank you for the report.
