### ISSUE TITLE
Shop signs

### ISSUE THREAD

**Issue by smudgerPH** [syl0r/Perpheads-Issues#75]
when the torch is turned on you can see what the shop signs really are (What the prop is)
![rp_paralake_city_v20045](https://cloud.githubusercontent.com/assets/11132778/6313479/ebb174e0-b9a4-11e4-99ac-6803481e8be8.jpg)

**Comment by Allabin** [comment]
Same for spotlights and it does not only remove the shop sign for the person with the flashlight, but for everyone in viewing distance of the sign.

**Comment by StephenPuffs** [comment]
Yes it's known, and at this time I do not have a solution
