### ISSUE TITLE
Taxi problem completely unfolded

### ISSUE THREAD

**Issue by Allabin** [syl0r/Perpheads-Issues#77]
After recieving several reports about people being charged 200$ when entering their own vehicles and soon after having the current taxi driver asking why he is not getting payed and him getting the message "The pessenger doesn't have any more money to pay for being driven around" (See equivalent passenger message: http://i.imgur.com/1FnACpa.jpg ).

I suspected a connection and decided to try and enter my own vehicle after being a passenger in the taxi and I recieved this when entering my own DeLorian http://i.imgur.com/BF2gMIR.jpg .
When asking around everyone else being charged 200$ for entering their own vehicle had been a passenger in a taxi prior to it. 

The Taxi Driver does not seems to be charged 200$ for entering his own car after leaving the taxi job (Tested with Chris).

Only way to fix this is to rejoin the server, respawning does not fix it.

**Comment by StephenPuffs** [comment]
Fixed for tomorrow
