### ISSUE TITLE
Cannot disband orgs.

### ISSUE THREAD

**Issue by Saltguy** [syl0r/Perpheads-Issues#78]
As the title says, when I tell the city hall clerk to disband my organization it says it's been done. It however does not work and the organization does not get disbanded.

**Comment by JDaymon** [comment]
Did you try doing it two times?

**Comment by Saltguy** [comment]
I've tried approx 7 times now.

**Comment by StephenPuffs** [comment]
Load your organization info with F3 then try disbanding.  Currently the organization system is terrible and extremely prone to bugs, we do plan on fixing this though.
