### ISSUE TITLE
Radios and other props can lift and move cars. 

### ISSUE THREAD

**Issue by KermitTheThug** [syl0r/Perpheads-Issues#83]
I'm not sure if this is a fixable problem but yesterday, I noticed someone moving a car the got stuck by a radio that they had dropped and they moved the whole car up and got it unstuck by carrying a radio with their fists.

**Comment by Minilarro** [comment]
This cannot be modifies i believe as It's Gmod physics. However doing this is a breaking rule 3.11 Leveraging Pushing, you should report anyone who does this in the future. If you or your car get stuck in a unrealistic way, make a /report and a staff member wil come and help you. If there's RC however I'd advise you to try making a RP sit if it isn't too silly.

**Comment by StephenPuffs** [comment]
As noted, there really isn't much that could be done about this, perhaps some but may result in buggy behavior.  So just do what @Minilarro said as its clearly unintended behavior that you are able to do that and violates rules.
