### ISSUE TITLE
Crafting Progressbar not updating correctly

### ISSUE THREAD

**Issue by coderiekelt** [syl0r/Perpheads-Issues#84]
Whenever you craft, it does not actually show progress, but it will only go from 0 to 100 when the crafting is actually complete.

**Comment by StephenPuffs** [comment]
Seems to function just fine for me.  It displays your total progress when not actively assembling, and your assembling progress when you are.

**Comment by AVAST4894** [comment]
same thing happens when you craft baretta m9
