### ISSUE TITLE
GMC Vandura lights

### ISSUE THREAD

**Issue by Minilarro** [syl0r/Perpheads-Issues#86]
The GMC Vandura's lights are currently misplaced i believe. The back lights hover behind the car and the front lights are a little bit too much as shown in the Image provided. They just seem a bit off. I know it's bad and I will try to upload a better one if needed.

Image:
http://i.imgur.com/n0leneK.png

**Comment by StephenPuffs** [comment]
I'll look into it, it may be a different model issue.  I don't remember seeing this last time I saw a Vandura.
