### ISSUE TITLE
Dodge Viper SRT's Issues

### ISSUE THREAD

**Issue by mehmetcan21** [syl0r/Perpheads-Issues#87]
1. When you access to trunk of vehicle, it doesnt do a /me action.

2. When you get out of the vehicle from driver seat, you get stuck.

3.Sometimes doesnt deal damage to driver after crashing so hard but sometimes it deals damage after crashing with 5-10 mph.

4. Wasting fuel SO MUCH in my opinion.

- Ultimate

**Comment by JDaymon** [comment]
For number 2) https://github.com/syl0r/Perpheads-Issues/issues/51

**Comment by mehmetcan21** [comment]
Thanks Daymon.
