### ISSUE TITLE
Remmington is awful.

### ISSUE THREAD

**Issue by BenStandish** [syl0r/Perpheads-Issues#91]
1. Doesn't even penetrate a wooden fence.
2. I put 18 bullets into an officer from the Projex entrance when I was 2 meters away, he didn't die.
3. Damage is also terri-bad, 2 shots in a civilians face to kill.

**Comment by EthanBelinsky** [comment]
No, it's actually decent. You just don't onebang everyone. Also 2 hits to body and 1 to face. And the body shots lead to quick bleeding out. It does penetrate. Even pistols penetrate.

**Comment by JDaymon** [comment]
@EthanBelinsky I believe he means that its bugged atm fr some reason.

**Comment by StephenPuffs** [comment]
Fixed for next update.  Issue was gun never reset it's number of shots so kept becoming more and more inaccurate as more shots were fired.
