### ISSUE TITLE
House buying bug

### ISSUE THREAD

**Issue by WoodyAndy** [syl0r/Perpheads-Issues#92]
When I go to bank and talk to NPC, then press "buy" button, nothing happens at all. Tried to buy different houses, still nothing.

**Comment by EthanBelinsky** [comment]
You have bought it. It says sold if you look at the house.

**Comment by WoodyAndy** [comment]
Nope, it's clearly a bug, the "buy" button is not highlighting and there is no apartments to sell

**Comment by gamingpeach** [comment]
Yep same thing happens to me, i cant earn any more and if i plant its got to be on a friends base. FIX THIS!

**Comment by Bamarin** [comment]
same thing for me too, i can't buy any house, so my org mates have to

**Comment by Bamarin** [comment]
I think I found out what the problem is: i tried to buy the house without any money in my pocket and ofc I couldn't buy it, then i witdrawed all the money i had in the bank, but again i couldn't buy it, so i deposited half of the money back in the bank and then i could buy the house

**Comment by StephenPuffs** [comment]
Buying properties now takes from either on hand or from bank, but will not take from a combination so be sure you have the amount in one of the two places.
