### ISSUE TITLE
Floating people with bats and scripting errors

### ISSUE THREAD

**Issue by BillySavery** [syl0r/Perpheads-Issues#98]
Okay so last night about 3am a load of us was fucking about with bats but it done this weird thing wear you couldn't see the hitting animation or the stance when you hold the bat. People were just floating around and you heard the hitting and swinging of the bat. Kinda like the whole situation where you came out of water and your person would be moving around on land doing the swimming animation.

And a little while ago every time I opened up my inventory wheel, something caused scripting errors and then I couldn't equip nothing because all it said was print name so I had to restart my Gmod.

**Comment by WimgotPiggot** [comment]
Can confirm, just encountered the inventory error, had to relog.


[ERROR] gamemodes/perp/gamemode/modules/inventorygui/inventorywheel/inventorywheel.lua:364: attempt to concatenate local 'itemcount' (a nil value)
  1. v - gamemodes/perp/gamemode/modules/inventorygui/inventorywheel/inventorywheel.lua:364
   2. unknown - lua/includes/modules/hook.lua:84

**Comment by Creepis** [comment]
Yeah, it's been here for a while now.Reproduce steps are simple, get a bat, swing it around, no walking animation, you are just dragging your legs across the floor sometimes.Getting into a car as a passenger can result in this for a few seconds.
![2015-04-12_00003](https://cloud.githubusercontent.com/assets/10688184/7105798/885c6e14-e12b-11e4-810f-c9cc9c041f83.jpg)

**Comment by StephenPuffs** [comment]
I labeled this as can't reproduce because on all test servers it works flawlessly, it seems to only happen on the live server for no apparent reason at this time.
